// ═══════════════════════════════════════════════════════════════════════════
// ترجمة — العربية
// مُجمّعة تحت window.I18N_AR، تُحمَّل قبل app.js (انظر index.html)، الذي
// يجمع بعد ذلك ملفات اللغات الثلاثة في سجل I18N.
// أي مفتاح غير موجود هنا يعود تلقائيًا إلى الفرنسية (انظر lang-fr.js).
// ═══════════════════════════════════════════════════════════════════════════
window.I18N_AR = {
    'app.subtitle': 'مدير',
    'nav.dashboard': 'الرئيسية',
    'nav.squad': 'التشكيلة',
    'nav.tactics': 'التكتيك',
    'nav.market': 'الانتقالات',
    'nav.staff': 'الطاقم الفني',
    'nav.standings': 'الترتيب',
    'nav.awards': 'الجوائز',
    'nav.shop': 'المتجر',
    'nav.campus': 'الحرم',
    'nav.home_mobile': 'الرئيسية',
    'nav.more': 'المزيد',
    'nav.profile': 'الملف الشخصي',
    'nav.reset': 'إعادة تعيين',
    'screen.tactics': 'مكتب التكتيك',
    'screen.standings': 'الترتيب',
    'screen.squad': 'التشكيلة الاحترافية',
    'screen.squad_sub': 'لاعبوك المتعاقدون حاليًا.',

    // ── الدفعة 1: بيانات اللعبة ──────────────────────────────────────────
    // الطاقم الفني
    'Entraîneur Adjoint': 'المدرب المساعد',
    'Bonus Tactique': 'مكافأة تكتيكية',
    'Kiné Chef': 'كبير المعالجين',
    'Récupération': 'التعافي',
    'Recruteur Chef': 'كبير الكشافين',
    'Précision scouting': 'دقة الكشف',
    'Médecin du Sport': 'طبيب رياضي',
    'Risque blessure': 'خطر الإصابة',
    'Manager des Jeunes': 'مدير الناشئين',
    'Progression académie': 'تطور الأكاديمية',

    // أزياء المدير
    'Costume Marine, cravate': 'بدلة كحلية، ربطة عنق',
    'Costume Noir, cravate': 'بدلة سوداء، ربطة عنق',
    'Gris moderne, col ouvert': 'رمادي عصري، ياقة مفتوحة',
    'Bordeaux élégant, cravate': 'خمري أنيق، ربطة عنق',
    'Vert olive, décontracté': 'أخضر زيتوني، غير رسمي',
    'Ivoire, cravate dorée': 'عاجي، ربطة ذهبية',
    'Sable, col mao': 'رملي، ياقة صينية',
    'Bleu nuit, pochette rouge': 'أزرق ليلي، منديل جيب أحمر',
    'Anthracite, boutons dorés': 'رمادي فحمي، أزرار ذهبية',
    'Prestige, revers ivoire': 'فاخرة، ياقة عاجية',

    // متجر الرصيد (راحة/تجميل)
    'Relancer les objectifs': 'إعادة سحب الأهداف',
    "Tire trois nouveaux objectifs hebdomadaires.": "يسحب ثلاثة أهداف أسبوعية جديدة.",
    'Révéler un joueur': 'كشف لاعب',
    "Dévoile les statistiques d'un joueur non supervisé du marché.": "يكشف إحصائيات لاعب غير مُستكشف في السوق.",
    'Tenue Ivoire': 'زي عاجي',
    "Costume ivoire, cravate dorée.": "بدلة عاجية، ربطة عنق ذهبية.",
    'Tenue Sable': 'زي رملي',
    "Costume sable, col mao.": "بدلة رملية، ياقة صينية.",
    'Tenue Bleu nuit': 'زي أزرق ليلي',
    "Bleu nuit, pochette rouge.": "أزرق ليلي، منديل جيب أحمر.",
    'Tenue Or': 'زي ذهبي',
    "Costume anthracite, boutons dorés.": "بدلة رمادية فحمية، أزرار ذهبية.",
    'Portée': 'مرتدى',
    'Porter': 'ارتداء',

    // الأهداف الأسبوعية
    'Gagner 2 matchs': 'الفوز بمباراتين',
    'Marquer 5 buts': 'تسجيل 5 أهداف',
    'Garder 1 cage inviolée': 'الحفاظ على نظافة الشباك مرة',
    'Gagner 3 points de stat': 'كسب 3 نقاط إحصائية',
    'Rester 3 matchs invaincu': 'عدم الهزيمة في 3 مباريات',
    'Un joueur noté 8.0 ou plus': 'لاعب بتقييم 8.0 أو أعلى',
    'Objectif rempli': 'اكتمل الهدف',
    'crédits': 'رصيد',

    // قمصان النادي
    'Historique': 'كلاسيكي',
    'Rayé': 'مخطط',
    'Cerclé': 'محلق',
    'Écharpe': 'وشاح',
    'Or & Nuit': 'ذهبي وليلي',
    'Flamme': 'لهب',

    // الملاعب
    'Terre Battue': 'الملعب الترابي',
    "Le terrain d'origine du club — poussiéreux mais chaleureux.": "ملعب النادي الأصلي — ترابي لكنه مفعم بالحماس.",
    'Tribune Populaire': 'المدرج الشعبي',
    "Des tribunes qui se remplissent, une ambiance qui monte.": "مدرجات تمتلئ، وأجواء تشتعل.",
    'Arène Moderne': 'الملعب الحديث',
    "Béton et acier — un stade aux normes continentales.": "خرسانة وفولاذ — ملعب بمعايير قارية.",
    'Nocturne': 'مباراة ليلية',
    "Sous les projecteurs — l'ambiance électrique des matchs en soirée.": "تحت الأضواء — أجواء كهربائية لمباريات المساء.",
    'Nocturne Doré': 'ليلة ذهبية',
    "La même nuit électrique, habillée d'or — exclusif.": "نفس الليلة الكهربائية، بحلة ذهبية — حصري.",
    'Arène Continentale': 'الملعب القاري',
    "Le décor des grands soirs de CAF — bleu et lumière.": "أجواء ليالي الكاف الكبرى — أزرق وضوء.",
    'Jour de Finale': 'يوم النهائي',
    "Feux d'artifice et confettis — le stade d'un soir de sacre.": "ألعاب نارية وقصاصات ورقية — ملعب ليلة التتويج.",

    // احتفالات الأهداف
    'Classique': 'كلاسيكي',
    'Sprint au coin': 'ركضة الركنية',
    'Glissade': 'انزلاقة الركبتين',
    'Virage en fusion': 'المدرج المشتعل',
    "Feu d'artifice": 'ألعاب نارية',
    'Statut de légende': 'مكانة الأسطورة',
    'Nuit continentale': 'ليلة قارية',
    'Roue de la Fortune': 'عجلة الحظ',
    'Tour gratuit du jour': 'الدورة المجانية اليومية',

    // شارات الملف الشخصي
    'Aucun': 'لا شيء',
    'Sur le banc': 'على مقاعد البدلاء',
    'Tacticien': 'خبير التكتيك',
    'Bâtisseur': 'البنّاء',
    'Gagneur': 'الفائز',
    'Légende': 'أسطورة',
    'Icône continentale': 'أيقونة قارية',

    // الحرم الجامعي (الملعب)
    'Tribunes agrandies': 'مدرجات موسعة',
    "Plus de places disponibles à domicile — hausse directe du plafond de billetterie.": "المزيد من المقاعد في الديار — رفع مباشر لسقف التذاكر.",
    'Boutique du Club': 'متجر النادي',
    "Maillots et produits dérivés — un revenu fixe supplémentaire à chaque match.": "قمصان ومنتجات — دخل ثابت إضافي في كل مباراة.",
    'Espace VIP': 'صالة كبار الشخصيات',
    "Loges premium pour sponsors et invités — revenu de prestige à chaque match.": "أجنحة فاخرة للرعاة والضيوف — دخل مرموق في كل مباراة.",
    'Chaudron & Ambiance': 'المرجل والأجواء',
    "Un stade qui vibre attire plus de monde — billetterie additionnelle à domicile.": "ملعب نابض بالحياة يجذب المزيد من الجماهير — تذاكر إضافية في الديار.",
    'Écran Géant': 'شاشة عملاقة',
    "Purement visuel — l'ambiance du jour de match, sans effet sur les recettes.": "بصري فقط — أجواء يوم المباراة، دون أي تأثير على الإيرادات.",

    // جوائز نهاية الموسم
    "Ballon d'Or Africain": "الكرة الذهبية الأفريقية",
    "Le meilleur joueur du continent, tous postes confondus.": "أفضل لاعب في القارة، بجميع المراكز.",
    "Soulier d'Or Africain": "الحذاء الذهبي الأفريقي",
    "Le plus grand buteur des 10 championnats.": "أفضل هداف في الدوريات العشرة.",
    "Meilleur Passeur Africain": "أفضل صانع ألعاب أفريقي",
    "Le maître à jouer de la saison.": "عبقري خط الوسط في الموسم.",
    "Gant d'Or Africain": "القفاز الذهبي الأفريقي",
    "Le gardien le plus infranchissable.": "الحارس الأكثر صعوبة في الاختراق.",
    "Meilleur Espoir Africain": "أفضل لاعب واعد أفريقي",
    "Le meilleur joueur de 21 ans ou moins.": "أفضل لاعب يبلغ 21 عامًا أو أقل.",
    "Meilleur buteur du championnat": "هداف الدوري",
    "Le canonnier de votre championnat.": "قناص دوريك.",
    'Non attribué cette saison': 'لم تُمنح هذا الموسم',
    'm. joués': 'مباراة',
    'passes déc.': 'تمريرة حاسمة',
    'buts': 'أهداف',
    'passes': 'تمريرات',
    'Prime sponsors': 'مكافأة الرعاة',
    'Prime versée à': 'مكافأة مدفوعة إلى',

    // ── الدفعة 2: المتجر + الحرم الجامعي ─────────────────────────────────
    'Poignée de crédits': 'حفنة من الرصيد',
    'Sac de crédits': 'كيس من الرصيد',
    'Coffre de crédits': 'صندوق من الرصيد',
    'Édition Manager': 'إصدار المدير',
    "Retire les publicités imposées, offre 1000 crédits, la tenue Or exclusive et un second emplacement de carrière.": "يزيل الإعلانات الإجبارية، ويمنح 1000 رصيد، والزي الذهبي الحصري، وفتحة مسيرة ثانية.",
    "Débloque la piste Prestige du pass en cours : cosmétiques exclusifs et crédits à chaque palier.": "يفتح مسار الفخامة للتذكرة الحالية: عناصر تجميلية حصرية ورصيد في كل مستوى.",
    'Offre de bienvenue': 'عرض الترحيب',
    "1200 crédits, 150 gemmes, la tenue Ivoire et un Pack Découverte (1 joueur confirmé) offerts. Réservée à votre première saison.": "1200 رصيد، 150 جوهرة، الزي العاجي وحزمة اكتشاف مجانية (لاعب واحد مؤكد). حصري لموسمك الأول.",
    'Abonnement VIP': 'اشتراك كبار الشخصيات',
    "80 crédits chaque jour, 60 gemmes à chaque renouvellement, publicités imposées retirées, badge VIP. Reconduction automatique chaque mois à 2,49 € jusqu'à résiliation — résiliable à tout moment depuis le Play Store.": "80 رصيد يوميًا، 60 جوهرة عند كل تجديد، إزالة الإعلانات الإجبارية، شارة كبار الشخصيات. يتجدد تلقائيًا شهريًا بسعر 2.49 يورو حتى الإلغاء — يمكن الإلغاء في أي وقت من متجر Play.",
    'Sachet de gemmes': 'كيس جواهر صغير',
    'Bourse de gemmes': 'كيس جواهر',
    'Coffre de gemmes': 'صندوق جواهر',
    'Pack Découverte': 'حزمة الاكتشاف',
    "1 joueur confirmé (80-85), immédiatement dans l'effectif.": "لاعب واحد مؤكد (80-85)، يُضاف فورًا إلى التشكيلة.",
    'Pack Talents': 'حزمة المواهب',
    "3 joueurs confirmés (80-88) en un seul tirage.": "3 لاعبين مؤكدين (80-88) في سحب واحد.",
    'Pack Génération': 'حزمة الجيل',
    "6 joueurs confirmés (83-92) — un effectif de stars d'un coup.": "6 لاعبين مؤكدين (83-92) — تشكيلة من النجوم دفعة واحدة.",
    '80 crédits': '80 رصيد',
    '220 crédits': '220 رصيد',
    '20 gemmes': '20 جوهرة',
    '50 gemmes': '50 جوهرة',
    'Révélation gratuite': 'كشف مجاني',
    'Pack Découverte offert': 'حزمة اكتشاف مجانية',
    'Jackpot — 180 gemmes': 'الجائزة الكبرى — 180 جوهرة',
    'Populaire': 'الأكثر رواجًا',
    'Meilleure valeur': 'أفضل قيمة',
    'Une fois': 'مرة واحدة',
    'Restaurer': 'استعادة',
    'Actif': 'مفعّل',
    'Tourner': 'تدوير',
    'gemmes': 'جواهر',

    // ── الدفعة 3: شاشات اللعبة (البداية) ─────────────────────────────────
    'Exige un transfert': 'يطالب بالانتقال',
    'Transfert': 'انتقال',
    'Réclame du temps de jeu': 'يطالب بمزيد من وقت اللعب',
    'Frustré': 'محبط',
    'Refuser': 'رفض',
    'Récupérer': 'استلام',
    'Prêter': 'إعارة',
    'Fermer': 'إغلاق',
    'Accepter': 'قبول',
    'Valider': 'تأكيد',
    'Tout auto': 'تعبئة تلقائية',
    'Reprendre le match': 'استئناف المباراة',
    'Rencontrer': 'مقابلة',
    'Mon club': 'ناديي',
    'Licencier': 'إقالة',
    'Ignorer': 'تجاهل',
    'Décliner': 'رفض',
    'Compositions': 'التشكيلات',
    'Annuler': 'إلغاء',
    'Afrique': 'أفريقيا',

    // ── الدفعة 3 (تابع): الانتقالات، الأكاديمية، الطاقم ──────────────────
    'Tous postes': 'كل المراكز',
    'Tous prix': 'كل الأسعار',
    'Tout niveau': 'كل المستويات',
    'Rafraîchir les agents libres': 'تحديث اللاعبين الأحرار',
    'Infrastructures': 'المنشآت',
    'Niv. Max Atteint': 'تم بلوغ الحد الأقصى',
    'Améliorer': 'ترقية',
    'Débutant': 'مبتدئ',
    'Confirmé': 'متمرس',
    'Expérimenté': 'ذو خبرة',
    'Réputé': 'مرموق',
    'Élite': 'النخبة',
    'ans': 'سنة',

    // ── الدفعة 4: الإشعارات، صندوق الوارد، المقابلات ─────────────────────
    'Aucun message': 'لا توجد رسائل',
    'Offre reçue': 'عرض مستلم',
    'Recrutement': 'تعاقد',
    'Demande de prêt': 'طلب إعارة',
    'Proposition': 'عرض',
    'Alerte': 'تنبيه',
    'Contrat': 'عقد',
    'Vestiaire': 'غرفة الملابس',
    'Palier': 'مستوى',
    'Distinction': 'جائزة',
    'Objectif': 'هدف',
    'Quotidien': 'يومي',
    'Info': 'معلومة',
    'Bonus': 'مكافأة',
    'Une réaction ?': 'أي رد فعل؟',
    'Le défendre publiquement': 'الدفاع عنه علنًا',
    'Prendre ses distances': 'النأي بالنفس',
    'Ne pas réagir': 'عدم الرد',
    'Le féliciter publiquement': 'تهنئته علنًا',
    'Recentrer sur le collectif': 'التركيز على الفريق',
    'Rester factuel': 'التزام الموضوعية',

    // ── الدفعة 4 (تابع): تعليقات المباراة المباشرة ───────────────────────
    "L'arbitre siffle le coup d'envoi. C'est parti !": "يصفر الحكم بداية المباراة. لقد انطلقنا!",
    "Mi-temps. Les équipes rentrent aux vestiaires.": "الشوط الأول. الفريقان يعودان إلى غرف الملابس.",
    "Fin de la première période de prolongation.": "نهاية الشوط الأول من الوقت الإضافي.",
    "Fin du temps réglementaire.": "نهاية الوقت الأصلي.",
    "Coup de sifflet final !": "صافرة النهاية!",
    "PENALTY sifflé pour": "ركلة جزاء لصالح",
    "place le ballon sur le point.": "يضع الكرة على البقعة.",
    "Corner pour": "ركلة ركنية لصالح",
    "Coup franc dangereux pour": "ركلة حرة خطيرة لصالح",
    "se charge du ballon.": "يتولى تنفيذها.",
    "EXPULSION !": "طرد!",
    "voit son 2e carton jaune !": "يحصل على بطاقته الصفراء الثانية!",
    "Faute tactique. Carton jaune pour": "خطأ تكتيكي. بطاقة صفراء لـ",
    "CARTON ROUGE DIRECT !": "بطاقة حمراء مباشرة!",
    "Faute grossière de": "خطأ فادح من",
    "BLESSURE !": "إصابة!",
    "est touché": "يتعرض للإصابة",
    "Son énergie s'effondre, remplacez-le vite !": "طاقته تنهار، بدّله بسرعة!",
    "Changement :": "تبديل:",
    "remplace": "يحل محل",
    "sorti sur blessure.": "الذي خرج بداعي الإصابة.",
    "Coup dur pour l'adversaire :": "ضربة موجعة للخصم:",
    "sort sur civière et l'équipe n'a plus de remplaçant !": "يُخرج على نقالة والفريق ليس لديه بدلاء متبقون!",
    "Action fulgurante de": "هجمة خاطفة من",
    "La défense de": "دفاع",
    "repousse le danger.": "يبعد الخطر.",

    // ── الدفعة 6: تعليقات المباراة (تابع) ─────────────────────────────────
    "Toujours rien pour départager les deux clubs — on joue la prolongation (2 × 15 min).": "لا شيء يفصل بين الفريقين حتى الآن — نلعب وقتًا إضافيًا (2 × 15 دقيقة).",
    "Prolongation ! Un 6e remplacement vous est accordé.": "وقت إضافي! تم منحك تبديلاً سادسًا.",
    "minute(s) de temps additionnel.": "دقيقة (دقائق) وقت بدل ضائع.",
    "Séance de tirs au but :": "ركلات الترجيح:",
    "se qualifie !": "يتأهل!",
    "Changement tactique pour l'adversaire.": "تبديل تكتيكي للخصم.",

    // ── الدفعة 7: تعليقات الأهداف ──────────────────────────────────────────
    'BUT !': 'هــدف!',
    'sert': 'يمرر لـ',
    'qui conclut en beauté !': 'الذي يسددها بشكل رائع!',
    'Quelle passe de': 'يا لها من تمريرة من',
    'ne pouvait pas rater !': 'لم يكن ليخطئها!',
    'Superbe centre de': 'عرضية رائعة من',
    'pour': 'إلى',
    'BUT SUR PENALTY !': 'هدف من ركلة جزاء!',
    'transforme avec sang-froid !': 'يسددها ببرود أعصاب!',
    'COUP FRANC DIRECT !': 'ركلة حرة مباشرة!',
    'enroule par-dessus le mur !': 'يلفها فوق الحائط!',
    'BUT EXCEPTIONNEL !': 'هدف استثنائي!',
    'Frappe de': 'تسديدة من',
    'à': 'من مسافة',
    'mètres': 'أمتار',
    'place parfaitement son tir': 'يضع تسديدته بدقة',
    'à bout portant': 'من مسافة قريبة جدًا',
    'INCROYABLE RATÉ !': 'إهدار لا يُصدق!',
    'était seul face au but !': 'كان منفردًا بالمرمى!',
    'ARRÊT MIRACULEUX !': 'تصدٍ معجزة!',
    'Le gardien sauve son équipe face à': 'الحارس ينقذ فريقه أمام',
    'Frappe lointaine de': 'تسديدة من بعيد من',
    'qui passe loin du cadre.': 'تمر بعيدًا عن المرمى.',
    'Tir dans un angle fermé de': 'تسديدة من زاوية ضيقة من',
    'capté tranquillement par le gardien.': 'يمسكها الحارس بهدوء.',
    'Bel arrêt du gardien sur cette frappe de': 'تصدٍ جميل من الحارس لتسديدة',
    'dévisse légèrement son tir.': 'يخطئ تصويبته قليلاً.',
    'La défense se jette et contre la frappe de': 'الدفاع يرمي بنفسه ويصد تسديدة',

    // ── الدفعة 8: شاشة الكاف ───────────────────────────────────────────────
    "Votre club n'est pas qualifié cette saison — terminez": "ناديك غير مؤهل هذا الموسم — أنهِ",
    'Top 2': 'المركز الثاني أو أفضل',
    'de votre championnat pour participer.': 'في دوريك للمشاركة.',
    'Votre club est éliminé': 'تم إقصاء ناديك',
    'Sorti en': 'خرج في',
    'Phase de groupes': 'دور المجموعات',
    'Demi-finale': 'نصف النهائي',
    'vous pouvez suivre la suite de la compétition en spectateur.': 'يمكنك متابعة باقي البطولة كمتفرج.',
    "Champion d'Afrique": 'بطل أفريقيا',
    'GROUPE': 'المجموعة',
    'Votre groupe': 'مجموعتك',
    'Club': 'النادي',
    'V': 'ف',
    'N': 'ت',
    'D': 'خ',
    'Pts': 'نقاط',
    'Quarts de finale': 'ربع النهائي',
    'Aller': 'الذهاب',
    'Retour': 'الإياب',
    'Finale': 'النهائي',

    // ── الدفعة 9: الترتيب + أحاديث الاستراحة ─────────────────────────────
    'j': 'ج',
    'Rester calme': 'الهدوء',
    "On ne change rien, on continue.": "لا نغيّر شيئًا، نواصل.",
    'Encourager': 'التشجيع',
    "Vous leur dites votre confiance.": "تُظهر لهم ثقتك بهم.",
    'Secouer': 'الحزم',
    "Le ton monte dans le vestiaire.": "ترتفع حدة النبرة في غرفة الملابس.",
    'Exiger le bloc': 'التماسك الدفاعي',
    "Consignes serrées, on verrouille.": "تعليمات صارمة، نُحكم الإغلاق.",
    "Vous menez à la pause. Le vestiaire est chaud.": "تتقدم في الاستراحة. الأجواء حماسية في غرفة الملابس.",
    "Vous êtes menés. Onze paires d'yeux vous regardent.": "أنت متأخر في النتيجة. أحد عشر زوجًا من العيون تراقبك.",
    "Tout reste à faire. Le match se joue maintenant.": "كل شيء لا يزال ممكنًا. المباراة تُحسم الآن."
};
