// ═══════════════════════════════════════════════════════════════════════════
// TRANSLATION — ENGLISH
// Grouped under window.I18N_EN, loaded BEFORE app.js (see index.html), which
// then assembles the three language files into the I18N registry.
// Any key missing here falls back to French (see lang-fr.js / t() in app.js).
// ═══════════════════════════════════════════════════════════════════════════
window.I18N_EN = {
    'app.subtitle': 'Manager',
    'nav.dashboard': 'Dashboard',
    'nav.squad': 'Squad',
    'nav.tactics': 'Tactics',
    'nav.market': 'Transfers',
    'nav.staff': 'Staff',
    'nav.standings': 'Standings',
    'nav.awards': 'Awards',
    'nav.shop': 'Shop',
    'nav.campus': 'Campus',
    'nav.home_mobile': 'Home',
    'nav.more': 'More',
    'nav.profile': 'Profile',
    'nav.reset': 'Reset',
    'screen.tactics': 'Tactics Office',
    'screen.standings': 'Standings',
    'screen.squad': 'Pro Squad',
    'screen.squad_sub': 'Your players currently under contract.',

    // ── PASSE 1 : DONNÉES DE JEU ─────────────────────────────────────────
    // Staff
    'Entraîneur Adjoint': 'Assistant Coach',
    'Bonus Tactique': 'Tactical Bonus',
    'Kiné Chef': 'Head Physio',
    'Récupération': 'Recovery',
    'Recruteur Chef': 'Head Scout',
    'Précision scouting': 'Scouting Accuracy',
    'Médecin du Sport': 'Sports Doctor',
    'Risque blessure': 'Injury Risk',
    'Manager des Jeunes': 'Youth Manager',
    'Progression académie': 'Academy Progress',

    // Tenues du manager
    'Costume Marine, cravate': 'Navy Suit, Tie',
    'Costume Noir, cravate': 'Black Suit, Tie',
    'Gris moderne, col ouvert': 'Modern Grey, Open Collar',
    'Bordeaux élégant, cravate': 'Elegant Maroon, Tie',
    'Vert olive, décontracté': 'Olive Green, Casual',
    'Ivoire, cravate dorée': 'Ivory, Gold Tie',
    'Sable, col mao': 'Sand, Mandarin Collar',
    'Bleu nuit, pochette rouge': 'Midnight Blue, Red Pocket Square',
    'Anthracite, boutons dorés': 'Charcoal, Gold Buttons',
    'Prestige, revers ivoire': 'Prestige, Ivory Lapel',

    // Boutique de crédits (confort/cosmétique)
    'Relancer les objectifs': 'Reroll Objectives',
    "Tire trois nouveaux objectifs hebdomadaires.": "Draws three new weekly objectives.",
    'Révéler un joueur': 'Reveal a Player',
    "Dévoile les statistiques d'un joueur non supervisé du marché.": "Reveals the stats of an unscouted market player.",
    'Tenue Ivoire': 'Ivory Suit',
    "Costume ivoire, cravate dorée.": "Ivory suit, gold tie.",
    'Tenue Sable': 'Sand Suit',
    "Costume sable, col mao.": "Sand suit, mandarin collar.",
    'Tenue Bleu nuit': 'Midnight Blue Suit',
    "Bleu nuit, pochette rouge.": "Midnight blue, red pocket square.",
    'Tenue Or': 'Gold Suit',
    "Costume anthracite, boutons dorés.": "Charcoal suit, gold buttons.",
    'Portée': 'Worn',
    'Porter': 'Wear',

    // Objectifs hebdomadaires
    'Gagner 2 matchs': 'Win 2 matches',
    'Marquer 5 buts': 'Score 5 goals',
    'Garder 1 cage inviolée': 'Keep 1 clean sheet',
    'Gagner 3 points de stat': 'Gain 3 stat points',
    'Rester 3 matchs invaincu': 'Go unbeaten in 3 matches',
    'Un joueur noté 8.0 ou plus': 'A player rated 8.0 or higher',
    'Objectif rempli': 'Objective completed',
    'crédits': 'credits',

    // Maillots du club
    'Historique': 'Classic',
    'Rayé': 'Striped',
    'Cerclé': 'Hooped',
    'Écharpe': 'Sash',
    'Or & Nuit': 'Gold & Night',
    'Flamme': 'Flame',

    // Stades
    'Terre Battue': 'Dusty Pitch',
    "Le terrain d'origine du club — poussiéreux mais chaleureux.": "The club's original ground — dusty but full of heart.",
    'Tribune Populaire': 'Popular Stand',
    "Des tribunes qui se remplissent, une ambiance qui monte.": "Stands filling up, atmosphere rising.",
    'Arène Moderne': 'Modern Arena',
    "Béton et acier — un stade aux normes continentales.": "Concrete and steel — a stadium built to continental standards.",
    'Nocturne': 'Night Match',
    "Sous les projecteurs — l'ambiance électrique des matchs en soirée.": "Under the floodlights — the electric feel of evening matches.",
    'Nocturne Doré': 'Golden Night',
    "La même nuit électrique, habillée d'or — exclusif.": "The same electric night, dressed in gold — exclusive.",
    'Arène Continentale': 'Continental Arena',
    "Le décor des grands soirs de CAF — bleu et lumière.": "The backdrop of big CAF nights — blue and light.",
    'Jour de Finale': 'Final Day',
    "Feux d'artifice et confettis — le stade d'un soir de sacre.": "Fireworks and confetti — the stadium on a night of glory.",

    // Célébrations de but
    'Classique': 'Classic',
    'Sprint au coin': 'Corner Sprint',
    'Glissade': 'Knee Slide',
    'Virage en fusion': 'Stand on Fire',
    "Feu d'artifice": 'Fireworks',
    'Statut de légende': 'Legend Status',
    'Nuit continentale': 'Continental Night',
    'Roue de la Fortune': 'Wheel of Fortune',
    'Tour gratuit du jour': "Today's Free Spin",

    // Badges de profil
    'Aucun': 'None',
    'Sur le banc': 'On the Bench',
    'Tacticien': 'Tactician',
    'Bâtisseur': 'Builder',
    'Gagneur': 'Winner',
    'Légende': 'Legend',
    'Icône continentale': 'Continental Icon',

    // Campus
    'Tribunes agrandies': 'Expanded Stands',
    "Plus de places disponibles à domicile — hausse directe du plafond de billetterie.": "More seats at home — a direct boost to your ticketing cap.",
    'Boutique du Club': 'Club Store',
    "Maillots et produits dérivés — un revenu fixe supplémentaire à chaque match.": "Shirts and merchandise — extra fixed income every match.",
    'Espace VIP': 'VIP Lounge',
    "Loges premium pour sponsors et invités — revenu de prestige à chaque match.": "Premium boxes for sponsors and guests — prestige income every match.",
    'Chaudron & Ambiance': 'Cauldron & Atmosphere',
    "Un stade qui vibre attire plus de monde — billetterie additionnelle à domicile.": "A buzzing stadium draws bigger crowds — extra home ticketing.",
    'Écran Géant': 'Giant Screen',
    "Purement visuel — l'ambiance du jour de match, sans effet sur les recettes.": "Purely visual — matchday atmosphere, no effect on revenue.",

    // Trophées de fin de saison
    "Ballon d'Or Africain": "African Ballon d'Or",
    "Le meilleur joueur du continent, tous postes confondus.": "The continent's best player, across all positions.",
    "Soulier d'Or Africain": "African Golden Boot",
    "Le plus grand buteur des 10 championnats.": "The top scorer across all 10 leagues.",
    "Meilleur Passeur Africain": "African Playmaker of the Year",
    "Le maître à jouer de la saison.": "The season's midfield maestro.",
    "Gant d'Or Africain": "African Golden Glove",
    "Le gardien le plus infranchissable.": "The most impenetrable goalkeeper.",
    "Meilleur Espoir Africain": "African Young Player of the Year",
    "Le meilleur joueur de 21 ans ou moins.": "The best player aged 21 or under.",
    "Meilleur buteur du championnat": "League Top Scorer",
    "Le canonnier de votre championnat.": "The sharpshooter of your league.",
    'Non attribué cette saison': 'Not awarded this season',
    'm. joués': 'apps',
    'passes déc.': 'assists',
    'buts': 'goals',
    'passes': 'assists',
    'Prime sponsors': 'Sponsor bonus',
    'Prime versée à': 'Bonus paid to',

    // ── PASSE 2 : BOUTIQUE + CAMPUS ──────────────────────────────────────
    'Poignée de crédits': 'Handful of Credits',
    'Sac de crédits': 'Bag of Credits',
    'Coffre de crédits': 'Chest of Credits',
    'Édition Manager': 'Manager Edition',
    "Retire les publicités imposées, offre 1000 crédits, la tenue Or exclusive et un second emplacement de carrière.": "Removes forced ads, grants 1000 credits, the exclusive Gold suit and a second career slot.",
    "Débloque la piste Prestige du pass en cours : cosmétiques exclusifs et crédits à chaque palier.": "Unlocks the Prestige track of the current pass: exclusive cosmetics and credits at every tier.",
    'Offre de bienvenue': 'Welcome Offer',
    "1200 crédits, 150 gemmes, la tenue Ivoire et un Pack Découverte (1 joueur confirmé) offerts. Réservée à votre première saison.": "1200 credits, 150 gems, the Ivory suit and a free Discovery Pack (1 confirmed player). First-season only.",
    'Abonnement VIP': 'VIP Subscription',
    "80 crédits chaque jour, 60 gemmes à chaque renouvellement, publicités imposées retirées, badge VIP. Reconduction automatique chaque mois à 2,49 € jusqu'à résiliation — résiliable à tout moment depuis le Play Store.": "80 credits every day, 60 gems on every renewal, forced ads removed, VIP badge. Auto-renews monthly at €2.49 until cancelled — cancel anytime from the Play Store.",
    'Sachet de gemmes': 'Small Gem Pouch',
    'Bourse de gemmes': 'Gem Purse',
    'Coffre de gemmes': 'Gem Chest',
    'Pack Découverte': 'Discovery Pack',
    "1 joueur confirmé (80-85), immédiatement dans l'effectif.": "1 confirmed player (80-85), added to your squad instantly.",
    'Pack Talents': 'Talent Pack',
    "3 joueurs confirmés (80-88) en un seul tirage.": "3 confirmed players (80-88) in one draw.",
    'Pack Génération': 'Generation Pack',
    "6 joueurs confirmés (83-92) — un effectif de stars d'un coup.": "6 confirmed players (83-92) — a squad of stars in one go.",
    '80 crédits': '80 credits',
    '220 crédits': '220 credits',
    '20 gemmes': '20 gems',
    '50 gemmes': '50 gems',
    'Révélation gratuite': 'Free Reveal',
    'Pack Découverte offert': 'Free Discovery Pack',
    'Jackpot — 180 gemmes': 'Jackpot — 180 gems',
    'Populaire': 'Popular',
    'Meilleure valeur': 'Best Value',
    'Une fois': 'One-time',
    'Restaurer': 'Restore',
    'Actif': 'Active',
    'Tourner': 'Spin',
    'gemmes': 'gems',

    // ── PASSE 3 : ÉCRANS DE JEU (débuts) ─────────────────────────────────
    'Exige un transfert': 'Demands a transfer',
    'Transfert': 'Transfer',
    'Réclame du temps de jeu': 'Wants more playing time',
    'Frustré': 'Frustrated',
    'Refuser': 'Decline',
    'Récupérer': 'Claim',
    'Prêter': 'Loan',
    'Fermer': 'Close',
    'Accepter': 'Accept',
    'Valider': 'Confirm',
    'Tout auto': 'Auto-fill',
    'Reprendre le match': 'Resume Match',
    'Rencontrer': 'Meet',
    'Mon club': 'My Club',
    'Licencier': 'Dismiss',
    'Ignorer': 'Dismiss',
    'Décliner': 'Decline',
    'Compositions': 'Line-ups',
    'Annuler': 'Cancel',
    'Afrique': 'Africa',

    // ── PASSE 3 (suite) : Mercato, Académie, Staff ───────────────────────
    'Tous postes': 'All positions',
    'Tous prix': 'All prices',
    'Tout niveau': 'All ratings',
    'Rafraîchir les agents libres': 'Refresh free agents',
    'Infrastructures': 'Facilities',
    'Niv. Max Atteint': 'Max Level Reached',
    'Améliorer': 'Upgrade',
    'Débutant': 'Rookie',
    'Confirmé': 'Seasoned',
    'Expérimenté': 'Experienced',
    'Réputé': 'Renowned',
    'Élite': 'Elite',
    'ans': 'y/o',

    // ── PASSE 4 : NOTIFICATIONS, BOÎTE DE RÉCEPTION, INTERVIEWS ──────────
    'Aucun message': 'No messages',
    'Offre reçue': 'Offer received',
    'Recrutement': 'Signing',
    'Demande de prêt': 'Loan request',
    'Proposition': 'Offer',
    'Alerte': 'Alert',
    'Contrat': 'Contract',
    'Vestiaire': 'Dressing Room',
    'Palier': 'Tier',
    'Distinction': 'Award',
    'Objectif': 'Objective',
    'Quotidien': 'Daily',
    'Info': 'News',
    'Bonus': 'Bonus',
    'Une réaction ?': 'Any reaction?',
    'Le défendre publiquement': 'Defend him publicly',
    'Prendre ses distances': 'Distance yourself',
    'Ne pas réagir': "Don't react",
    'Le féliciter publiquement': 'Praise him publicly',
    'Recentrer sur le collectif': 'Refocus on the team',
    'Rester factuel': 'Stay factual',

    // ── PASSE 4 (suite) : COMMENTAIRES DE MATCH EN DIRECT ────────────────
    "L'arbitre siffle le coup d'envoi. C'est parti !": "The referee blows the whistle. Kick-off!",
    "Mi-temps. Les équipes rentrent aux vestiaires.": "Half-time. The teams head to the dressing rooms.",
    "Fin de la première période de prolongation.": "End of the first period of extra time.",
    "Fin du temps réglementaire.": "End of regulation time.",
    "Coup de sifflet final !": "Full time!",
    "PENALTY sifflé pour": "PENALTY awarded to",
    "place le ballon sur le point.": "places the ball on the spot.",
    "Corner pour": "Corner for",
    "Coup franc dangereux pour": "Dangerous free kick for",
    "se charge du ballon.": "steps up to take it.",
    "EXPULSION !": "SENT OFF!",
    "voit son 2e carton jaune !": "picks up a second yellow card!",
    "Faute tactique. Carton jaune pour": "Tactical foul. Yellow card for",
    "CARTON ROUGE DIRECT !": "STRAIGHT RED CARD!",
    "Faute grossière de": "A reckless foul from",
    "BLESSURE !": "INJURY!",
    "est touché": "is down injured",
    "Son énergie s'effondre, remplacez-le vite !": "His energy is collapsing, sub him off quickly!",
    "Changement :": "Substitution:",
    "remplace": "replaces",
    "sorti sur blessure.": "who went off injured.",
    "Coup dur pour l'adversaire :": "Tough break for the opposition:",
    "sort sur civière et l'équipe n'a plus de remplaçant !": "is stretchered off and the team has no substitutes left!",
    "Action fulgurante de": "A lightning move from",
    "La défense de": "The defense of",
    "repousse le danger.": "clears the danger.",

    // ── PASSE 6 : commentaires de match (suite) ───────────────────────────
    "Toujours rien pour départager les deux clubs — on joue la prolongation (2 × 15 min).": "Still nothing to separate the two sides — on to extra time (2 × 15 min).",
    "Prolongation ! Un 6e remplacement vous est accordé.": "Extra time! You're granted a 6th substitution.",
    "minute(s) de temps additionnel.": "minute(s) of added time.",
    "Séance de tirs au but :": "Penalty shootout:",
    "se qualifie !": "goes through!",
    "Changement tactique pour l'adversaire.": "Tactical change for the opposition.",

    // ── PASSE 7 : commentaires de but ────────────────────────────────────
    'BUT !': 'GOAL!',
    'sert': 'sets up',
    'qui conclut en beauté !': 'who finishes in style!',
    'Quelle passe de': 'What a pass from',
    'ne pouvait pas rater !': 'couldn\'t miss that!',
    'Superbe centre de': 'A superb cross from',
    'pour': 'for',
    'BUT SUR PENALTY !': 'GOAL FROM THE SPOT!',
    'transforme avec sang-froid !': 'converts ice-cold!',
    'COUP FRANC DIRECT !': 'DIRECT FREE KICK!',
    'enroule par-dessus le mur !': 'curls it over the wall!',
    'BUT EXCEPTIONNEL !': 'STUNNING GOAL!',
    'Frappe de': 'A strike from',
    'à': 'from',
    'mètres': 'meters out',
    'place parfaitement son tir': 'places his shot perfectly',
    'à bout portant': 'from point-blank range',
    'INCROYABLE RATÉ !': 'UNBELIEVABLE MISS!',
    'était seul face au but !': 'was clean through on goal!',
    'ARRÊT MIRACULEUX !': 'MIRACLE SAVE!',
    'Le gardien sauve son équipe face à': 'The keeper bails his team out against',
    'Frappe lointaine de': 'A long-range effort from',
    'qui passe loin du cadre.': 'flies well wide.',
    'Tir dans un angle fermé de': 'A tight-angle shot from',
    'capté tranquillement par le gardien.': 'comfortably held by the keeper.',
    'Bel arrêt du gardien sur cette frappe de': 'A fine save by the keeper from',
    'dévisse légèrement son tir.': 'scuffs his shot slightly.',
    'La défense se jette et contre la frappe de': 'The defense throws itself in and blocks the shot from',

    // ── PASSE 8 : écran CAF ──────────────────────────────────────────────
    "Votre club n'est pas qualifié cette saison — terminez": "Your club isn't qualified this season — finish",
    'Top 2': 'Top 2',
    'de votre championnat pour participer.': 'of your league to take part.',
    'Votre club est éliminé': 'Your club has been eliminated',
    'Sorti en': 'Eliminated in the',
    'Phase de groupes': 'Group Stage',
    'Demi-finale': 'Semi-final',
    'vous pouvez suivre la suite de la compétition en spectateur.': 'you can follow the rest of the competition as a spectator.',
    "Champion d'Afrique": 'Champion of Africa',
    'GROUPE': 'GROUP',
    'Votre groupe': 'Your Group',
    'Club': 'Club',
    'V': 'W',
    'N': 'D',
    'D': 'L',
    'Pts': 'Pts',
    'Quarts de finale': 'Quarter-finals',
    'Aller': 'Leg 1',
    'Retour': 'Leg 2',
    'Finale': 'Final',

    // ── PASSE 9 : Classements + causeries de mi-temps ────────────────────
    'j': 'gp',
    'Rester calme': 'Stay Calm',
    "On ne change rien, on continue.": "No changes, we carry on.",
    'Encourager': 'Encourage',
    "Vous leur dites votre confiance.": "You tell them you believe in them.",
    'Secouer': 'Shake Them Up',
    "Le ton monte dans le vestiaire.": "Voices are raised in the dressing room.",
    'Exiger le bloc': 'Demand Discipline',
    "Consignes serrées, on verrouille.": "Tight instructions, lock it down.",
    "Vous menez à la pause. Le vestiaire est chaud.": "You're leading at the break. The dressing room is buzzing.",
    "Vous êtes menés. Onze paires d'yeux vous regardent.": "You're trailing. Eleven pairs of eyes are on you.",
    "Tout reste à faire. Le match se joue maintenant.": "Everything's still to play for. The match is decided now."
};
