// ═══════════════════════════════════════════════════════════════════════════
// TRANSLATION — ENGLISH
// Grouped under window.I18N_EN, loaded BEFORE app.js (see index.html), which
// then assembles the three language files into the I18N registry.
// Any key missing here falls back to French (see lang-fr.js / t() in app.js).
// ═══════════════════════════════════════════════════════════════════════════
window.I18N_EN = {
    'app.subtitle': 'Manager',
    'nav.dashboard': 'Dashboard',
    'nav.squad': 'Squad',
    'nav.tactics': 'Tactics',
    'nav.market': 'Transfers',
    'nav.staff': 'Staff',
    'nav.standings': 'Standings',
    'nav.awards': 'Awards',
    'nav.shop': 'Shop',
    'nav.campus': 'Campus',
    'nav.home_mobile': 'Home',
    'nav.more': 'More',
    'nav.profile': 'Profile',
    'nav.reset': 'Reset',
    'screen.tactics': 'Tactics Office',
    'screen.standings': 'Standings',
    'screen.squad': 'Pro Squad',
    'screen.squad_sub': 'Your players currently under contract.',

    // ── PASSE 1 : DONNÉES DE JEU ─────────────────────────────────────────
    // Staff
    'Entraîneur Adjoint': 'Assistant Coach',
    'Bonus Tactique': 'Tactical Bonus',
    'Kiné Chef': 'Head Physio',
    'Récupération': 'Recovery',
    'Recruteur Chef': 'Head Scout',
    'Précision scouting': 'Scouting Accuracy',
    'Médecin du Sport': 'Sports Doctor',
    'Risque blessure': 'Injury Risk',
    'Manager des Jeunes': 'Youth Manager',
    'Progression académie': 'Academy Progress',

    // Tenues du manager
    'Costume Marine, cravate': 'Navy Suit, Tie',
    'Costume Noir, cravate': 'Black Suit, Tie',
    'Gris moderne, col ouvert': 'Modern Grey, Open Collar',
    'Bordeaux élégant, cravate': 'Elegant Maroon, Tie',
    'Vert olive, décontracté': 'Olive Green, Casual',
    'Ivoire, cravate dorée': 'Ivory, Gold Tie',
    'Sable, col mao': 'Sand, Mandarin Collar',
    'Bleu nuit, pochette rouge': 'Midnight Blue, Red Pocket Square',
    'Anthracite, boutons dorés': 'Charcoal, Gold Buttons',
    'Prestige, revers ivoire': 'Prestige, Ivory Lapel',

    // Boutique de crédits (confort/cosmétique)
    'Relancer les objectifs': 'Reroll Objectives',
    "Tire trois nouveaux objectifs hebdomadaires.": "Draws three new weekly objectives.",
    'Révéler un joueur': 'Reveal a Player',
    "Dévoile les statistiques d'un joueur non supervisé du marché.": "Reveals the stats of an unscouted market player.",
    'Tenue Ivoire': 'Ivory Suit',
    "Costume ivoire, cravate dorée.": "Ivory suit, gold tie.",
    'Tenue Sable': 'Sand Suit',
    "Costume sable, col mao.": "Sand suit, mandarin collar.",
    'Tenue Bleu nuit': 'Midnight Blue Suit',
    "Bleu nuit, pochette rouge.": "Midnight blue, red pocket square.",
    'Tenue Or': 'Gold Suit',
    "Costume anthracite, boutons dorés.": "Charcoal suit, gold buttons.",
    'Portée': 'Worn',
    'Porter': 'Wear',

    // Objectifs hebdomadaires
    'Gagner 2 matchs': 'Win 2 matches',
    'Marquer 5 buts': 'Score 5 goals',
    'Garder 1 cage inviolée': 'Keep 1 clean sheet',
    'Gagner 3 points de stat': 'Gain 3 stat points',
    'Rester 3 matchs invaincu': 'Go unbeaten in 3 matches',
    'Un joueur noté 8.0 ou plus': 'A player rated 8.0 or higher',
    'Objectif rempli': 'Objective completed',
    'crédits': 'credits',

    // Maillots du club
    'Historique': 'Classic',
    'Rayé': 'Striped',
    'Cerclé': 'Hooped',
    'Écharpe': 'Sash',
    'Or & Nuit': 'Gold & Night',
    'Flamme': 'Flame',

    // Stades
    'Terre Battue': 'Dusty Pitch',
    "Le terrain d'origine du club — poussiéreux mais chaleureux.": "The club's original ground — dusty but full of heart.",
    'Tribune Populaire': 'Popular Stand',
    "Des tribunes qui se remplissent, une ambiance qui monte.": "Stands filling up, atmosphere rising.",
    'Arène Moderne': 'Modern Arena',
    "Béton et acier — un stade aux normes continentales.": "Concrete and steel — a stadium built to continental standards.",
    'Nocturne': 'Night Match',
    "Sous les projecteurs — l'ambiance électrique des matchs en soirée.": "Under the floodlights — the electric feel of evening matches.",
    'Nocturne Doré': 'Golden Night',
    "La même nuit électrique, habillée d'or — exclusif.": "The same electric night, dressed in gold — exclusive.",
    'Arène Continentale': 'Continental Arena',
    "Le décor des grands soirs de CAF — bleu et lumière.": "The backdrop of big CAF nights — blue and light.",
    'Jour de Finale': 'Final Day',
    "Feux d'artifice et confettis — le stade d'un soir de sacre.": "Fireworks and confetti — the stadium on a night of glory.",

    // Célébrations de but
    'Classique': 'Classic',
    'Sprint au coin': 'Corner Sprint',
    'Glissade': 'Knee Slide',
    'Virage en fusion': 'Stand on Fire',
    "Feu d'artifice": 'Fireworks',
    'Statut de légende': 'Legend Status',
    'Nuit continentale': 'Continental Night',
    'Roue de la Fortune': 'Wheel of Fortune',
    'Tour gratuit du jour': "Today's Free Spin",

    // Badges de profil
    'Aucun': 'None',
    'Sur le banc': 'On the Bench',
    'Tacticien': 'Tactician',
    'Bâtisseur': 'Builder',
    'Gagneur': 'Winner',
    'Légende': 'Legend',
    'Icône continentale': 'Continental Icon',

    // Campus
    'Tribunes agrandies': 'Expanded Stands',
    "Plus de places disponibles à domicile — hausse directe du plafond de billetterie.": "More seats at home — a direct boost to your ticketing cap.",
    'Boutique du Club': 'Club Store',
    "Maillots et produits dérivés — un revenu fixe supplémentaire à chaque match.": "Shirts and merchandise — extra fixed income every match.",
    'Espace VIP': 'VIP Lounge',
    "Loges premium pour sponsors et invités — revenu de prestige à chaque match.": "Premium boxes for sponsors and guests — prestige income every match.",
    'Chaudron & Ambiance': 'Cauldron & Atmosphere',
    "Un stade qui vibre attire plus de monde — billetterie additionnelle à domicile.": "A buzzing stadium draws bigger crowds — extra home ticketing.",
    'Écran Géant': 'Giant Screen',
    "Purement visuel — l'ambiance du jour de match, sans effet sur les recettes.": "Purely visual — matchday atmosphere, no effect on revenue.",

    // Trophées de fin de saison
    "Ballon d'Or Africain": "African Ballon d'Or",
    "Le meilleur joueur du continent, tous postes confondus.": "The continent's best player, across all positions.",
    "Soulier d'Or Africain": "African Golden Boot",
    "Le plus grand buteur des 10 championnats.": "The top scorer across all 10 leagues.",
    "Meilleur Passeur Africain": "African Playmaker of the Year",
    "Le maître à jouer de la saison.": "The season's midfield maestro.",
    "Gant d'Or Africain": "African Golden Glove",
    "Le gardien le plus infranchissable.": "The most impenetrable goalkeeper.",
    "Meilleur Espoir Africain": "African Young Player of the Year",
    "Le meilleur joueur de 21 ans ou moins.": "The best player aged 21 or under.",
    "Meilleur buteur du championnat": "League Top Scorer",
    "Le canonnier de votre championnat.": "The sharpshooter of your league.",
    'Non attribué cette saison': 'Not awarded this season',
    'm. joués': 'apps',
    'passes déc.': 'assists',
    'buts': 'goals',
    'passes': 'assists',
    'Prime sponsors': 'Sponsor bonus',
    'Prime versée à': 'Bonus paid to',

    // ── PASSE 2 : BOUTIQUE + CAMPUS ──────────────────────────────────────
    'Poignée de crédits': 'Handful of Credits',
    'Sac de crédits': 'Bag of Credits',
    'Coffre de crédits': 'Chest of Credits',
    'Édition Manager': 'Manager Edition',
    "Retire les publicités imposées, offre 1000 crédits, la tenue Or exclusive et un second emplacement de carrière.": "Removes forced ads, grants 1000 credits, the exclusive Gold suit and a second career slot.",
    "Débloque la piste Prestige du pass en cours : cosmétiques exclusifs et crédits à chaque palier.": "Unlocks the Prestige track of the current pass: exclusive cosmetics and credits at every tier.",
    'Offre de bienvenue': 'Welcome Offer',
    "1200 crédits, 150 gemmes, la tenue Ivoire et un Pack Découverte (1 joueur confirmé) offerts. Réservée à votre première saison.": "1200 credits, 150 gems, the Ivory suit and a free Discovery Pack (1 confirmed player). First-season only.",
    'Abonnement VIP': 'VIP Subscription',
    "80 crédits chaque jour, 60 gemmes à chaque renouvellement, publicités imposées retirées, badge VIP. Reconduction automatique chaque mois à 2,49 € jusqu'à résiliation — résiliable à tout moment depuis le Play Store.": "80 credits every day, 60 gems on every renewal, forced ads removed, VIP badge. Auto-renews monthly at €2.49 until cancelled — cancel anytime from the Play Store.",
    'Sachet de gemmes': 'Small Gem Pouch',
    'Bourse de gemmes': 'Gem Purse',
    'Coffre de gemmes': 'Gem Chest',
    'Pack Découverte': 'Discovery Pack',
    "1 joueur confirmé (80-85), immédiatement dans l'effectif.": "1 confirmed player (80-85), added to your squad instantly.",
    'Pack Talents': 'Talent Pack',
    "3 joueurs confirmés (80-88) en un seul tirage.": "3 confirmed players (80-88) in one draw.",
    'Pack Génération': 'Generation Pack',
    "6 joueurs confirmés (83-92) — un effectif de stars d'un coup.": "6 confirmed players (83-92) — a squad of stars in one go.",
    '80 crédits': '80 credits',
    '220 crédits': '220 credits',
    '20 gemmes': '20 gems',
    '50 gemmes': '50 gems',
    'Révélation gratuite': 'Free Reveal',
    'Pack Découverte offert': 'Free Discovery Pack',
    'Jackpot — 180 gemmes': 'Jackpot — 180 gems',
    'Populaire': 'Popular',
    'Meilleure valeur': 'Best Value',
    'Une fois': 'One-time',
    'Restaurer': 'Restore',
    'Actif': 'Active',
    'Tourner': 'Spin',
    'gemmes': 'gems',

    // ── PASSE 3 : ÉCRANS DE JEU (débuts) ─────────────────────────────────
    'Exige un transfert': 'Demands a transfer',
    'Transfert': 'Transfer',
    'Réclame du temps de jeu': 'Wants more playing time',
    'Frustré': 'Frustrated',
    'Refuser': 'Decline',
    'Récupérer': 'Claim',
    'Prêter': 'Loan',
    'Fermer': 'Close',
    'Accepter': 'Accept',
    'Valider': 'Confirm',
    'Tout auto': 'Auto-fill',
    'Reprendre le match': 'Resume Match',
    'Rencontrer': 'Meet',
    'Mon club': 'My Club',
    'Licencier': 'Dismiss',
    'Ignorer': 'Dismiss',
    'Décliner': 'Decline',
    'Compositions': 'Line-ups',
    'Annuler': 'Cancel',
    'Afrique': 'Africa',

    // ── PASSE 3 (suite) : Mercato, Académie, Staff ───────────────────────
    'Tous postes': 'All positions',
    'Tous prix': 'All prices',
    'Tout niveau': 'All ratings',
    'Rafraîchir les agents libres': 'Refresh free agents',
    'Infrastructures': 'Facilities',
    'Niv. Max Atteint': 'Max Level Reached',
    'Améliorer': 'Upgrade',
    'Débutant': 'Rookie',
    'Confirmé': 'Seasoned',
    'Expérimenté': 'Experienced',
    'Réputé': 'Renowned',
    'Élite': 'Elite',
    'ans': 'y/o',

    // ── PASSE 4 : NOTIFICATIONS, BOÎTE DE RÉCEPTION, INTERVIEWS ──────────
    'Aucun message': 'No messages',
    'Offre reçue': 'Offer received',
    'Recrutement': 'Signing',
    'Demande de prêt': 'Loan request',
    'Proposition': 'Offer',
    'Alerte': 'Alert',
    'Contrat': 'Contract',
    'Vestiaire': 'Dressing Room',
    'Palier': 'Tier',
    'Distinction': 'Award',
    'Objectif': 'Objective',
    'Quotidien': 'Daily',
    'Info': 'News',
    'Bonus': 'Bonus',
    'Une réaction ?': 'Any reaction?',
    'Le défendre publiquement': 'Defend him publicly',
    'Prendre ses distances': 'Distance yourself',
    'Ne pas réagir': "Don't react",
    'Le féliciter publiquement': 'Praise him publicly',
    'Recentrer sur le collectif': 'Refocus on the team',
    'Rester factuel': 'Stay factual',

    // ── PASSE 4 (suite) : COMMENTAIRES DE MATCH EN DIRECT ────────────────
    "L'arbitre siffle le coup d'envoi. C'est parti !": "The referee blows the whistle. Kick-off!",
    "Mi-temps. Les équipes rentrent aux vestiaires.": "Half-time. The teams head to the dressing rooms.",
    "Fin de la première période de prolongation.": "End of the first period of extra time.",
    "Fin du temps réglementaire.": "End of regulation time.",
    "Coup de sifflet final !": "Full time!",
    "PENALTY sifflé pour": "PENALTY awarded to",
    "place le ballon sur le point.": "places the ball on the spot.",
    "Corner pour": "Corner for",
    "Coup franc dangereux pour": "Dangerous free kick for",
    "se charge du ballon.": "steps up to take it.",
    "EXPULSION !": "SENT OFF!",
    "voit son 2e carton jaune !": "picks up a second yellow card!",
    "Faute tactique. Carton jaune pour": "Tactical foul. Yellow card for",
    "CARTON ROUGE DIRECT !": "STRAIGHT RED CARD!",
    "Faute grossière de": "A reckless foul from",
    "BLESSURE !": "INJURY!",
    "est touché": "is down injured",
    "Son énergie s'effondre, remplacez-le vite !": "His energy is collapsing, sub him off quickly!",
    "Changement :": "Substitution:",
    "remplace": "replaces",
    "sorti sur blessure.": "who went off injured.",
    "Coup dur pour l'adversaire :": "Tough break for the opposition:",
    "sort sur civière et l'équipe n'a plus de remplaçant !": "is stretchered off and the team has no substitutes left!",
    "Action fulgurante de": "A lightning move from",
    "La défense de": "The defense of",
    "repousse le danger.": "clears the danger.",

    // ── PASSE 6 : commentaires de match (suite) ───────────────────────────
    "Toujours rien pour départager les deux clubs — on joue la prolongation (2 × 15 min).": "Still nothing to separate the two sides — on to extra time (2 × 15 min).",
    "Prolongation ! Un 6e remplacement vous est accordé.": "Extra time! You're granted a 6th substitution.",
    "minute(s) de temps additionnel.": "minute(s) of added time.",
    "Séance de tirs au but :": "Penalty shootout:",
    "se qualifie !": "goes through!",
    "Changement tactique pour l'adversaire.": "Tactical change for the opposition.",

    // ── PASSE 7 : commentaires de but ────────────────────────────────────
    'BUT !': 'GOAL!',
    'sert': 'sets up',
    'qui conclut en beauté !': 'who finishes in style!',
    'Quelle passe de': 'What a pass from',
    'ne pouvait pas rater !': 'couldn\'t miss that!',
    'Superbe centre de': 'A superb cross from',
    'pour': 'for',
    'BUT SUR PENALTY !': 'GOAL FROM THE SPOT!',
    'transforme avec sang-froid !': 'converts ice-cold!',
    'COUP FRANC DIRECT !': 'DIRECT FREE KICK!',
    'enroule par-dessus le mur !': 'curls it over the wall!',
    'BUT EXCEPTIONNEL !': 'STUNNING GOAL!',
    'Frappe de': 'A strike from',
    'à': 'from',
    'mètres': 'meters out',
    'place parfaitement son tir': 'places his shot perfectly',
    'à bout portant': 'from point-blank range',
    'INCROYABLE RATÉ !': 'UNBELIEVABLE MISS!',
    'était seul face au but !': 'was clean through on goal!',
    'ARRÊT MIRACULEUX !': 'MIRACLE SAVE!',
    'Le gardien sauve son équipe face à': 'The keeper bails his team out against',
    'Frappe lointaine de': 'A long-range effort from',
    'qui passe loin du cadre.': 'flies well wide.',
    'Tir dans un angle fermé de': 'A tight-angle shot from',
    'capté tranquillement par le gardien.': 'comfortably held by the keeper.',
    'Bel arrêt du gardien sur cette frappe de': 'A fine save by the keeper from',
    'dévisse légèrement son tir.': 'scuffs his shot slightly.',
    'La défense se jette et contre la frappe de': 'The defense throws itself in and blocks the shot from',

    // ── PASSE 8 : écran CAF ──────────────────────────────────────────────
    "Votre club n'est pas qualifié cette saison — terminez": "Your club isn't qualified this season — finish",
    'Top 2': 'Top 2',
    'de votre championnat pour participer.': 'of your league to take part.',
    'Votre club est éliminé': 'Your club has been eliminated',
    'Sorti en': 'Eliminated in the',
    'Phase de groupes': 'Group Stage',
    'Demi-finale': 'Semi-final',
    'vous pouvez suivre la suite de la compétition en spectateur.': 'you can follow the rest of the competition as a spectator.',
    "Champion d'Afrique": 'Champion of Africa',
    'GROUPE': 'GROUP',
    'Votre groupe': 'Your Group',
    'Club': 'Club',
    'V': 'W',
    'N': 'D',
    'D': 'L',
    'Pts': 'Pts',
    'Quarts de finale': 'Quarter-finals',
    'Aller': 'Leg 1',
    'Retour': 'Leg 2',
    'Finale': 'Final',

    // ── PASSE 9 : Classements + causeries de mi-temps ────────────────────
    'j': 'gp',
    'Rester calme': 'Stay Calm',
    "On ne change rien, on continue.": "No changes, we carry on.",
    'Encourager': 'Encourage',
    "Vous leur dites votre confiance.": "You tell them you believe in them.",
    'Secouer': 'Shake Them Up',
    "Le ton monte dans le vestiaire.": "Voices are raised in the dressing room.",
    'Exiger le bloc': 'Demand Discipline',
    "Consignes serrées, on verrouille.": "Tight instructions, lock it down.",
    "Vous menez à la pause. Le vestiaire est chaud.": "You're leading at the break. The dressing room is buzzing.",
    "Vous êtes menés. Onze paires d'yeux vous regardent.": "You're trailing. Eleven pairs of eyes are on you.",
    "Tout reste à faire. Le match se joue maintenant.": "Everything's still to play for. The match is decided now.",

    // ── PASSE 9 (suite) : consignes tactiques ────────────────────────────
    "Couloir d'attaque": 'Attacking Channel',
    'Par où le jeu sort': 'Where play builds from',
    'Mixte': 'Mixed',
    'Axe': 'Through the Middle',
    'Deux ailes': 'Both Flanks',
    'Droite': 'Right',
    'Gauche': 'Left',
    'Pressing': 'Pressing',
    'Où on va chercher le ballon': 'Where you win the ball back',
    'Sa surface': 'Their Box',
    'Sa moitié': 'Their Half',
    'Tout terrain': 'Full Pitch',
    'Ligne défensive': 'Defensive Line',
    'La hauteur du bloc': 'How high the block sits',
    'Basse': 'Low',
    'Normale': 'Normal',
    'Haute': 'High',
    'Mentalité': 'Mentality',
    'Défensive': 'Defensive',
    'Équilibrée': 'Balanced',
    'Offensive': 'Offensive',
    'Style de jeu': 'Playing Style',
    'Possession': 'Possession',
    'Direct': 'Direct',
    'Contre': 'Counter',
    'Consignes en direct': 'Live Instructions',
    "Chaque changement s'applique immédiatement, sans arrêter le jeu.": "Every change applies instantly, without stopping play.",
    'Formation': 'Formation',

    // ── Écran Paramètres ──────────────────────────────────────────────────
    'nav.settings': 'Settings',
    'Langue': 'Language',
    'Apparence': 'Appearance',
    'Sombre': 'Dark',
    'Clair': 'Light',
    'Le mode clair est encore en cours de finition sur certains écrans.': 'Light mode is still being polished on some screens.',
    'Ambiance sonore': 'Sound',
    'Revoir le tutoriel': 'Replay the Tutorial',
    'Revoir le tutoriel de la boutique': 'Replay the Shop Tutorial',

    // ── Négociations de transfert et contrats ────────────────────────────
    'Renouvellement de contrat': 'Contract Renewal',
    'OVR': 'OVR',
    'Salaire actuel :': 'Current wage:',
    'mois': 'month',
    'Nouveau salaire demandé :': 'Requested new wage:',
    'Durée :': 'Length:',
    'saisons': 'seasons',
    'Contrat de': 'Contract for',
    'renouvelé (2 saisons) !': 'renewed (2 seasons)!',
    'Prolonger': 'Extend',
    "Effectif complet (30 joueurs maximum).": "Squad full (30 players maximum).",
    'ne peut pas vendre': "can't sell",
    "il n'est chez eux qu'en prêt, il ne leur appartient pas.": "he's only on loan there, they don't own him.",
    'refuse de négocier.': 'refuses to negotiate.',
    'Leur effectif est déjà trop court': 'Their squad is already too thin',
    'joueurs': 'players',
    'pour se séparer de qui que ce soit.': 'to let anyone go.',
    'refuse net.': 'flatly refuses.',
    "est un pilier du club : il n'est pas à vendre, quel que soit le montant.": "is a key player: not for sale at any price.",
    'réclame': 'is asking',
    'Vos fonds :': 'Your funds:',
    'Il vous manque': "You're short by",
    'accepte de négocier': 'agrees to negotiate',
    'POT': 'POT',
    'Indemnité de transfert :': 'Transfer fee:',
    'Salaire réclamé :': 'Requested wage:',
    'Le club a besoin de liquidités : le prix est en dessous de sa valeur.': 'The club needs cash: the price is below market value.',
    "C'est un titulaire chez eux, d'où la majoration.": "He's a starter there, hence the markup.",
    'Fonds insuffisants.': 'Insufficient funds.',
    "Ce joueur n'est plus disponible.": 'This player is no longer available.',
    'rejoint': 'joins',
    'Signer': 'Sign',

    // ── Commentaires additionnels + demande de prêt ──────────────────────
    'CHANGEMENT TACTIQUE :': 'TACTICAL CHANGE:',
    'entre à la place de': 'comes on for',
    'Le groupe répond présent.': 'The squad responds well.',
    'Le message passe mal, les têtes se baissent.': "The message doesn't land, heads drop.",
    'Le groupe écoute sans broncher.': 'The squad listens without flinching.',
    'Causerie': 'Team Talk',
    'Consigne du banc': 'Touchline Instruction',
    'Maximum 4 joueurs empruntés simultanément.': 'Maximum 4 players on loan at once.',
    'est déjà en prêt à': 'is already on loan at',
    'il ne peut pas être re-prêté.': "he can't be loaned out again.",
    'refuse :': 'refuses:',
    'leur effectif': 'their squad',
    "est trop court pour se priver de quelqu'un.": "is too thin to let anyone go.",
    'refuse.': 'refuses.',
    'est titulaire chez eux': 'is a starter there',
    'e de la hiérarchie': 'th in the pecking order',
    "On ne prête pas un homme dont on a besoin le week-end.": "You don't loan out a player you need at the weekend.",
    'décline poliment.': 'politely declines.',
    'À OVR': 'At OVR',
    'vise plus haut que': 'is aiming higher than',
    'force': 'strength',
    "Renforcez d'abord la stature du club.": "Build up the club's stature first.",
    'Indemnité de prêt réclamée :': 'Loan fee requested:',
    'Vos fonds ne suffisent pas.': "Your funds aren't enough.",
    'accepte de vous prêter': 'agrees to loan you',
    'pour une saison.': 'for a season.',
    'Indemnité de prêt :': 'Loan fee:',
    'Salaire à votre charge :': 'Wage you cover:',
    'Il repartira automatiquement chez lui en fin de saison. Vous ne pourrez ni le vendre, ni le re-prêter.': "He'll automatically return home at season's end. You can't sell him or loan him out again.",

    // ── Conférences de presse (réponses courtes + citations) ────────────
    'Un pas à la fois': 'One step at a time',
    'On vise le trophée': "We're aiming for the trophy",
    'Féliciter les joueurs': 'Praise the players',
    'Relativiser': 'Keep perspective',
    'Reconnaître la déception': 'Admit the disappointment',
    "Blâmer l'arbitrage": 'Blame the officiating',
    'Regarder devant': 'Look ahead',
    'Revendiquer le travail': 'Claim credit for the work',
    'Rester humble': 'Stay humble',
    'Rassurer le groupe': 'Reassure the group',
    'Se remettre en cause': 'Question myself',
    'Hausser le ton': 'Raise the tone',
    'Ne rien changer': 'Change nothing',
    'Se projeter sur le titre': 'Look ahead to the title',
    'Prévenir un relâchement': 'Warn against complacency',
    'Journée après journée': 'Matchday by matchday',
    'Assumer le costume': 'Own the role',
    'Rejeter la pression': 'Dismiss the pressure',
    'Dédramatiser': 'Play it down',
    "Sonner l'alarme": 'Sound the alarm',
    'Rassurer la direction': 'Reassure the board',
    'Demander du temps': 'Ask for time',
    'Défier les critiques': 'Defy the critics',
    'Ne pas commenter': 'No comment',
    'Protéger le groupe': 'Protect the group',
    'Assumer seul': 'Take sole responsibility',
    'Pointer les manques': 'Point out the shortcomings',
    'Rester prudent': 'Stay cautious',
    "Assumer l'ambition": 'Own the ambition',
    'Créditer le groupe': 'Credit the group',
    "Les points d'abord": 'Points come first',
    'Reconnaître les limites': 'Acknowledge the limits',
    'Saluer le mental': 'Salute the mentality',
    'Féliciter la défense': 'Praise the defense',
    "Réclamer plus d'ambition": 'Demand more ambition',
    'Un point pris': 'A point gained',
    'Un point de trop perdu': 'A point too many dropped',
    'Rester neutre': 'Stay neutral',
    'Rester vague': 'Stay vague',
    'Annoncer une ambition': 'Announce an ambition',
    'Prôner la prudence': 'Advocate caution',
    "S'en réjouir ouvertement": 'Openly celebrate it',
    'Match après match': 'Match by match',
    'Viser plus haut': 'Aim higher',
    'Rester lucide': 'Stay level-headed',
    'On savoure ce soir, on repense au continent demain.': 'We enjoy tonight, we think continent tomorrow.',
    'On ne participe pas pour faire de la figuration. On y va pour le gagner.': "We're not here to make up the numbers. We're here to win it.",
    'Ce sont eux qui ont fait le travail sur le terrain, pas moi.': 'They did the work on the pitch, not me.',
    'Le championnat reste notre priorité. On tourne la page vite.': 'The league remains our priority. We turn the page quickly.',
    "C'est une désillusion. On visait plus loin, il faut le dire.": "It's a disappointment. We aimed further, let's be honest.",
    "Certaines décisions ont pesé lourd ce soir. Je ne suis pas le seul à l'avoir vu.": "Some decisions weighed heavily tonight. I'm not the only one who noticed.",
    'Les chiffres, on les comptera à la fin. Pas avant.': "We'll count the numbers at the end. Not before.",
    'Ce club a changé de visage depuis mon arrivée. Je le dis sans fausse modestie.': 'This club has changed face since I arrived. I say it without false modesty.',
    "Je ne suis qu'un maillon. Le club était là avant moi, il sera là après.": "I'm just one link. The club was here before me, it'll be here after.",
    "On va s'en sortir ensemble. Douter maintenant serait la pire erreur.": "We'll get through this together. Doubting now would be the worst mistake.",
    "Le premier responsable d'une série comme celle-là, c'est le coach. Je regarde ce que je peux changer.": "The person most responsible for a run like this is the coach. I'm looking at what I can change.",
    "Il y a un manque d'exigence individuelle. Ça doit changer, et vite.": "There's a lack of individual demands. That has to change, and fast.",
    "On garde les pieds sur terre et la même méthode. C'est elle qui paie.": "We keep our feet on the ground and the same method. It's what's paying off.",
    "À ce rythme, il n'y a aucune raison de se cacher sur nos ambitions.": "At this rate, there's no reason to hide our ambitions.",
    "Le vrai danger maintenant, c'est de croire qu'on a déjà gagné quelque chose.": "The real danger now is thinking we've already won something.",
    'On ne regarde pas le classement, seulement le prochain adversaire.': "We're not looking at the table, only the next opponent.",
    'On veut ce titre. Autant le dire clairement plutôt que de jouer la fausse humilité.': 'We want this title. Better to say it clearly than play false humility.',
    "La pression, c'est pour ceux qui n'ont rien à perdre. Nous, on joue libérés.": 'Pressure is for those with nothing to lose. We play free.',
    "On a les moyens de s'en sortir. Il faut juste rester soudés.": 'We have what it takes to get through this. We just need to stay united.',
    "La situation est grave. Ceux qui ne le comprennent pas n'ont rien à faire ici.": "The situation is serious. Those who don't understand that have no place here.",
    'Je prends mes responsabilités devant le club. On va se maintenir.': 'I take responsibility before the club. We will stay up.',
    'Un projet se juge sur une saison, pas sur trois journées.': 'A project is judged over a season, not three matchdays.',
    'Je fais mon travail. Ceux qui doutent jugeront au classement.': 'I do my job. Those who doubt will judge by the table.',
    'Je ne parle que de football.': 'I only talk about football.',
    "Personne ne lâche. Ces joueurs se battent, je réponds d'eux.": 'Nobody gives up. These players fight, I vouch for them.',
    "L'équipe a fait le travail. Le choix tactique était le mien, l'erreur aussi.": 'The team did the work. The tactical choice was mine, and so was the mistake.',
    "Certains n'ont pas le niveau exigé ici. Ils le savent.": "Some don't have the level required here. They know it.",
    'Un match ne fait pas une saison. On regarde le suivant.': "One match doesn't make a season. We look at the next one.",
    "On joue pour gagner, et de la meilleure des manières. Pourquoi s'en cacher ?": 'We play to win, and in the best possible way. Why hide it?',
    'Ce sont eux sur le terrain. Tout leur revient.': "It's them out on the pitch. It's all down to them.",
    'Trois points restent trois points, quelle que soit la manière.': 'Three points are three points, no matter how you get them.',
    "On sait qu'il y a du travail. Cette victoire ne doit pas masquer ça.": "We know there's work to do. This win shouldn't hide that.",
    "Ce groupe ne lâche jamais. C'est ce qui a fait la différence.": "This group never gives up. That's what made the difference.",
    "C'est un travail collectif, du gardien jusqu'aux attaquants qui défendent en premier.": "It's a collective effort, from the keeper to the forwards defending first.",
    "Bien défendre, c'est un point de départ. Il faut aussi être dangereux devant.": 'Defending well is a starting point. We also need to be dangerous up front.',
    'On a fait le nécessaire. Rien de plus à ajouter.': 'We did what was needed. Nothing more to add.',
    'Face à cet adversaire, ce point est plutôt bon à prendre.': 'Against this opponent, this point is a good one to take.',
    "On avait les moyens de gagner ce soir. C'est deux points de perdus, pas un de pris.": "We had what it took to win tonight. That's two points dropped, not one gained.",
    'Un résultat logique au vu de la physionomie du match.': 'A logical result given how the match unfolded.',
    "On construit match après match, sans se fixer de chiffre à l'avance.": 'We build match by match, without setting a number in advance.',
    'Ce club a les moyens de viser le haut du tableau cette saison. Je le dis dès maintenant.': "This club has what it takes to aim for the top of the table this season. I'm saying it now.",
    "Il faut d'abord poser des bases solides. Les ambitions viendront ensuite.": 'We need to lay solid foundations first. The ambitions will come after.',
    'La saison est encore longue. On ne regarde pas trop loin.': "The season is still long. We're not looking too far ahead.",
    "Ce classement, on l'a mérité. Pas de raison de bouder son plaisir.": 'We earned this table position. No reason to hold back our joy.',
    'Cette place doit nous donner faim, pas nous satisfaire.': 'This position should make us hungry, not satisfied.',
    'On avance sans regarder trop loin.': 'We move forward without looking too far ahead.',
    'Ce groupe peut aller chercher davantage.': 'This group can achieve more.',
    "Nos moyens sont ce qu'ils sont. On fait avec.": 'Our resources are what they are. We work with them.',

    // ── Questions de conférence de presse ─────────────────────────────────
    'Qualification continentale face à': 'Continental qualification against',
    "L'Afrique, ce n'est plus un rêve ?": 'Is Africa no longer just a dream?',
    'Élimination continentale contre': 'Continental elimination against',
    'Un échec pour le projet ?': 'A failure for the project?',
    'Un cap symbolique de matchs à la tête du club. Un bilan ?': 'A symbolic number of matches in charge. Any assessment?',
    "Troisième défaite d'affilée. La spirale négative vous inquiète-t-elle ?": 'Third straight defeat. Does the negative spiral worry you?',
    "Cinquième match sans défaite. Cette équipe a-t-elle changé de dimension ?": 'Fifth match unbeaten. Has this team stepped up a level?',
    'À quelques journées de la fin, vous jouez le titre. La pression monte-t-elle ?': "With a few matchdays left, you're in the title race. Is the pressure building?",
    'Le club est empêtré dans la lutte pour le maintien. Le discours a-t-il changé dans le vestiaire ?': "The club is stuck in a relegation battle. Has the message changed in the dressing room?",
    'Votre poste est ouvertement discuté. Un message à la direction ?': 'Your job is openly being questioned. Any message for the board?',
    'Nouveau revers face à': 'Another setback against',
    'Le vestiaire vous échappe-t-il ?': 'Is the dressing room slipping away from you?',
    'Une démonstration face à': 'A statement performance against',
    'Le plus beau match de la saison ?': 'The best match of the season?',
    'Victoire courte mais précieuse contre': 'A narrow but precious win against',
    'La manière compte-t-elle vraiment ?': 'Does the manner of victory really matter?',
    'Une cage inviolée de plus face à': 'Another clean sheet against',
    'Le socle défensif du club ?': "The club's defensive foundation?",
    'Match nul concédé face à': 'A draw conceded against',
    'Un point perdu ou un point pris ?': 'A point dropped or a point gained?',
    'Encore tôt dans la saison. Quels objectifs vous fixez-vous pour cet exercice ?': 'Still early in the season. What targets are you setting for this campaign?',
    'Le club pointe à la': 'The club sits in',
    'ᵉ place. Une saison qui prend une belle tournure ?': ' place. Is the season taking a good turn?',
    'Comment abordez-vous la suite du championnat,': 'How are you approaching the rest of the season, currently',
    'ᵉ au classement ?': ' in the table?',

    // ── Rapport d'avant-match (style adverse) ────────────────────────────
    'Garde le ballon et construit patiemment.': 'Keeps the ball and builds patiently.',
    "Joue vers l'avant dès que possible, beaucoup de ballons longs.": 'Plays forward as soon as possible, lots of long balls.',
    'Laisse le ballon et frappe en transition.': 'Cedes the ball and strikes on the counter.',
    'Bloc bas, presse seulement dans sa surface.': 'Low block, only presses in its own box.',
    'Bloc médian.': 'Mid block.',
    'Presse haut, sur tout le terrain.': 'Presses high, across the whole pitch.',
    "Défense basse — l'espace est devant, pas derrière.": 'Deep defense — the space is in front, not behind.',
    'Ligne médiane.': 'Mid line.',
    'Ligne haute — un ballon dans le dos peut tout casser.': 'High line — a ball in behind can break everything open.',
    'Attaque de partout.': 'Attacks from everywhere.',
    "Cherche l'axe.": 'Looks to go through the middle.',
    'Étire le jeu sur les deux ailes.': 'Stretches play on both wings.',
    'Insiste sur son côté droit.': 'Favors its right side.',
    'Insiste sur son côté gauche.': 'Favors its left side.',
    "Ils attendent la transition : ne laissez pas votre ligne trop haute.": "They wait to break: don't push your line too high.",
    "Ils veulent le ballon : allez le leur prendre haut.": 'They want the ball: go and press them high.',
    "Ils jouent long : reculez la ligne et gagnez les seconds ballons.": 'They play long: drop your line and win the second balls.',

    // ── Paliers de carrière + objectifs du tableau de bord ───────────────
    'Premiers pas': 'First Steps',
    'Le conseil vous fait confiance': 'The board trusts you',
    'Reconnaissance': 'Recognition',
    'La presse commence à vous citer': 'The press starts quoting you',
    'Coach confirmé': 'Established Coach',
    'Un sponsor rejoint le projet': 'A sponsor joins the project',
    "Vos infrastructures montent d'un cran": 'Your facilities move up a level',
    'Monument': 'Monument',
    'Une légende africaine rejoint votre projet': 'An African legend joins your project',
    'Classements': 'Leaderboards',
    'Obtenu': 'Achieved',
    'Remporter le titre': 'Win the Title',
    'Top 3 en championnat': 'Top 3 in the League',
    'Maintien (Top 10)': 'Stay Up (Top 10)',

    // ── Derniers oublis trouvés en vérification finale ───────────────────
    'Achat déjà en cours...': 'Purchase already in progress...',
    'Offre de bienvenue déjà utilisée ou expirée.': 'Welcome offer already used or expired.',
    'Pass de saison déjà actif.': 'Season pass already active.',

    // ── Tableau de bord ───────────────────────────────────────────────────
    'CAF — Finale': 'CAF — Final',
    'CAF — Demi-finale': 'CAF — Semi-final',
    'CAF — Quart de finale': 'CAF — Quarter-final',
    'CAF — Phase de groupes': 'CAF — Group Stage',
    'Championnat': 'League',
    'Aucun match': 'No match',
    'Continental': 'Continental',
    'Fin de saison': 'Season over',
    'Réputation': 'Reputation',
    'Masse sal.': 'Wage Bill',
    'Contrats': 'Contracts',
    'Académie': 'Academy',
    'Projection fin de saison :': 'End-of-season projection:',
    'Masse sal./mois': 'Wage Bill/Month',

    // ── Onglet Tactiques ──────────────────────────────────────────────────
    'Contre-attaque': 'Counter-attack',
    'Jeu direct': 'Direct Play',
    'Joueur': 'Player',
    'Personne de disponible': 'No one available',
    'aucun': 'none',
    'Choisi': 'Chosen',
    'Auto': 'Auto',
    'Penalty': 'Penalty',
    'Coup franc': 'Free Kick',
    'Corner': 'Corner',
    'Capitaine': 'Captain',
    'Meneur de jeu': 'Playmaker',
    "Rôles de l'équipe": 'Team Roles',
    'Qui prend le ballon sur coup arrêté': 'Who takes set pieces',
    'Joueurs': 'Players',

    // ── Onglet Mercato ────────────────────────────────────────────────────
    'Packs de joueurs': 'Player Packs',
    "Des joueurs confirmés (80+) directement dans l'effectif pro — un raccourci vers ce que le mercato permet déjà, en plus rapide.": "Confirmed players (80+) added straight to your pro squad — a shortcut to what the transfer market already allows, just faster.",
    'Poste tiré au sort à chaque joueur : 10% Gardien, 30% Défenseur, 30% Milieu, 30% Attaquant. Note exacte tirée au sort dans la fourchette indiquée sur chaque pack.': 'Position is randomized per player: 10% Goalkeeper, 30% Defender, 30% Midfielder, 30% Forward. Exact rating is randomized within the range shown on each pack.',
    'Demandes de prêt': 'Loan Requests',
    'Offres reçues': 'Offers Received',
    'Offre de': 'Offer from',
    'Superviser': 'Scout',
    'Stature du projet insuffisante': "Project stature insufficient",
    'LIBRE': 'FREE',
    'Agent libre': 'Free Agent',
    'Acheter': 'Buy',
    'Prime à la signature': 'Signing bonus',
    'signature(s) restante(s)': 'signing(s) left',
    "Quota d'agents libres épuisé cette saison": 'Free agent quota used up this season',

    // ── Onglet Staff ──────────────────────────────────────────────────────
    'Salaire': 'Salary',
    'Engager': 'Hire',
    'requis': 'required',
    'rejoint le staff': 'joins the staff',
    'Staff Technique': 'Technical Staff',
    'Améliorez votre encadrement pour obtenir des bonus passifs.': 'Upgrade your staff to get passive bonuses.',
    'Fonds Dispos': 'Available Funds',

    // ── Onglet Académie ───────────────────────────────────────────────────
    'match en réserve': 'reserve match',
    'matchs en réserve': 'reserve matches',
    'Promouvoir': 'Promote',
    "Votre effectif pro est plein (30 joueurs max) !": "Your pro squad is full (30 players max)!",
    '+ Nouvelle Promotion': '+ New Intake',

    // ── Onglet Classement + CAF (compléments) ────────────────────────────
    'La compétition continentale se lance en fin de saison. Terminez dans le': 'The continental competition kicks off at the end of the season. Finish in the',
    'de votre ligue pour y participer.': 'of your league to take part.',
    'Demi-finales': 'Semi-finals',
    'Ligue Elite Africaine': 'African Elite League',
    'Aucun joueur correspondant aux filtres.': 'No player matches the filters.',
    "Aucun match joué pour l'instant": 'No match played yet',
    'Résultats': 'Results',
    'matchs': 'matches',

    // ── Onglet Palmarès ───────────────────────────────────────────────────
    'cr.': 'cr.',
    'Le onze sera désigné après la prochaine journée': 'The team of the week will be announced after the next matchday',
    'Coach de la journée': 'Manager of the Day',
    'Distinctions': 'Awards',
    'Rendez-vous quotidien': 'Daily Check-in',
    'Jour': 'Day',
    'Série de': 'Streak of',
    'jour(s)': 'day(s)',
    'crédits à récupérer': 'credits to claim',
    'Revenez demain pour poursuivre la série': 'Come back tomorrow to keep the streak going',
    'Doubler': 'Double',
    'Pris': 'Claimed',
    'Objectifs de la semaine': "This Week's Objectives",
    'journée(s) restante(s)': 'matchday(s) left',
    'Onze de la journée': 'Team of the Day',
    'Pass de saison': 'Season Pass',
    'pts de carrière': 'career pts',
    'Ouvrir la piste Prestige': 'Unlock the Prestige Track',
    'Piste Prestige active': 'Prestige Track Active',
    'Tenue exclusive': 'Exclusive Suit',
    'Maillot exclusif': 'Exclusive Kit',
    'Gratuit': 'Free',
    'Prestige': 'Prestige',
    'Boutique': 'Shop',

    // ── Onglet Historique ─────────────────────────────────────────────────
    'Le palmarès se remplira à la fin de votre première saison': "Your trophy cabinet will fill up at the end of your first season",
    'Champion': 'Champion',
    'place': 'place',
    'Titre': 'Title',
    'Champion :': 'Champion:',
    'Vainqueur continental :': 'Continental winner:',
    'Meilleur buteur :': 'Top scorer:',
    'Cumuls dès la fin de la 1re saison': 'Totals available from the end of season 1',
    'retraité': 'retired',
    "Aucun joueur n'approche de la fin de carrière": "No player is nearing the end of their career",
    'Buteurs': 'Scorers',
    'Passeurs': 'Assists',
    'Matchs joués': 'Appearances',
    'Histoire du club': 'Club History',
    'Palmarès, records de tous les temps et fins de carrière.': 'Trophy cabinet, all-time records and career endings.',

    // ── Onglet Manager / Paramètres ───────────────────────────────────────
    'Tactique': 'Tactics',
    'Gestion': 'Management',
    'Charisme': 'Charisma',
    'Saison': 'Season',
    'Depuis la saison': 'Since season',
    'Aucun titre': 'No titles',
    'Aucun club dans le CV pour le moment.': 'No club in the CV yet.',
    'Attributs': 'Attributes',
    'Ces notes progressent lentement avec vos résultats, la tenue du vestiaire et vos recrutements — elles ne se réinitialisent jamais.': 'These ratings progress slowly with your results, dressing-room discipline and signings — they never reset.',
    'Paliers de carrière': 'Career Tiers',
    'points': 'points',
    'victoires, titres et podiums': 'wins, titles and podiums',
    'Connecté': 'Connected',
    'Votre score :': 'Your score:',
    'Voir': 'View',
    'Se connecter à Google Play Games': 'Sign in to Google Play Games',
    'Points de carrière': 'Career Points',

    // ── Onglet Formation ──────────────────────────────────────────────────
    'Allégée': 'Light',
    'Préserve les jambes': 'Preserves the legs',
    'Le bon compromis': 'The right balance',
    'Intense': 'Intense',
    'Progresse vite, fatigue et blesse': 'Fast progress, but tires and injures',
    'Bloqué': 'Stuck',
    'Lent': 'Slow',
    'Modéré': 'Moderate',
    'Bon': 'Good',
    'Rapide': 'Fast',
    'blessé': 'injured',
    'Plafond atteint': 'Cap reached',
    '+1 dans': '+1 in',
    'Entraînement': 'Training',
    "Rendement selon l'âge": 'Output by age',

    // ── Onglet Entraîneurs ────────────────────────────────────────────────
    'Vous': 'You',
    'Votre équipe': 'Your Team',
    'Entraîneurs': 'Coaches',
    'Offensif': 'Attacking',
    'Défensif': 'Defensive',
    'Équilibré': 'Balanced',
    'Jeu total': 'Total Football',

    // ── Rattrapage : commentaires/notifications manquants ────────────────
    'Journée sans match, on avance.': 'No match today, moving on.',
    'Journée simulée automatiquement.': 'Matchday simulated automatically.',
    'La saison est terminée !': 'The season is over!',
    'Sans recruteur : estimation approximative': 'Without a scout: rough estimate',

    // ── Modales secondaires (coups de pied arrêtés, fiche équipe) ────────
    'Prêt': 'Loan',
    'Conseillé': 'Recommended',
    'forme': 'form',
    'Aptitude': 'Suitability',
    'Choix automatique': 'Automatic Choice',
    "Aujourd'hui :": 'Today:',
    'Aucun joueur disponible': 'No player available',
    'Le sang-froid sur onze mètres': 'Ice-cold composure from twelve yards',
    'La frappe par-dessus le mur': 'The strike over the wall',
    'Le pied qui trouve la tête': 'The foot that finds the head',
    'Le patron dans le vestiaire': 'The boss of the dressing room',
    'Celui par qui le jeu doit passer': 'The one the play must go through',

    // ── Fiche joueur détaillée ────────────────────────────────────────────
    'Réserve': 'Reserve',
    'Matchs': 'Matches',
    'Né le': 'Born on',
    'Pot.': 'Pot.',
    'Buts': 'Goals',
    'Passes': 'Assists',
    'Statistiques': 'Statistics',
    'Total carrière': 'Career Total',
    'saison': 'season',
    'Historique saison par saison': 'Season-by-Season History',

    // ── Rattrapage final : notifications confirmées manquantes ───────────
    'Achat non abouti.': 'Purchase did not go through.',
    'Attention : aucun gardien dans votre onze de départ !': 'Warning: no goalkeeper in your starting eleven!',
    'Aucun joueur à révéler sur le marché.': 'No player to reveal on the market.',
    'Budget insuffisant !': 'Insufficient budget!',
    'Ce joueur est déjà en prêt.': 'This player is already out on loan.',
    'Ce joueur est emprunté : vous ne pouvez pas le vendre.': "This player is on loan: you can't sell him.",
    'Connectez-vous pour comparer votre carrière à celle des autres managers.': 'Sign in to compare your career with other managers.',
    'Déjà en parfait état.': 'Already in perfect condition.',
    'Fonds insuffisants pour ce transfert.': 'Insufficient funds for this transfer.',
    'Fonds insuffisants pour envoyer un recruteur.': 'Insufficient funds to send a scout.',
    'Les trophées seront décernés à la fin de la saison.': 'Trophies will be awarded at the end of the season.',
    'Membre du staff licencié.': 'Staff member dismissed.',
    'Niveau maximum atteint !': 'Maximum level reached!',
    'Niveau maximum déjà atteint.': 'Maximum level already reached.',
    'Offre déclinée.': 'Offer declined.',
    'Tenue changée.': 'Outfit changed.',
    'Trois nouveaux objectifs tirés.': 'Three new objectives drawn.',
    'Vérification des achats en cours...': 'Checking purchases...',

    // ── Clés manquantes détectées par audit ──────────────────────────────
    'Bon offert': 'Free session',
    'Comprendre la boutique': 'Understand the shop',
    'Conférence de presse': 'Press Conference',
    'Forme': 'Fitness',
    'Kiné': 'Physio',
    'Lui parler': 'Talk to him',
    'Moral': 'Morale',
    'Pas de kiné au club': 'No physio at the club',
    'Presse': 'Press',
    'Prêté par': 'On loan from',
    'Renouveler': 'Renew',
    'Repos': 'Rest',
    'Séance faite': 'Session done',
    'Tireur de corner': 'Corner taker',
    'Tireur de coup franc': 'Free-kick taker',
    'Tireur de penalty': 'Penalty taker',
    'Vendre': 'Sell',
    'séance(s)': 'session(s)',

    // ── Interface statique (index.html) ──────────────────────────────────
    "1. Votre nom d'entraîneur": '1. Your manager name',
    '2. Votre allure': '2. Your look',
    '3. Choisissez une Ligue': '3. Choose a League',
    '4. Choisissez votre Club': '4. Choose your Club',
    'Actualités': 'News',
    'Alchimie du groupe': 'Team Chemistry',
    'B/M': 'G/M',
    'Banc': 'Bench',
    'Boîte de réception': 'Inbox',
    'Budget': 'Budget',
    'Calcul de tous les matchs du continent africain': 'Calculating every match across Africa',
    'Choisissez le club africain que vous allez diriger vers les sommets.': 'Choose the African club you will lead to the top.',
    'Classement': 'Standings',
    'Composition': 'Line-up',
    'Confiance du conseil': 'Board Confidence',
    'Consignes': 'Instructions',
    'Contre-Attaque': 'Counter-Attack',
    'Diff. niveau': 'Rating gap',
    'Discours de motivation': 'Motivational Speech',
    'Défense Absolue': 'Absolute Defense',
    'Forme dom.': 'Home form',
    'Forme ext.': 'Away form',
    'Forme récente': 'Recent Form',
    'Glissez un joueur sur un autre, ou touchez-en deux': 'Drag one player onto another, or tap two',
    'Humeur du vestiaire': 'Dressing Room Mood',
    'Jeu Direct': 'Direct Play',
    'Lancer le match 2D': 'Start the 2D match',
    'Les news apparaissent ici…': 'News will appear here…',
    'Manière de jouer': 'Style of Play',
    'Mercato & Détection': 'Transfers & Scouting',
    'Notes': 'Ratings',
    'Nouveau Contrat': 'New Contract',
    'Objectifs saison': 'Season Objectives',
    'Passer': 'Skip',
    'Points': 'Points',
    'Position': 'Position',
    'Prochain match': 'Next match',
    'Recruteur (500 K€)': 'Scout (€500K)',
    'Remplacements': 'Substitutions',
    'Renforcez votre effectif. Fonds disponibles :': 'Strengthen your squad. Available funds:',
    'Réservistes': 'Reserves',
    'Rôles': 'Roles',
    'Signer le contrat': 'Sign the contract',
    'Simulation en cours...': 'Simulating...',
    'Stats': 'Stats',
    'Style': 'Style',
    'TEMPS FORT': 'HIGHLIGHT',
    'Tenue': 'Outfit',
    'Tireurs &amp; capitaine': 'Takers &amp; captain',
    'Ultra Offensive': 'Ultra Attacking',
    'VS': 'VS',
    'Visage': 'Face',
    'Voir les résultats de la journée': 'View matchday results',
    'XI de départ': 'Starting XI',
    '⚠️ Effacer ma partie et recommencer': '⚠️ Erase my game and start over',
    'Échanger avec…': 'Swap with…',
    'joueur': 'player',

    'Zone de danger': 'Danger Zone',
    'Efface définitivement votre carrière : effectif, palmarès, budget et progression. Cette action est irréversible.': 'Permanently erases your career: squad, trophies, budget and progress. This action cannot be undone.',
    'Effacer ma partie et recommencer': 'Erase my game and start over',

    // ── Fragments d'interface (audit final) ──────────────────────────────
    'Annuler (Reprendre)': 'Cancel (Resume)',
    'Aucun buteur': 'No scorer',
    'Aucun club ne correspond.': 'No club matches.',
    "Aucun de vos joueurs n'a été distingué cette saison. Les primes vont à leurs clubs.": 'None of your players won an award this season. The bonuses go to their clubs.',
    'Aucun joueur ne correspond.': 'No player matches.',
    'Aucune actualité': 'No news',
    'Badges de profil': 'Profile Badges',
    'Bilan de carrière': 'Career Summary',
    'Carrière (CV)': 'Career (CV)',
    'Ce que conseille votre staff': 'What your staff advises',
    'Clubs + Joueurs': 'Clubs + Players',
    'Comment ils jouent': 'How they play',
    "Confort uniquement — rien ici n'améliore vos joueurs.": 'Convenience only — nothing here improves your players.',
    "Consulter les stats d'abord": 'Check the stats first',
    "Coup d'envoi": 'Kick-off',
    'Célébrations de but': 'Goal Celebrations',
    'Design actif :': 'Active design:',
    "Direction l'effectif": 'Off to the squad',
    'Début de saison': 'Start of season',
    'Démarrer la saison suivante': 'Start next season',
    'Effet des philosophies': 'Effect of philosophies',
    'Entretien': 'Upkeep',
    'Entretien individuel': 'One-to-one talk',
    'Garde-robe du manager': 'Manager Wardrobe',
    'Gemmes': 'Gems',
    'Grande Finale': 'Grand Final',
    'Installations': 'Facilities',
    "Jusqu'à minuit": 'Until midnight',
    'Le palmarès individuel se remplira à la fin de votre première saison.': 'Individual honours will appear at the end of your first season.',
    'Les hommes à surveiller': 'Players to watch',
    'Maillots du club': 'Club Kits',
    'Meilleurs Buteurs': 'Top Scorers',
    'Meilleurs Passeurs': 'Top Assists',
    'Mi-temps': 'Half-time',
    'Note': 'Rating',
    'Notes du match': 'Match Ratings',
    'Nouveaux joueurs confirmés': 'New confirmed players',
    'Offre limitée': 'Limited offer',
    'Palier atteint': 'Tier reached',
    'Pas encore de buteur en Ligue Elite Africaine.': 'No scorer yet in the African Elite League.',
    'Pas encore de passeur en Ligue Elite Africaine.': 'No assist yet in the African Elite League.',
    'Porté': 'Worn',
    'Poste': 'Position',
    "Purement financier — aucune installation n'apporte le moindre avantage sportif.": 'Purely financial — no facility grants any sporting advantage.',
    "Purement visuel — aucun stade n'apporte le moindre avantage sportif.": 'Purely visual — no stadium grants any sporting advantage.',
    'Repartent en fin de saison': "Return at season's end",
    'Retour automatique en fin de saison': "Automatic return at season's end",
    'Récupérer les 80 crédits du jour': "Claim today's 80 credits",
    'Stades': 'Stadiums',
    'Tapez un nom, ou choisissez un poste / OVR / âge pour lister des joueurs.': 'Type a name, or pick a position / OVR / age to list players.',
    'Trajectoire': 'Trajectory',
    'Utiliser': 'Use',
    'Vidéos bonus': 'Bonus Videos',
    "Voir l'effectif": 'View squad',
    'Votre club': 'Your club',
    'Votre club termine à la': 'Your club finishes',
    'note moyenne': 'avg rating',
    'possession': 'possession',
    'tirs': 'shots',

    'Active': 'Active',
    'Campus': 'Campus',
    'Clubs': 'Clubs',
    'Défense →': 'Defense →',
    'Effectif': 'Squad',
    'Entre': 'On',
    'Force': 'Strength',
    'Ils ont raccroché': 'They hung up their boots',
    'Notes indisponibles pour ce match.': 'Ratings unavailable for this match.',
    'Notes provisoires : le poids du résultat monte à mesure que le match avance.': 'Provisional ratings: the result weighs more as the match goes on.',
    'Offre Flash': 'Flash Offer',
    'Sort': 'Off',
    'Tous': 'All',
    "d'énergie": 'energy',
    'e place': 'place',
    'en bas': 'bottom',
    'obtenu.': 'obtained.',
    'temps de jeu réel': 'actual playing time',
    '· moyenne': '· average',
    '← Attaque': '← Attack',
    '↩ Rappeler': '↩ Recall',

    // ── PASSE COMPLÉMENTAIRE : chaînes restées en dur ─────────────────────
    // Attributs HTML (placeholder / title) — voir index.html
    'Ex : Didier Kouassi': 'e.g. Didier Kouassi',
    'Rechercher un club ou un joueur': 'Search for a club or a player',
    // Feuille de match / tableau de bord
    'Chargement...': 'Loading...',
    'Domicile': 'Home',
    'Extérieur': 'Away',
    // Paliers de réputation (en-tête)
    'Local': 'Local',
    'National': 'National',
    'Mondial': 'Worldwide',
    // Onglet Composition (libellés des volets)
    'Remplaçants': 'Substitutes',
    'Tribunes': 'Stands',
    // Écran de match en direct
    'En Cours': 'Live',
    // Tutoriel
    'Suivant': 'Next',
    'Terminer': 'Finish',

    // ═══ PASSE INTÉGRALE — chaînes restantes d'app.js ═══════════════════════
    // ── Championnats (listes déroulantes création de partie + classement) ──
    "Liga 1 (Côte d'Ivoire)": "Liga 1 (Ivory Coast)",
    'Boutola Pro (Maroc)': 'Boutola Pro (Morocco)',
    'Premier Division (Afr. Sud)': 'Premier Division (South Africa)',
    'Super League (Égypte)': 'Super League (Egypt)',
    'Liga Pro (Tunisie)': 'Liga Pro (Tunisia)',
    'Liga 1 (Algérie)': 'Liga 1 (Algeria)',
    'Liga 1 (Sénégal)': 'Liga 1 (Senegal)',
    'Liga Pro (Nigéria)': 'Liga Pro (Nigeria)',
    'Elite Division (Cameroun)': 'Elite Division (Cameroon)',
    'Liga Congo (RDC)': 'Liga Congo (DR Congo)',

    // ── Création de partie : difficulté du club choisi ─────────────────────
    'Favori': 'Favourite',
    'Solide': 'Solid',
    'Difficile': 'Tough',

    // ── Postes détaillés ──────────────────────────────────────────────────
    'Gardien de but': 'Goalkeeper',
    'Défenseur central': 'Centre-back',
    'Latéral droit': 'Right-back',
    'Latéral gauche': 'Left-back',
    'Milieu défensif': 'Defensive midfielder',
    'Milieu relayeur': 'Box-to-box midfielder',
    'Ailier droit': 'Right winger',
    'Ailier gauche': 'Left winger',
    'Buteur': 'Striker',

    // ── Attributs et statistiques ─────────────────────────────────────────
    'Arrêts': 'Saves',
    'Tirs cadrés': 'Shots on target',
    'Constance': 'Consistency',
    'Engagement': 'Work rate',
    'Rythme': 'Pace',
    'Régularité': 'Reliability',
    'Sérieux': 'Professionalism',
    'moitié': 'half',
    'Aller / Retour': 'Home / Away',
    'Aucune donnée': 'No data',
    'Aucune donnée pour l&rsquo;instant': 'No data yet',
    'Trophées : calcul impossible': 'Trophies: cannot be computed',
    'Très probable': 'Very likely',
    'Normal': 'Normal',
    'Semaine pleine': 'Full week',
    'Reprise': 'Pre-season',
    'Coach': 'Coach',
    'Histoire': 'History',
    'Bienvenue': 'Welcome',
    'Tout effacer': 'Erase everything',
    'Crédits bonus': 'Bonus credits',
    'Deux monnaies': 'Two currencies',
    'Confort & cosmétique': 'Comfort & cosmetics',
    'Vos objectifs': 'Your objectives',
    'Votre effectif': 'Your squad',
    'Votre onze': 'Your starting XI',
    'Votre progression': 'Your progress',
    'Le bureau tactique': 'The tactics office',
    'Moral du vestiaire': 'Dressing-room morale',
    'La direction observe': 'The board is watching',
    'Le groupe se connaît': 'The squad knows each other',
    'Stabilité dans le groupe': 'Stability in the squad',
    'Débrief d\'après-match': 'Post-match debrief',
    'SOIRÉE CONTINENTAL': 'CONTINENTAL NIGHT',
    'Gala des trophées :': 'Awards gala:',
    'Prime de championnat : +': 'League bonus: +',
    'Temps de jeu :': 'Playing time:',
    'ne vous appartient pas : il est prêté par': 'does not belong to you — on loan from',
    '📺 Yao Baba Sport': '📺 Yao Baba Sport',
    '🤝 Prêter': '🤝 Loan out',
    'Phase de Groupes': 'Group Stage',
    'Quarts de Finale': 'Quarter-finals',

    // ── Réponses aux interviews / vestiaire ───────────────────────────────
    'Promettre du temps de jeu': 'Promise playing time',
    'Recadrer fermement': 'Come down hard',
    'Écouter sans promettre': 'Listen without promising',
    'Fixer un nouveau cap': 'Set a new direction',

    // ── Notifications ─────────────────────────────────────────────────────
    'Abonnement VIP activé : 80 crédits par jour, 60 gemmes, publicités retirées.': 'VIP subscription active: 80 credits a day, 60 gems, forced ads removed.',
    'Abonnement VIP déjà actif.': 'VIP subscription already active.',
    'Achat payé mais non appliqué — réessayez ou contactez le support.': 'Purchase charged but not delivered — try again or contact support.',
    'Aucune vidéo disponible pour le moment. Réessayez plus tard.': 'No video available right now. Try again later.',
    "Ce joueur n'est plus dans vos rangs.": 'This player is no longer in your squad.',
    'Consignes du staff appliquées.': 'Staff instructions applied.',
    'Discours motivant ! +15 moral pour tous les joueurs.': 'Rousing team talk! +15 morale for every player.',
    'Doubler la récompense du jour': "Double today's reward",
    'Effectif trop court pour prêter (15 joueurs minimum).': 'Squad too small to loan out (15 players minimum).',
    'Erreur de chargement :': 'Loading error:',
    'Erreur pendant le match (récupération auto) :': 'Error during the match (auto-recovered):',
    'Impossible : effectif minimum de 14 joueurs.': 'Not possible: 14-player minimum squad.',
    'Impossible de vendre : effectif minimum de 14 joueurs.': 'Cannot sell: 14-player minimum squad.',
    'Incident technique — match arrêté proprement, vous pouvez continuer.': 'Technical issue — match stopped cleanly, you can carry on.',
    'Jeu sauvegardé ! Taille :': 'Game saved! Size:',
    "Journée CAF — Votre club n'est pas qualifié.": 'CAF matchday — your club has not qualified.',
    'La piste Prestige demande le pass de saison.': 'The Prestige track requires the season pass.',
    "Les classements s'ouvriront ici une fois l'app publiée sur Android.": 'Leaderboards will open here once the app is published on Android.',
    'Match reporté — reprenez quand vous êtes prêt.': 'Match postponed — resume when you are ready.',
    'Matchs CAF simulés automatiquement.': 'CAF matches simulated automatically.',
    'Maximum 6 joueurs prêtés simultanément.': 'Maximum 6 players out on loan at once.',
    'Mémoire pleine ! Impossible de sauvegarder.': 'Storage full! Cannot save.',
    'Nouvelle saison démarrée ! Bonne chance !': 'New season under way. Good luck!',
    'Offre Flash du jour': "Today's flash offer",
    'Offre Flash déjà récupérée aujourd\'hui. Revenez demain.': 'Flash offer already claimed today. Come back tomorrow.',
    'Offre de bienvenue activée : crédits, gemmes, tenue Ivoire et Pack Découverte reçus.': 'Welcome offer activated: credits, gems, Ivory suit and Starter Pack received.',
    'Pass de saison activé : la piste Prestige est ouverte.': 'Season pass activated: the Prestige track is open.',
    'Qualifié pour la Ligue Elite Africaine !': 'Qualified for the African Elite League!',
    'Qualifié pour les demi-finales CAF ! +2M€': 'Through to the CAF semi-finals! +€2M',
    'Qualifié pour les quarts CAF ! +1M€': 'Through to the CAF quarter-finals! +€1M',
    'Rien à entretenir — installation non construite.': 'Nothing to maintain — facility not built.',
    'Rôles réattribués automatiquement.': 'Roles reassigned automatically.',
    'Sauvegarde échouée :': 'Save failed:',
    'VIP — +80 crédits du jour.': 'VIP — +80 credits for today.',
    'Vidéo interrompue — aucune récompense.': 'Video interrupted — no reward.',
    'Votre club est en FINALE AFRICAINE ! +3M€': 'Your club is in the AFRICAN FINAL! +€3M',
    'Votre effectif est plein (30 joueurs max) !': 'Your squad is full (30 players max)!',
    'Édition Manager activée : publicités imposées retirées, tenue Or débloquée.': 'Manager Edition activated: forced ads removed, Gold suit unlocked.',
    'Édition Manager déjà active.': 'Manager Edition already active.',
    'Élimination en Demi-finale CAF.': 'Knocked out in the CAF semi-finals.',
    'Élimination en Quarts de finale CAF.': 'Knocked out in the CAF quarter-finals.',
    'Élimination en phase de groupes CAF.': 'Knocked out in the CAF group stage.',
    '⏳ Discours déjà utilisé ce mois-ci.': '⏳ Team talk already used this month.',
    '🚨 Attention !\\n\\nVous allez perdre toute votre progression.\\nVoulez-vous vraiment recommencer à zéro ?': '🚨 Warning!\\n\\nYou are about to lose all your progress.\\nDo you really want to start over?',

    // ── Boutique : lots flash et textes explicatifs ───────────────────────
    'Lot Flash — Découverte': 'Flash Bundle — Starter',
    'Lot Flash — Gemmes + crédits': 'Flash Bundle — Gems + credits',
    'Lot Flash — Gemmes doublées': 'Flash Bundle — Double gems',
    'Lot Flash — Grand format': 'Flash Bundle — Large',
    'Au Mercato : des joueurs confirmés (80+) directement dans votre effectif pro. Un raccourci vers ce que le mercato permet déjà, en plus rapide.': 'In Transfers: established players (80+) straight into your pro squad. A shortcut to what the transfer market already allows, only faster.',
    'La monnaie premium : achat direct, ou obtenue via le VIP, l\'offre de bienvenue ou la roue. Elle ouvre les packs de joueurs (Mercato), les stades premium et le Campus (Boutique).': 'The premium currency: bought directly, or earned through VIP, the welcome offer or the wheel. It unlocks player packs (Transfers), premium stadiums and the Campus (Shop).',
    'Les crédits se gagnent en jouant (objectifs, matchs, vidéos) et achètent du confort. Les gemmes sont à part : elles ne s\'obtiennent qu\'en payant, jamais en jouant normalement.': 'Credits are earned by playing (objectives, matches, videos) and buy convenience. Gems are separate: they can only be paid for, never earned through normal play.',
    'Relance d\'objectifs, révélation de joueur, tenues, maillots : tout ici est du confort ou de l\'apparence. Rien n\'améliore un joueur ni ne change un résultat de match.': 'Objective rerolls, player reveals, suits, kits: everything here is convenience or looks. Nothing improves a player or changes a match result.',
    'Toujours volontaires, jamais imposées : elles rapportent des crédits ou un petit coup de pouce, plafonnées par jour.': 'Always optional, never forced: they pay credits or a small boost, capped per day.',
    'Un abonnement mensuel : crédits chaque jour, un versement de gemmes à chaque renouvellement, et les publicités imposées retirées.': 'A monthly subscription: credits every day, a gem payout on each renewal, and forced ads removed.',
    'Un lot de gemmes à prix réduit, différent chaque jour, valable jusqu\'à minuit. Un seul achat par jour.': 'A discounted gem bundle, different every day, valid until midnight. One purchase per day.',
    'Un tour gratuit chaque jour, ou payant en gemmes ensuite. Crédits, gemmes, révélation de joueur ou pack offert.': 'One free spin a day, then paid in gems. Credits, gems, a player reveal or a free pack.',
    'Aucun achat ne modifie l\'énergie, le staff, la force des joueurs ni le résultat d\'un match.': 'No purchase changes energy, staff, player ratings or a match result.',

    // ── Tutoriel ──────────────────────────────────────────────────────────
    'Cette barre se remplit à chaque victoire. Au bout du chemin : une légende africaine rejoindra votre club. À vous de jouer.': 'This bar fills with every win. At the end of the road, an African legend joins your club. Over to you.',
    'Chaque carte montre un joueur : sa note, sa forme, son moral. Une forme basse fait chuter son rendement — surveillez-la avant chaque match.': 'Each card shows a player: rating, form, morale. Poor form drags his output down — check it before every match.',
    'Touchez un titulaire puis un remplaçant pour les échanger. Les 11 premiers joueurs de la liste sont ceux qui commencent le match.': 'Tap a starter then a substitute to swap them. The first 11 players in the list are the ones who start.',
    'Trois objectifs renouvelés chaque semaine. Ils rapportent des crédits et font avancer votre carrière — le premier palier tombe vite.': 'Three objectives refreshed every week. They pay credits and move your career forward — the first tier comes quickly.',
    'Trois volets : le Terrain pour voir votre onze, l\'Effectif pour changer un joueur, les Consignes pour la formation et le style.': 'Three panels: Pitch to see your XI, Squad to change a player, Instructions for formation and style.',

    // ── Lot 2 : fuites relevées au balayage automatique des écrans ─────────
    'Barème des primes': 'Bonus scale',
    'Barème des primes, calibré sur le budget actuel': 'Bonus scale, calibrated on the current budget',
    'Course aux trophées': 'Trophy race',
    'Palmarès saison par saison': 'Season-by-season honours',
    'Palmarès individuel': 'Individual honours',
    'Palmarès individuel des saisons archivées': 'Individual honours from archived seasons',
    'Records de tous les temps': 'All-time records',
    'Buteurs par championnat': 'Top scorers by league',
    'Meilleur buteur par championnat': 'Top scorer by league',
    'Fin de carrière': 'End of career',
    'Prêts sortants': 'Players out on loan',
    'Révéler un joueur du marché': 'Reveal a player on the market',
    'Révéler un joueur du marché contre une vidéo.': 'Reveal a player on the market by watching a video.',
    "Aucune donnée pour l’instant": 'No data yet',
    '80 crédits chaque jour': '80 credits every day',
    'publicités imposées retirées': 'forced ads removed',
    '80 crédits chaque jour, 60 gemmes à chaque renouvellement, publicités imposées retirées.': '80 credits every day, 60 gems on each renewal, forced ads removed.',
    'Montants recalculés en direct selon votre budget, votre réputation et la richesse de votre championnat. Versés uniquement si le lauréat est chez vous.': 'Amounts recalculated live from your budget, your reputation and the wealth of your league. Paid only if the winner is one of yours.',
    "Risque de retraite à l'issue de la saison en cours, à l'âge qu'ils auront alors.": 'Retirement risk at the end of the current season, at the age they will be then.',
    "Aucun joueur prêté. Envoyez vos jeunes de l'académie chercher du temps de jeu ailleurs : ils reviendront plus forts. Le bouton « Prêter » se trouve sur chaque fiche de joueur (Académie et Effectif).": 'No players out on loan. Send your academy youngsters to find playing time elsewhere — they come back stronger. The "Loan out" button is on every player card (Academy and Squad).',
    'Vous voilà à la tête de {club}. Tout se joue ici : votre effectif, vos tactiques, vos résultats.': 'You are now in charge of {club}. It all happens here: your squad, your tactics, your results.',
    'Monnaie à part, jamais distribuée par les objectifs, le rendez-vous quotidien ou les distinctions de match — uniquement par achat, abonnement VIP ou offre de bienvenue. Ouvre les packs de joueurs (Mercato), les stades premium et le Campus (plus bas).': 'A separate currency, never handed out by objectives, the daily check-in or match awards — only by purchase, VIP subscription or the welcome offer. It unlocks player packs (Transfers), premium stadiums and the Campus (below).',

    // ── Lot 3 : dernières fuites (abréviations d'attributs, décorations) ───
    '(en direct)': '(live)',
    // Abréviations affichées sur les fiches de joueur — 3 lettres, alignées
    // sur les libellés longs déjà traduits juste en dessous.
    'VIT': 'PAC',
    'PAS': 'PAS',
    'FIN': 'FIN',
    'TAC': 'TAC',
    'VIS': 'VIS',
    'PLA': 'POS',
    'PLO': 'DIV',
    'REF': 'REF',
    'PRI': 'HAN',
    'REL': 'KIC',
    'SOR': 'CMD',

    // Onglet « Direct » de l'écran de match (à distinguer du style de jeu).
    'match.tab_live': 'Live',

    // ── Lot 4 : finances du club ──────────────────────────────────────────
    'Finances du mois': 'Monthly finances',
    'Recettes des matchs': 'Matchday income',
    'Sponsors (fin de mois)': 'Sponsors (end of month)',
    'Masse salariale': 'Wage bill',
    'Déjà prélevé ce mois': 'Already deducted this month',
    'Solde du mois (projeté)': 'Monthly balance (projected)',
    "Les sponsors suivent votre réputation et votre classement. Une place en coupe d'Afrique fait bondir les trois postes de recettes.": 'Sponsors follow your reputation and your league position. A place in the African cup lifts all three revenue streams.',

    // ── Lot 5 : carte « Finances du mois » (postes de recettes) ────────────
    'Billetterie': 'Gate receipts',
    'Droits TV': 'TV rights',
    'Primes': 'Bonuses',
    'Sponsors': 'Sponsors',
    'Recettes': 'Income',
    'Charges': 'Costs',

    // ── Lot 6 : dernières chaînes restées en dur (audit complet) ──
    "Calcul...": "Calculating...",
    "Changer de design": "Change design",
    "Construisez avec le budget du club ou en gemmes pour aller plus vite — plus de recettes à chaque match à domicile. Une fois construite, une installation s'entretient : sans entretien elle se dégrade et finit par perdre un niveau. Aucun effet sur vos matchs, quelle que soit la monnaie utilisée.": "Build with the club budget, or with gems to go faster — more income at every home match. Once built, a facility needs upkeep: neglect it and it decays, eventually losing a level. No effect on your matches, whichever currency you use.",
    "restants": "left",
    "Rapport d'avant-match": "Pre-match report",
    "Aucun match joué": "No match played",
    "Appliquer : ligne": "Apply: line",
    "pressing": "pressing",
    "Le xG mesure la qualité des occasions : deux équipes à 1-1 mais 2,4 contre 0,3 de xG n'ont pas fait le même match.": "xG measures the quality of chances: two teams at 1-1 but 2.4 against 0.3 in xG did not play the same match.",
    "Notes à la": "Ratings at the",
    "Fin de la saison": "End of season",
    "Voir les trophées de la saison": "View the season awards",
    "jeune": "youth",
    "jeunes": "youths",
    "Primes encaissées : +": "Bonuses collected: +",
    "Top 5 Ballon d'Or": "Ballon d'Or Top 5",
    "Indemnité": "Fee",
    "Salaire pris en charge :": "Wage covered:",
    "Prêter à": "Loan to",
    "Prêt d'une saison. Sa progression au retour dépendra du": "A one-season loan. His progress on return will depend on the",
    "départ": "start",
    "Quart": "QF",
    "Recherche": "Search",
    "Regarder": "Watch",
};
