// ═══════════════════════════════════════════════════════════════════════════
// ترجمة — العربية
// مُجمّعة تحت window.I18N_AR، تُحمَّل قبل app.js (انظر index.html)، الذي
// يجمع بعد ذلك ملفات اللغات الثلاثة في سجل I18N.
// أي مفتاح غير موجود هنا يعود تلقائيًا إلى الفرنسية (انظر lang-fr.js).
// ═══════════════════════════════════════════════════════════════════════════
window.I18N_AR = {
    'app.subtitle': 'مدير',
    'nav.dashboard': 'الرئيسية',
    'nav.squad': 'التشكيلة',
    'nav.tactics': 'التكتيك',
    'nav.market': 'الانتقالات',
    'nav.staff': 'الطاقم الفني',
    'nav.standings': 'الترتيب',
    'nav.awards': 'الجوائز',
    'nav.shop': 'المتجر',
    'nav.campus': 'الحرم',
    'nav.home_mobile': 'الرئيسية',
    'nav.more': 'المزيد',
    'nav.profile': 'الملف الشخصي',
    'nav.reset': 'إعادة تعيين',
    'screen.tactics': 'مكتب التكتيك',
    'screen.standings': 'الترتيب',
    'screen.squad': 'التشكيلة الاحترافية',
    'screen.squad_sub': 'لاعبوك المتعاقدون حاليًا.',

    // ── الدفعة 1: بيانات اللعبة ──────────────────────────────────────────
    // الطاقم الفني
    'Entraîneur Adjoint': 'المدرب المساعد',
    'Bonus Tactique': 'مكافأة تكتيكية',
    'Kiné Chef': 'كبير المعالجين',
    'Récupération': 'التعافي',
    'Recruteur Chef': 'كبير الكشافين',
    'Précision scouting': 'دقة الكشف',
    'Médecin du Sport': 'طبيب رياضي',
    'Risque blessure': 'خطر الإصابة',
    'Manager des Jeunes': 'مدير الناشئين',
    'Progression académie': 'تطور الأكاديمية',

    // أزياء المدير
    'Costume Marine, cravate': 'بدلة كحلية، ربطة عنق',
    'Costume Noir, cravate': 'بدلة سوداء، ربطة عنق',
    'Gris moderne, col ouvert': 'رمادي عصري، ياقة مفتوحة',
    'Bordeaux élégant, cravate': 'خمري أنيق، ربطة عنق',
    'Vert olive, décontracté': 'أخضر زيتوني، غير رسمي',
    'Ivoire, cravate dorée': 'عاجي، ربطة ذهبية',
    'Sable, col mao': 'رملي، ياقة صينية',
    'Bleu nuit, pochette rouge': 'أزرق ليلي، منديل جيب أحمر',
    'Anthracite, boutons dorés': 'رمادي فحمي، أزرار ذهبية',
    'Prestige, revers ivoire': 'فاخرة، ياقة عاجية',

    // متجر الرصيد (راحة/تجميل)
    'Relancer les objectifs': 'إعادة سحب الأهداف',
    "Tire trois nouveaux objectifs hebdomadaires.": "يسحب ثلاثة أهداف أسبوعية جديدة.",
    'Révéler un joueur': 'كشف لاعب',
    "Dévoile les statistiques d'un joueur non supervisé du marché.": "يكشف إحصائيات لاعب غير مُستكشف في السوق.",
    'Tenue Ivoire': 'زي عاجي',
    "Costume ivoire, cravate dorée.": "بدلة عاجية، ربطة عنق ذهبية.",
    'Tenue Sable': 'زي رملي',
    "Costume sable, col mao.": "بدلة رملية، ياقة صينية.",
    'Tenue Bleu nuit': 'زي أزرق ليلي',
    "Bleu nuit, pochette rouge.": "أزرق ليلي، منديل جيب أحمر.",
    'Tenue Or': 'زي ذهبي',
    "Costume anthracite, boutons dorés.": "بدلة رمادية فحمية، أزرار ذهبية.",
    'Portée': 'مرتدى',
    'Porter': 'ارتداء',

    // الأهداف الأسبوعية
    'Gagner 2 matchs': 'الفوز بمباراتين',
    'Marquer 5 buts': 'تسجيل 5 أهداف',
    'Garder 1 cage inviolée': 'الحفاظ على نظافة الشباك مرة',
    'Gagner 3 points de stat': 'كسب 3 نقاط إحصائية',
    'Rester 3 matchs invaincu': 'عدم الهزيمة في 3 مباريات',
    'Un joueur noté 8.0 ou plus': 'لاعب بتقييم 8.0 أو أعلى',
    'Objectif rempli': 'اكتمل الهدف',
    'crédits': 'رصيد',

    // قمصان النادي
    'Historique': 'كلاسيكي',
    'Rayé': 'مخطط',
    'Cerclé': 'محلق',
    'Écharpe': 'وشاح',
    'Or & Nuit': 'ذهبي وليلي',
    'Flamme': 'لهب',

    // الملاعب
    'Terre Battue': 'الملعب الترابي',
    "Le terrain d'origine du club — poussiéreux mais chaleureux.": "ملعب النادي الأصلي — ترابي لكنه مفعم بالحماس.",
    'Tribune Populaire': 'المدرج الشعبي',
    "Des tribunes qui se remplissent, une ambiance qui monte.": "مدرجات تمتلئ، وأجواء تشتعل.",
    'Arène Moderne': 'الملعب الحديث',
    "Béton et acier — un stade aux normes continentales.": "خرسانة وفولاذ — ملعب بمعايير قارية.",
    'Nocturne': 'مباراة ليلية',
    "Sous les projecteurs — l'ambiance électrique des matchs en soirée.": "تحت الأضواء — أجواء كهربائية لمباريات المساء.",
    'Nocturne Doré': 'ليلة ذهبية',
    "La même nuit électrique, habillée d'or — exclusif.": "نفس الليلة الكهربائية، بحلة ذهبية — حصري.",
    'Arène Continentale': 'الملعب القاري',
    "Le décor des grands soirs de CAF — bleu et lumière.": "أجواء ليالي الكاف الكبرى — أزرق وضوء.",
    'Jour de Finale': 'يوم النهائي',
    "Feux d'artifice et confettis — le stade d'un soir de sacre.": "ألعاب نارية وقصاصات ورقية — ملعب ليلة التتويج.",

    // احتفالات الأهداف
    'Classique': 'كلاسيكي',
    'Sprint au coin': 'ركضة الركنية',
    'Glissade': 'انزلاقة الركبتين',
    'Virage en fusion': 'المدرج المشتعل',
    "Feu d'artifice": 'ألعاب نارية',
    'Statut de légende': 'مكانة الأسطورة',
    'Nuit continentale': 'ليلة قارية',
    'Roue de la Fortune': 'عجلة الحظ',
    'Tour gratuit du jour': 'الدورة المجانية اليومية',

    // شارات الملف الشخصي
    'Aucun': 'لا شيء',
    'Sur le banc': 'على مقاعد البدلاء',
    'Tacticien': 'خبير التكتيك',
    'Bâtisseur': 'البنّاء',
    'Gagneur': 'الفائز',
    'Légende': 'أسطورة',
    'Icône continentale': 'أيقونة قارية',

    // الحرم الجامعي (الملعب)
    'Tribunes agrandies': 'مدرجات موسعة',
    "Plus de places disponibles à domicile — hausse directe du plafond de billetterie.": "المزيد من المقاعد في الديار — رفع مباشر لسقف التذاكر.",
    'Boutique du Club': 'متجر النادي',
    "Maillots et produits dérivés — un revenu fixe supplémentaire à chaque match.": "قمصان ومنتجات — دخل ثابت إضافي في كل مباراة.",
    'Espace VIP': 'صالة كبار الشخصيات',
    "Loges premium pour sponsors et invités — revenu de prestige à chaque match.": "أجنحة فاخرة للرعاة والضيوف — دخل مرموق في كل مباراة.",
    'Chaudron & Ambiance': 'المرجل والأجواء',
    "Un stade qui vibre attire plus de monde — billetterie additionnelle à domicile.": "ملعب نابض بالحياة يجذب المزيد من الجماهير — تذاكر إضافية في الديار.",
    'Écran Géant': 'شاشة عملاقة',
    "Purement visuel — l'ambiance du jour de match, sans effet sur les recettes.": "بصري فقط — أجواء يوم المباراة، دون أي تأثير على الإيرادات.",

    // جوائز نهاية الموسم
    "Ballon d'Or Africain": "الكرة الذهبية الأفريقية",
    "Le meilleur joueur du continent, tous postes confondus.": "أفضل لاعب في القارة، بجميع المراكز.",
    "Soulier d'Or Africain": "الحذاء الذهبي الأفريقي",
    "Le plus grand buteur des 10 championnats.": "أفضل هداف في الدوريات العشرة.",
    "Meilleur Passeur Africain": "أفضل صانع ألعاب أفريقي",
    "Le maître à jouer de la saison.": "عبقري خط الوسط في الموسم.",
    "Gant d'Or Africain": "القفاز الذهبي الأفريقي",
    "Le gardien le plus infranchissable.": "الحارس الأكثر صعوبة في الاختراق.",
    "Meilleur Espoir Africain": "أفضل لاعب واعد أفريقي",
    "Le meilleur joueur de 21 ans ou moins.": "أفضل لاعب يبلغ 21 عامًا أو أقل.",
    "Meilleur buteur du championnat": "هداف الدوري",
    "Le canonnier de votre championnat.": "قناص دوريك.",
    'Non attribué cette saison': 'لم تُمنح هذا الموسم',
    'm. joués': 'مباراة',
    'passes déc.': 'تمريرة حاسمة',
    'buts': 'أهداف',
    'passes': 'تمريرات',
    'Prime sponsors': 'مكافأة الرعاة',
    'Prime versée à': 'مكافأة مدفوعة إلى',

    // ── الدفعة 2: المتجر + الحرم الجامعي ─────────────────────────────────
    'Poignée de crédits': 'حفنة من الرصيد',
    'Sac de crédits': 'كيس من الرصيد',
    'Coffre de crédits': 'صندوق من الرصيد',
    'Édition Manager': 'إصدار المدير',
    "Retire les publicités imposées, offre 1000 crédits, la tenue Or exclusive et un second emplacement de carrière.": "يزيل الإعلانات الإجبارية، ويمنح 1000 رصيد، والزي الذهبي الحصري، وفتحة مسيرة ثانية.",
    "Débloque la piste Prestige du pass en cours : cosmétiques exclusifs et crédits à chaque palier.": "يفتح مسار الفخامة للتذكرة الحالية: عناصر تجميلية حصرية ورصيد في كل مستوى.",
    'Offre de bienvenue': 'عرض الترحيب',
    "1200 crédits, 150 gemmes, la tenue Ivoire et un Pack Découverte (1 joueur confirmé) offerts. Réservée à votre première saison.": "1200 رصيد، 150 جوهرة، الزي العاجي وحزمة اكتشاف مجانية (لاعب واحد مؤكد). حصري لموسمك الأول.",
    'Abonnement VIP': 'اشتراك كبار الشخصيات',
    "80 crédits chaque jour, 60 gemmes à chaque renouvellement, publicités imposées retirées, badge VIP. Reconduction automatique chaque mois à 2,49 € jusqu'à résiliation — résiliable à tout moment depuis le Play Store.": "80 رصيد يوميًا، 60 جوهرة عند كل تجديد، إزالة الإعلانات الإجبارية، شارة كبار الشخصيات. يتجدد تلقائيًا شهريًا بسعر 2.49 يورو حتى الإلغاء — يمكن الإلغاء في أي وقت من متجر Play.",
    'Sachet de gemmes': 'كيس جواهر صغير',
    'Bourse de gemmes': 'كيس جواهر',
    'Coffre de gemmes': 'صندوق جواهر',
    'Pack Découverte': 'حزمة الاكتشاف',
    "1 joueur confirmé (80-85), immédiatement dans l'effectif.": "لاعب واحد مؤكد (80-85)، يُضاف فورًا إلى التشكيلة.",
    'Pack Talents': 'حزمة المواهب',
    "3 joueurs confirmés (80-88) en un seul tirage.": "3 لاعبين مؤكدين (80-88) في سحب واحد.",
    'Pack Génération': 'حزمة الجيل',
    "6 joueurs confirmés (83-92) — un effectif de stars d'un coup.": "6 لاعبين مؤكدين (83-92) — تشكيلة من النجوم دفعة واحدة.",
    '80 crédits': '80 رصيد',
    '220 crédits': '220 رصيد',
    '20 gemmes': '20 جوهرة',
    '50 gemmes': '50 جوهرة',
    'Révélation gratuite': 'كشف مجاني',
    'Pack Découverte offert': 'حزمة اكتشاف مجانية',
    'Jackpot — 180 gemmes': 'الجائزة الكبرى — 180 جوهرة',
    'Populaire': 'الأكثر رواجًا',
    'Meilleure valeur': 'أفضل قيمة',
    'Une fois': 'مرة واحدة',
    'Restaurer': 'استعادة',
    'Actif': 'مفعّل',
    'Tourner': 'تدوير',
    'gemmes': 'جواهر',

    // ── الدفعة 3: شاشات اللعبة (البداية) ─────────────────────────────────
    'Exige un transfert': 'يطالب بالانتقال',
    'Transfert': 'انتقال',
    'Réclame du temps de jeu': 'يطالب بمزيد من وقت اللعب',
    'Frustré': 'محبط',
    'Refuser': 'رفض',
    'Récupérer': 'استلام',
    'Prêter': 'إعارة',
    'Fermer': 'إغلاق',
    'Accepter': 'قبول',
    'Valider': 'تأكيد',
    'Tout auto': 'تعبئة تلقائية',
    'Reprendre le match': 'استئناف المباراة',
    'Rencontrer': 'مقابلة',
    'Mon club': 'ناديي',
    'Licencier': 'إقالة',
    'Ignorer': 'تجاهل',
    'Décliner': 'رفض',
    'Compositions': 'التشكيلات',
    'Annuler': 'إلغاء',
    'Afrique': 'أفريقيا',

    // ── الدفعة 3 (تابع): الانتقالات، الأكاديمية، الطاقم ──────────────────
    'Tous postes': 'كل المراكز',
    'Tous prix': 'كل الأسعار',
    'Tout niveau': 'كل المستويات',
    'Rafraîchir les agents libres': 'تحديث اللاعبين الأحرار',
    'Infrastructures': 'المنشآت',
    'Niv. Max Atteint': 'تم بلوغ الحد الأقصى',
    'Améliorer': 'ترقية',
    'Débutant': 'مبتدئ',
    'Confirmé': 'متمرس',
    'Expérimenté': 'ذو خبرة',
    'Réputé': 'مرموق',
    'Élite': 'النخبة',
    'ans': 'سنة',

    // ── الدفعة 4: الإشعارات، صندوق الوارد، المقابلات ─────────────────────
    'Aucun message': 'لا توجد رسائل',
    'Offre reçue': 'عرض مستلم',
    'Recrutement': 'تعاقد',
    'Demande de prêt': 'طلب إعارة',
    'Proposition': 'عرض',
    'Alerte': 'تنبيه',
    'Contrat': 'عقد',
    'Vestiaire': 'غرفة الملابس',
    'Palier': 'مستوى',
    'Distinction': 'جائزة',
    'Objectif': 'هدف',
    'Quotidien': 'يومي',
    'Info': 'معلومة',
    'Bonus': 'مكافأة',
    'Une réaction ?': 'أي رد فعل؟',
    'Le défendre publiquement': 'الدفاع عنه علنًا',
    'Prendre ses distances': 'النأي بالنفس',
    'Ne pas réagir': 'عدم الرد',
    'Le féliciter publiquement': 'تهنئته علنًا',
    'Recentrer sur le collectif': 'التركيز على الفريق',
    'Rester factuel': 'التزام الموضوعية',

    // ── الدفعة 4 (تابع): تعليقات المباراة المباشرة ───────────────────────
    "L'arbitre siffle le coup d'envoi. C'est parti !": "يصفر الحكم بداية المباراة. لقد انطلقنا!",
    "Mi-temps. Les équipes rentrent aux vestiaires.": "الشوط الأول. الفريقان يعودان إلى غرف الملابس.",
    "Fin de la première période de prolongation.": "نهاية الشوط الأول من الوقت الإضافي.",
    "Fin du temps réglementaire.": "نهاية الوقت الأصلي.",
    "Coup de sifflet final !": "صافرة النهاية!",
    "PENALTY sifflé pour": "ركلة جزاء لصالح",
    "place le ballon sur le point.": "يضع الكرة على البقعة.",
    "Corner pour": "ركلة ركنية لصالح",
    "Coup franc dangereux pour": "ركلة حرة خطيرة لصالح",
    "se charge du ballon.": "يتولى تنفيذها.",
    "EXPULSION !": "طرد!",
    "voit son 2e carton jaune !": "يحصل على بطاقته الصفراء الثانية!",
    "Faute tactique. Carton jaune pour": "خطأ تكتيكي. بطاقة صفراء لـ",
    "CARTON ROUGE DIRECT !": "بطاقة حمراء مباشرة!",
    "Faute grossière de": "خطأ فادح من",
    "BLESSURE !": "إصابة!",
    "est touché": "يتعرض للإصابة",
    "Son énergie s'effondre, remplacez-le vite !": "طاقته تنهار، بدّله بسرعة!",
    "Changement :": "تبديل:",
    "remplace": "يحل محل",
    "sorti sur blessure.": "الذي خرج بداعي الإصابة.",
    "Coup dur pour l'adversaire :": "ضربة موجعة للخصم:",
    "sort sur civière et l'équipe n'a plus de remplaçant !": "يُخرج على نقالة والفريق ليس لديه بدلاء متبقون!",
    "Action fulgurante de": "هجمة خاطفة من",
    "La défense de": "دفاع",
    "repousse le danger.": "يبعد الخطر.",

    // ── الدفعة 6: تعليقات المباراة (تابع) ─────────────────────────────────
    "Toujours rien pour départager les deux clubs — on joue la prolongation (2 × 15 min).": "لا شيء يفصل بين الفريقين حتى الآن — نلعب وقتًا إضافيًا (2 × 15 دقيقة).",
    "Prolongation ! Un 6e remplacement vous est accordé.": "وقت إضافي! تم منحك تبديلاً سادسًا.",
    "minute(s) de temps additionnel.": "دقيقة (دقائق) وقت بدل ضائع.",
    "Séance de tirs au but :": "ركلات الترجيح:",
    "se qualifie !": "يتأهل!",
    "Changement tactique pour l'adversaire.": "تبديل تكتيكي للخصم.",

    // ── الدفعة 7: تعليقات الأهداف ──────────────────────────────────────────
    'BUT !': 'هــدف!',
    'sert': 'يمرر لـ',
    'qui conclut en beauté !': 'الذي يسددها بشكل رائع!',
    'Quelle passe de': 'يا لها من تمريرة من',
    'ne pouvait pas rater !': 'لم يكن ليخطئها!',
    'Superbe centre de': 'عرضية رائعة من',
    'pour': 'إلى',
    'BUT SUR PENALTY !': 'هدف من ركلة جزاء!',
    'transforme avec sang-froid !': 'يسددها ببرود أعصاب!',
    'COUP FRANC DIRECT !': 'ركلة حرة مباشرة!',
    'enroule par-dessus le mur !': 'يلفها فوق الحائط!',
    'BUT EXCEPTIONNEL !': 'هدف استثنائي!',
    'Frappe de': 'تسديدة من',
    'à': 'من مسافة',
    'mètres': 'أمتار',
    'place parfaitement son tir': 'يضع تسديدته بدقة',
    'à bout portant': 'من مسافة قريبة جدًا',
    'INCROYABLE RATÉ !': 'إهدار لا يُصدق!',
    'était seul face au but !': 'كان منفردًا بالمرمى!',
    'ARRÊT MIRACULEUX !': 'تصدٍ معجزة!',
    'Le gardien sauve son équipe face à': 'الحارس ينقذ فريقه أمام',
    'Frappe lointaine de': 'تسديدة من بعيد من',
    'qui passe loin du cadre.': 'تمر بعيدًا عن المرمى.',
    'Tir dans un angle fermé de': 'تسديدة من زاوية ضيقة من',
    'capté tranquillement par le gardien.': 'يمسكها الحارس بهدوء.',
    'Bel arrêt du gardien sur cette frappe de': 'تصدٍ جميل من الحارس لتسديدة',
    'dévisse légèrement son tir.': 'يخطئ تصويبته قليلاً.',
    'La défense se jette et contre la frappe de': 'الدفاع يرمي بنفسه ويصد تسديدة',

    // ── الدفعة 8: شاشة الكاف ───────────────────────────────────────────────
    "Votre club n'est pas qualifié cette saison — terminez": "ناديك غير مؤهل هذا الموسم — أنهِ",
    'Top 2': 'المركز الثاني أو أفضل',
    'de votre championnat pour participer.': 'في دوريك للمشاركة.',
    'Votre club est éliminé': 'تم إقصاء ناديك',
    'Sorti en': 'خرج في',
    'Phase de groupes': 'دور المجموعات',
    'Demi-finale': 'نصف النهائي',
    'vous pouvez suivre la suite de la compétition en spectateur.': 'يمكنك متابعة باقي البطولة كمتفرج.',
    "Champion d'Afrique": 'بطل أفريقيا',
    'GROUPE': 'المجموعة',
    'Votre groupe': 'مجموعتك',
    'Club': 'النادي',
    'V': 'ف',
    'N': 'ت',
    'D': 'خ',
    'Pts': 'نقاط',
    'Quarts de finale': 'ربع النهائي',
    'Aller': 'الذهاب',
    'Retour': 'الإياب',
    'Finale': 'النهائي',

    // ── الدفعة 9: الترتيب + أحاديث الاستراحة ─────────────────────────────
    'j': 'ج',
    'Rester calme': 'الهدوء',
    "On ne change rien, on continue.": "لا نغيّر شيئًا، نواصل.",
    'Encourager': 'التشجيع',
    "Vous leur dites votre confiance.": "تُظهر لهم ثقتك بهم.",
    'Secouer': 'الحزم',
    "Le ton monte dans le vestiaire.": "ترتفع حدة النبرة في غرفة الملابس.",
    'Exiger le bloc': 'التماسك الدفاعي',
    "Consignes serrées, on verrouille.": "تعليمات صارمة، نُحكم الإغلاق.",
    "Vous menez à la pause. Le vestiaire est chaud.": "تتقدم في الاستراحة. الأجواء حماسية في غرفة الملابس.",
    "Vous êtes menés. Onze paires d'yeux vous regardent.": "أنت متأخر في النتيجة. أحد عشر زوجًا من العيون تراقبك.",
    "Tout reste à faire. Le match se joue maintenant.": "كل شيء لا يزال ممكنًا. المباراة تُحسم الآن.",

    // ── الدفعة 9 (تابع): التعليمات التكتيكية ──────────────────────────────
    "Couloir d'attaque": 'ممر الهجوم',
    'Par où le jeu sort': 'من أين تنطلق الهجمات',
    'Mixte': 'مختلط',
    'Axe': 'من المحور',
    'Deux ailes': 'كلا الجناحين',
    'Droite': 'اليمين',
    'Gauche': 'اليسار',
    'Pressing': 'الضغط',
    'Où on va chercher le ballon': 'أين نسترد الكرة',
    'Sa surface': 'منطقة جزائهم',
    'Sa moitié': 'نصف ملعبهم',
    'Tout terrain': 'كامل الملعب',
    'Ligne défensive': 'خط الدفاع',
    'La hauteur du bloc': 'ارتفاع خط الدفاع',
    'Basse': 'منخفض',
    'Normale': 'عادي',
    'Haute': 'مرتفع',
    'Mentalité': 'العقلية',
    'Défensive': 'دفاعية',
    'Équilibrée': 'متوازنة',
    'Offensive': 'هجومية',
    'Style de jeu': 'أسلوب اللعب',
    'Possession': 'الاستحواذ',
    'Direct': 'مباشر',
    'Contre': 'الهجوم المرتد',
    'Consignes en direct': 'تعليمات مباشرة',
    "Chaque changement s'applique immédiatement, sans arrêter le jeu.": "كل تغيير يُطبَّق فورًا، دون إيقاف اللعب.",
    'Fermer': 'إغلاق',
    'Formation': 'التشكيل',

    // ── شاشة الإعدادات ─────────────────────────────────────────────────
    'nav.settings': 'الإعدادات',
    'Langue': 'اللغة',
    'Apparence': 'المظهر',
    'Sombre': 'داكن',
    'Clair': 'فاتح',
    'Le mode clair est encore en cours de finition sur certains écrans.': 'الوضع الفاتح لا يزال قيد التحسين في بعض الشاشات.',
    'Ambiance sonore': 'الأجواء الصوتية',
    'Revoir le tutoriel': 'إعادة مشاهدة الدرس التعليمي',
    'Revoir le tutoriel de la boutique': 'إعادة مشاهدة درس المتجر',

    // ── مفاوضات الانتقالات والعقود ─────────────────────────────────────
    'Renouvellement de contrat': 'تجديد العقد',
    'OVR': 'التقييم',
    'Salaire actuel :': 'الراتب الحالي:',
    'mois': 'شهر',
    'Nouveau salaire demandé :': 'الراتب الجديد المطلوب:',
    'Durée :': 'المدة:',
    'saisons': 'مواسم',
    'Contrat de': 'عقد',
    'renouvelé (2 saisons) !': 'تم تجديده (موسمان)!',
    'Prolonger': 'تمديد',
    "Effectif complet (30 joueurs maximum).": "التشكيلة مكتملة (30 لاعبًا كحد أقصى).",
    'ne peut pas vendre': 'لا يمكنه بيع',
    "il n'est chez eux qu'en prêt, il ne leur appartient pas.": "إنه معهم بالإعارة فقط، لا يملكونه.",
    'refuse de négocier.': 'يرفض التفاوض.',
    'Leur effectif est déjà trop court': 'تشكيلتهم ضعيفة العدد أصلاً',
    'joueurs': 'لاعبين',
    'pour se séparer de qui que ce soit.': 'للتخلي عن أي لاعب.',
    'refuse net.': 'يرفض رفضًا قاطعًا.',
    "est un pilier du club : il n'est pas à vendre, quel que soit le montant.": "ركيزة أساسية في النادي: غير معروض للبيع مهما كان المبلغ.",
    'réclame': 'يطلب',
    'pour': 'مقابل',
    'Vos fonds :': 'أموالك:',
    'Il vous manque': 'ينقصك',
    'accepte de négocier': 'يوافق على التفاوض بشأن',
    'ans': 'سنة',
    'POT': 'الإمكانات',
    'Indemnité de transfert :': 'رسوم الانتقال:',
    'Salaire réclamé :': 'الراتب المطلوب:',
    'Le club a besoin de liquidités : le prix est en dessous de sa valeur.': 'النادي بحاجة إلى سيولة: السعر أقل من قيمته الفعلية.',
    "C'est un titulaire chez eux, d'où la majoration.": "إنه أساسي لديهم، ولهذا السعر مرتفع.",
    'Fonds insuffisants.': 'أموال غير كافية.',
    "Ce joueur n'est plus disponible.": 'هذا اللاعب لم يعد متاحًا.',
    'rejoint': 'ينضم إلى',
    'Signer': 'توقيع',

    // ── تعليقات إضافية + طلب الإعارة ────────────────────────────────────
    'CHANGEMENT TACTIQUE :': 'تبديل تكتيكي:',
    'entre à la place de': 'يدخل بدلاً من',
    'Le groupe répond présent.': 'المجموعة تستجيب بشكل جيد.',
    'Le message passe mal, les têtes se baissent.': 'الرسالة لم تصل بشكل جيد، الرؤوس تنحني.',
    'Le groupe écoute sans broncher.': 'المجموعة تستمع دون اعتراض.',
    'Causerie': 'حديث الفريق',
    'Consigne du banc': 'تعليمات من دكة البدلاء',
    'Maximum 4 joueurs empruntés simultanément.': 'الحد الأقصى 4 لاعبين معارين في آنٍ واحد.',
    'est déjà en prêt à': 'معار بالفعل إلى',
    'il ne peut pas être re-prêté.': 'لا يمكن إعارته مجددًا.',
    'refuse :': 'يرفض:',
    'leur effectif': 'تشكيلتهم',
    "est trop court pour se priver de quelqu'un.": 'ضعيفة العدد لتفويت أي لاعب.',
    'refuse.': 'يرفض.',
    'est titulaire chez eux': 'أساسي لديهم',
    'e de la hiérarchie': 'في الترتيب',
    "On ne prête pas un homme dont on a besoin le week-end.": 'لا يُعار لاعب نحتاجه في عطلة نهاية الأسبوع.',
    'décline poliment.': 'يعتذر بأدب.',
    'À OVR': 'بتقييم',
    'vise plus haut que': 'يطمح لمستوى أعلى من',
    'force': 'قوة',
    "Renforcez d'abord la stature du club.": 'عزّز مكانة ناديك أولاً.',
    'Indemnité de prêt réclamée :': 'رسوم الإعارة المطلوبة:',
    'Vos fonds ne suffisent pas.': 'أموالك غير كافية.',
    'accepte de vous prêter': 'يوافق على إعارتك',
    'pour une saison.': 'لمدة موسم.',
    'Indemnité de prêt :': 'رسوم الإعارة:',
    'Salaire à votre charge :': 'الراتب على عاتقك:',
    'Il repartira automatiquement chez lui en fin de saison. Vous ne pourrez ni le vendre, ni le re-prêter.': 'سيعود تلقائيًا إلى ناديه في نهاية الموسم. لا يمكنك بيعه أو إعارته مجددًا.',

    // ── المؤتمرات الصحفية (ردود قصيرة + اقتباسات) ─────────────────────
    'Un pas à la fois': 'خطوة بخطوة',
    'On vise le trophée': 'نستهدف اللقب',
    'Féliciter les joueurs': 'الإشادة باللاعبين',
    'Relativiser': 'التخفيف من وقع الأمر',
    'Reconnaître la déception': 'الاعتراف بخيبة الأمل',
    "Blâmer l'arbitrage": 'لوم التحكيم',
    'Regarder devant': 'التطلع للأمام',
    'Revendiquer le travail': 'المطالبة بالفضل في العمل المُنجز',
    'Rester humble': 'التحلي بالتواضع',
    'Rassurer le groupe': 'طمأنة المجموعة',
    'Se remettre en cause': 'مراجعة النفس',
    'Hausser le ton': 'رفع نبرة الخطاب',
    'Ne rien changer': 'عدم تغيير أي شيء',
    'Se projeter sur le titre': 'التطلع نحو اللقب',
    'Prévenir un relâchement': 'التحذير من التراخي',
    'Journée après journée': 'مباراة تلو الأخرى',
    'Assumer le costume': 'تحمل المسؤولية بثقة',
    'Rejeter la pression': 'رفض فكرة الضغط',
    'Dédramatiser': 'التقليل من حدة الموقف',
    "Sonner l'alarme": 'دق ناقوس الخطر',
    'Rassurer la direction': 'طمأنة الإدارة',
    'Demander du temps': 'طلب الوقت',
    'Défier les critiques': 'تحدي المنتقدين',
    'Ne pas commenter': 'الامتناع عن التعليق',
    'Protéger le groupe': 'حماية المجموعة',
    'Assumer seul': 'تحمل المسؤولية بمفردي',
    'Pointer les manques': 'الإشارة إلى أوجه القصور',
    'Rester prudent': 'التزام الحذر',
    "Assumer l'ambition": 'الإفصاح عن الطموح',
    'Créditer le groupe': 'الفضل يعود للمجموعة',
    "Les points d'abord": 'النقاط أولاً',
    'Reconnaître les limites': 'الاعتراف بأوجه القصور',
    'Saluer le mental': 'الإشادة بالعزيمة',
    'Féliciter la défense': 'الإشادة بالدفاع',
    "Réclamer plus d'ambition": 'المطالبة بمزيد من الطموح',
    'Un point pris': 'نقطة مكتسبة',
    'Un point de trop perdu': 'نقطة مهدورة',
    'Rester neutre': 'الحياد',
    'Rester vague': 'عدم التحديد',
    'Annoncer une ambition': 'الإعلان عن طموح',
    'Prôner la prudence': 'الدعوة إلى الحذر',
    "S'en réjouir ouvertement": 'الاحتفاء بذلك علنًا',
    'Match après match': 'مباراة تلو الأخرى',
    'Viser plus haut': 'استهداف الأعلى',
    'Rester lucide': 'التحلي بالواقعية',
    'On savoure ce soir, on repense au continent demain.': 'نحتفل الليلة، ونفكر في القارة غدًا.',
    'On ne participe pas pour faire de la figuration. On y va pour le gagner.': 'لسنا هنا لمجرد المشاركة. نحن هنا للفوز به.',
    'Ce sont eux qui ont fait le travail sur le terrain, pas moi.': 'هم من قاموا بالعمل على أرض الملعب، وليس أنا.',
    'Le championnat reste notre priorité. On tourne la page vite.': 'الدوري يبقى أولويتنا. نطوي الصفحة بسرعة.',
    "C'est une désillusion. On visait plus loin, il faut le dire.": 'إنها خيبة أمل. كنا نطمح لأبعد من ذلك، يجب قول ذلك.',
    "Certaines décisions ont pesé lourd ce soir. Je ne suis pas le seul à l'avoir vu.": 'بعض القرارات كان لها وزن ثقيل الليلة. لست الوحيد الذي لاحظ ذلك.',
    'Les chiffres, on les comptera à la fin. Pas avant.': 'سنحسب الأرقام في النهاية. وليس قبل ذلك.',
    'Ce club a changé de visage depuis mon arrivée. Je le dis sans fausse modestie.': 'تغير وجه هذا النادي منذ وصولي. أقول ذلك دون تواضع زائف.',
    "Je ne suis qu'un maillon. Le club était là avant moi, il sera là après.": 'أنا مجرد حلقة. النادي كان موجودًا قبلي، وسيبقى موجودًا بعدي.',
    "On va s'en sortir ensemble. Douter maintenant serait la pire erreur.": 'سنتجاوز هذا معًا. الشك الآن سيكون أسوأ خطأ.',
    "Le premier responsable d'une série comme celle-là, c'est le coach. Je regarde ce que je peux changer.": 'المسؤول الأول عن سلسلة كهذه هو المدرب. أنظر إلى ما يمكنني تغييره.',
    "Il y a un manque d'exigence individuelle. Ça doit changer, et vite.": 'هناك نقص في الصرامة الفردية. يجب أن يتغير هذا، وبسرعة.',
    "On garde les pieds sur terre et la même méthode. C'est elle qui paie.": 'نبقى واقعيين ونتمسك بنفس الأسلوب. إنه ما يؤتي ثماره.',
    "À ce rythme, il n'y a aucune raison de se cacher sur nos ambitions.": 'بهذا المعدل، لا داعٍ لإخفاء طموحاتنا.',
    "Le vrai danger maintenant, c'est de croire qu'on a déjà gagné quelque chose.": 'الخطر الحقيقي الآن هو الاعتقاد بأننا حققنا شيئًا بالفعل.',
    'On ne regarde pas le classement, seulement le prochain adversaire.': 'لا ننظر إلى الترتيب، بل إلى الخصم القادم فقط.',
    'On veut ce titre. Autant le dire clairement plutôt que de jouer la fausse humilité.': 'نريد هذا اللقب. من الأفضل قوله بوضوح بدلاً من التظاهر بتواضع زائف.',
    "La pression, c'est pour ceux qui n'ont rien à perdre. Nous, on joue libérés.": 'الضغط لمن ليس لديهم ما يخسرونه. نحن نلعب بتحرر.',
    "On a les moyens de s'en sortir. Il faut juste rester soudés.": 'لدينا القدرة على تجاوز الأمر. يجب فقط أن نبقى متحدين.',
    "La situation est grave. Ceux qui ne le comprennent pas n'ont rien à faire ici.": 'الوضع خطير. من لا يفهم ذلك ليس له مكان هنا.',
    'Je prends mes responsabilités devant le club. On va se maintenir.': 'أتحمل مسؤوليتي أمام النادي. سنبقى في الدوري.',
    'Un projet se juge sur une saison, pas sur trois journées.': 'يُحكم على المشروع خلال موسم كامل، وليس ثلاث مباريات.',
    'Je fais mon travail. Ceux qui doutent jugeront au classement.': 'أقوم بعملي. من يشك سيحكم من خلال الترتيب.',
    'Je ne parle que de football.': 'لا أتحدث إلا عن كرة القدم.',
    "Personne ne lâche. Ces joueurs se battent, je réponds d'eux.": 'لا أحد يستسلم. هؤلاء اللاعبون يقاتلون، وأنا أضمنهم.',
    "L'équipe a fait le travail. Le choix tactique était le mien, l'erreur aussi.": 'الفريق قام بالعمل. الاختيار التكتيكي كان مني، والخطأ أيضًا.',
    "Certains n'ont pas le niveau exigé ici. Ils le savent.": 'بعضهم ليس لديه المستوى المطلوب هنا. وهم يعرفون ذلك.',
    'Un match ne fait pas une saison. On regarde le suivant.': 'مباراة واحدة لا تصنع موسمًا. ننظر إلى التالية.',
    "On joue pour gagner, et de la meilleure des manières. Pourquoi s'en cacher ?": 'نلعب للفوز، وبأفضل طريقة ممكنة. لماذا نخفي ذلك؟',
    'Ce sont eux sur le terrain. Tout leur revient.': 'هم من يلعبون على أرض الملعب. الفضل كله لهم.',
    'Trois points restent trois points, quelle que soit la manière.': 'ثلاث نقاط تبقى ثلاث نقاط، مهما كانت الطريقة.',
    "On sait qu'il y a du travail. Cette victoire ne doit pas masquer ça.": 'نعلم أن هناك عملاً يجب القيام به. هذا الفوز يجب ألا يخفي ذلك.',
    "Ce groupe ne lâche jamais. C'est ce qui a fait la différence.": 'هذه المجموعة لا تستسلم أبدًا. هذا ما صنع الفارق.',
    "C'est un travail collectif, du gardien jusqu'aux attaquants qui défendent en premier.": 'إنه عمل جماعي، من الحارس إلى المهاجمين الذين يدافعون أولاً.',
    "Bien défendre, c'est un point de départ. Il faut aussi être dangereux devant.": 'الدفاع الجيد نقطة انطلاق. يجب أيضًا أن نكون خطيرين في الهجوم.',
    'On a fait le nécessaire. Rien de plus à ajouter.': 'قمنا بما هو ضروري. لا شيء آخر لإضافته.',
    'Face à cet adversaire, ce point est plutôt bon à prendre.': 'أمام هذا الخصم، هذه النقطة جيدة بما يكفي.',
    "On avait les moyens de gagner ce soir. C'est deux points de perdus, pas un de pris.": 'كان لدينا القدرة على الفوز الليلة. هاتان نقطتان ضائعتان، وليست نقطة مكتسبة.',
    'Un résultat logique au vu de la physionomie du match.': 'نتيجة منطقية بالنظر إلى مجريات المباراة.',
    "On construit match après match, sans se fixer de chiffre à l'avance.": 'نبني مباراة تلو الأخرى، دون تحديد رقم مسبقًا.',
    'Ce club a les moyens de viser le haut du tableau cette saison. Je le dis dès maintenant.': 'هذا النادي لديه القدرة على استهداف صدارة الترتيب هذا الموسم. أقول ذلك الآن.',
    "Il faut d'abord poser des bases solides. Les ambitions viendront ensuite.": 'يجب أولاً وضع أسس متينة. الطموحات ستأتي لاحقًا.',
    'La saison est encore longue. On ne regarde pas trop loin.': 'الموسم لا يزال طويلاً. لا ننظر بعيدًا جدًا.',
    "Ce classement, on l'a mérité. Pas de raison de bouder son plaisir.": 'استحققنا هذا الترتيب. لا داعٍ لكبح فرحتنا.',
    'Cette place doit nous donner faim, pas nous satisfaire.': 'هذا المركز يجب أن يزيدنا جوعًا للمزيد، لا أن يُرضينا.',
    'On avance sans regarder trop loin.': 'نتقدم دون النظر بعيدًا جدًا.',
    'Ce groupe peut aller chercher davantage.': 'هذه المجموعة قادرة على تحقيق المزيد.',
    "Nos moyens sont ce qu'ils sont. On fait avec.": 'إمكانياتنا هي ما هي عليه. نعمل بها.',

    // ── أسئلة المؤتمر الصحفي ────────────────────────────────────────────
    'Qualification continentale face à': 'التأهل القاري أمام',
    "L'Afrique, ce n'est plus un rêve ?": 'هل أفريقيا لم تعد حلمًا؟',
    'Élimination continentale contre': 'الإقصاء القاري أمام',
    'Un échec pour le projet ?': 'هل هو فشل للمشروع؟',
    'Un cap symbolique de matchs à la tête du club. Un bilan ?': 'عدد رمزي من المباريات على رأس النادي. ما هو التقييم؟',
    "Troisième défaite d'affilée. La spirale négative vous inquiète-t-elle ?": 'ثالث هزيمة متتالية. هل تقلقك دوامة النتائج السلبية؟',
    "Cinquième match sans défaite. Cette équipe a-t-elle changé de dimension ?": 'خامس مباراة دون هزيمة. هل ارتقى هذا الفريق لمستوى جديد؟',
    'À quelques journées de la fin, vous jouez le titre. La pression monte-t-elle ?': 'قبل جولات قليلة من النهاية، تتنافسون على اللقب. هل يتصاعد الضغط؟',
    'Le club est empêtré dans la lutte pour le maintien. Le discours a-t-il changé dans le vestiaire ?': 'النادي غارق في صراع البقاء. هل تغير الخطاب داخل غرفة الملابس؟',
    'Votre poste est ouvertement discuté. Un message à la direction ?': 'منصبك موضع تساؤل علني. هل من رسالة للإدارة؟',
    'Nouveau revers face à': 'انتكاسة جديدة أمام',
    'Le vestiaire vous échappe-t-il ?': 'هل تفلت منك غرفة الملابس؟',
    'Une démonstration face à': 'عرض قوة أمام',
    'Le plus beau match de la saison ?': 'أجمل مباراة في الموسم؟',
    'Victoire courte mais précieuse contre': 'فوز ضئيل لكنه ثمين أمام',
    'La manière compte-t-elle vraiment ?': 'هل الطريقة مهمة حقًا؟',
    'Une cage inviolée de plus face à': 'شباك نظيفة أخرى أمام',
    'Le socle défensif du club ?': 'الركيزة الدفاعية للنادي؟',
    'Match nul concédé face à': 'تعادل أمام',
    'Un point perdu ou un point pris ?': 'نقطة ضائعة أم نقطة مكتسبة؟',
    'Encore tôt dans la saison. Quels objectifs vous fixez-vous pour cet exercice ?': 'لا يزال الموسم في بدايته. ما الأهداف التي تضعها لهذا الموسم؟',
    'Le club pointe à la': 'يحتل النادي المركز',
    'ᵉ place. Une saison qui prend une belle tournure ?': '. هل يأخذ الموسم منحى جيدًا؟',
    'Comment abordez-vous la suite du championnat,': 'كيف تتعاملون مع بقية الدوري، وأنتم حاليًا في المركز',
    'ᵉ au classement ?': ' في الترتيب؟',

    // ── تقرير ما قبل المباراة (أسلوب الخصم) ─────────────────────────────
    'Garde le ballon et construit patiemment.': 'يحتفظ بالكرة ويبني الهجمات بصبر.',
    "Joue vers l'avant dès que possible, beaucoup de ballons longs.": 'يلعب للأمام في أسرع وقت، بكرات طويلة كثيرة.',
    'Laisse le ballon et frappe en transition.': 'يتنازل عن الكرة ويضرب في الهجمات المرتدة.',
    'Bloc bas, presse seulement dans sa surface.': 'كتلة منخفضة، يضغط فقط داخل منطقة جزائه.',
    'Bloc médian.': 'كتلة متوسطة.',
    'Presse haut, sur tout le terrain.': 'يضغط عاليًا، في كامل الملعب.',
    "Défense basse — l'espace est devant, pas derrière.": 'دفاع منخفض — المساحة أمامك، لا خلفك.',
    'Ligne médiane.': 'خط متوسط.',
    'Ligne haute — un ballon dans le dos peut tout casser.': 'خط مرتفع — كرة خلف الدفاع قد تُفسد كل شيء.',
    'Attaque de partout.': 'يهاجم من كل الجهات.',
    "Cherche l'axe.": 'يبحث عن اللعب من المحور.',
    'Étire le jeu sur les deux ailes.': 'يوسّع اللعب على كلا الجناحين.',
    'Insiste sur son côté droit.': 'يركّز على جانبه الأيمن.',
    'Insiste sur son côté gauche.': 'يركّز على جانبه الأيسر.',
    "Ils attendent la transition : ne laissez pas votre ligne trop haute.": 'ينتظرون الهجمة المرتدة: لا تجعل خط دفاعك مرتفعًا جدًا.',
    "Ils veulent le ballon : allez le leur prendre haut.": 'يريدون الكرة: اذهب لاستردادها منهم عاليًا.',
    "Ils jouent long : reculez la ligne et gagnez les seconds ballons.": 'يلعبون بكرات طويلة: تراجع بخط الدفاع واكسب الكرات الثانية.',

    // ── مستويات المسيرة + أهداف لوحة القيادة ─────────────────────────────
    'Premiers pas': 'الخطوات الأولى',
    'Le conseil vous fait confiance': 'الإدارة تثق بك',
    'Reconnaissance': 'الاعتراف',
    'La presse commence à vous citer': 'الصحافة بدأت تذكرك',
    'Coach confirmé': 'مدرب راسخ',
    'Un sponsor rejoint le projet': 'راعٍ ينضم إلى المشروع',
    'Bâtisseur': 'البنّاء',
    "Vos infrastructures montent d'un cran": 'منشآتك ترتقي مستوى',
    'Monument': 'أيقونة',
    'Une légende africaine rejoint votre projet': 'أسطورة أفريقية تنضم إلى مشروعك',
    'Classements': 'لوحات الصدارة',
    'Obtenu': 'تم تحقيقه',
    'Remporter le titre': 'الفوز باللقب',
    'Top 3 en championnat': 'المركز الثالث أو أفضل في الدوري',
    'Maintien (Top 10)': 'البقاء (ضمن العشرة الأوائل)',

    // ── آخر الثغرات المكتشفة في التحقق النهائي ─────────────────────────
    'Achat déjà en cours...': 'عملية شراء جارية بالفعل...',
    'Offre de bienvenue déjà utilisée ou expirée.': 'عرض الترحيب مستخدم بالفعل أو منتهي الصلاحية.',
    'Pass de saison déjà actif.': 'تذكرة الموسم مفعّلة بالفعل.',

    // ── لوحة القيادة ──────────────────────────────────────────────────────
    'CAF — Finale': 'الكاف — النهائي',
    'CAF — Demi-finale': 'الكاف — نصف النهائي',
    'CAF — Quart de finale': 'الكاف — ربع النهائي',
    'CAF — Phase de groupes': 'الكاف — دور المجموعات',
    'Championnat': 'الدوري',
    'Aucun match': 'لا توجد مباراة',
    'Continental': 'قاري',
    'Fin de saison': 'نهاية الموسم',
    'Réputation': 'السمعة',
    'Masse sal.': 'كتلة الأجور',
    'Contrats': 'العقود',
    'Académie': 'الأكاديمية',
    'Projection fin de saison :': 'توقعات نهاية الموسم:',
    'Masse sal./mois': 'كتلة الأجور/الشهر',

    // ── تبويب التكتيك ─────────────────────────────────────────────────────
    'Contre-attaque': 'الهجوم المرتد',
    'Jeu direct': 'اللعب المباشر',
    'Joueur': 'لاعب',
    'Personne de disponible': 'لا أحد متاح',
    'aucun': 'لا أحد',
    'Choisi': 'مُختار',
    'Auto': 'تلقائي',
    'Penalty': 'ركلة جزاء',
    'Coup franc': 'ركلة حرة',
    'Corner': 'ركلة ركنية',
    'Capitaine': 'القائد',
    'Meneur de jeu': 'صانع الألعاب',
    "Rôles de l'équipe": 'أدوار الفريق',
    'Qui prend le ballon sur coup arrêté': 'من يُنفذ الكرات الثابتة',
    'Joueurs': 'لاعبين',

    // ── تبويب الانتقالات ─────────────────────────────────────────────────
    'Packs de joueurs': 'حزم اللاعبين',
    "Des joueurs confirmés (80+) directement dans l'effectif pro — un raccourci vers ce que le mercato permet déjà, en plus rapide.": "لاعبون مؤكدون (80+) يُضافون مباشرة إلى التشكيلة الاحترافية — طريقة أسرع لما يتيحه سوق الانتقالات أصلاً.",
    'Poste tiré au sort à chaque joueur : 10% Gardien, 30% Défenseur, 30% Milieu, 30% Attaquant. Note exacte tirée au sort dans la fourchette indiquée sur chaque pack.': 'المركز يُحدد عشوائيًا لكل لاعب: 10% حارس مرمى، 30% مدافع، 30% لاعب وسط، 30% مهاجم. التقييم الدقيق يُحدد عشوائيًا ضمن النطاق الموضح على كل حزمة.',
    'Demandes de prêt': 'طلبات الإعارة',
    'Offres reçues': 'العروض المستلمة',
    'Offre de': 'عرض من',
    'Superviser': 'كشف',
    'Stature du projet insuffisante': 'مكانة المشروع غير كافية',
    'LIBRE': 'حر',
    'Agent libre': 'لاعب حر',
    'Acheter': 'شراء',
    'Prime à la signature': 'مكافأة التوقيع',
    'signature(s) restante(s)': 'توقيع(ات) متبقية',
    "Quota d'agents libres épuisé cette saison": 'تم استنفاد حصة اللاعبين الأحرار هذا الموسم',

    // ── تبويب الطاقم الفني ────────────────────────────────────────────────
    'Salaire': 'الراتب',
    'Engager': 'تعيين',
    'requis': 'مطلوب',
    'rejoint le staff': 'ينضم إلى الطاقم',
    'Staff Technique': 'الطاقم الفني',
    'Améliorez votre encadrement pour obtenir des bonus passifs.': 'طوّر طاقمك للحصول على مكافآت تلقائية.',
    'Fonds Dispos': 'الأموال المتاحة',

    // ── تبويب الأكاديمية ──────────────────────────────────────────────────
    'match en réserve': 'مباراة احتياط',
    'matchs en réserve': 'مباريات احتياط',
    'Formation': 'التدريب',
    'Promouvoir': 'ترقية',
    "Votre effectif pro est plein (30 joueurs max) !": "تشكيلتك الاحترافية مكتملة (30 لاعبًا كحد أقصى)!",
    '+ Nouvelle Promotion': '+ دفعة جديدة',

    // ── تبويب الترتيب + الكاف (تكملة) ────────────────────────────────────
    'La compétition continentale se lance en fin de saison. Terminez dans le': 'تنطلق البطولة القارية في نهاية الموسم. أنهِ في',
    'de votre ligue pour y participer.': 'من دوريك للمشاركة فيها.',
    'Demi-finales': 'نصف النهائي',
    'Ligue Elite Africaine': 'الدوري الأفريقي النخبوي',
    'Aucun joueur correspondant aux filtres.': 'لا يوجد لاعب يطابق عوامل التصفية.',
    "Aucun match joué pour l'instant": 'لا توجد مباراة ملعوبة بعد',
    'Résultats': 'النتائج',
    'matchs': 'مباريات',

    // ── تبويب الجوائز ─────────────────────────────────────────────────────
    'cr.': 'رصيد',
    'Le onze sera désigné après la prochaine journée': 'سيُعلن تشكيل الأسبوع بعد الجولة القادمة',
    'Coach de la journée': 'مدرب اليوم',
    'Distinctions': 'الجوائز',
    'crédits': 'رصيد',
    'Rendez-vous quotidien': 'الحضور اليومي',
    'Jour': 'اليوم',
    'Série de': 'سلسلة من',
    'jour(s)': 'يوم (أيام)',
    'crédits à récupérer': 'رصيد جاهز للاستلام',
    'Revenez demain pour poursuivre la série': 'عد غدًا لمواصلة السلسلة',
    'Doubler': 'مضاعفة',
    'Pris': 'تم الاستلام',
    'Objectifs de la semaine': 'أهداف الأسبوع',
    'journée(s) restante(s)': 'جولة (جولات) متبقية',
    'Onze de la journée': 'تشكيلة اليوم',
    'Pass de saison': 'تذكرة الموسم',
    'pts de carrière': 'نقاط المسيرة',
    'Ouvrir la piste Prestige': 'فتح مسار الفخامة',
    'Piste Prestige active': 'مسار الفخامة مفعّل',
    'Tenue exclusive': 'زي حصري',
    'Maillot exclusif': 'قميص حصري',
    'Gratuit': 'مجاني',
    'Prestige': 'الفخامة',
    'Boutique': 'المتجر',

    // ── تبويب التاريخ ─────────────────────────────────────────────────────
    'Le palmarès se remplira à la fin de votre première saison': 'ستمتلئ خزانة الألقاب في نهاية موسمك الأول',
    'Champion': 'بطل',
    'place': 'المركز',
    'Titre': 'لقب',
    'Champion :': 'البطل:',
    'Vainqueur continental :': 'البطل القاري:',
    'Meilleur buteur :': 'الهداف:',
    'Cumuls dès la fin de la 1re saison': 'المجاميع متاحة من نهاية الموسم الأول',
    'retraité': 'متقاعد',
    "Aucun joueur n'approche de la fin de carrière": 'لا يوجد لاعب يقترب من نهاية مسيرته',
    'Buteurs': 'الهدافون',
    'Passeurs': 'صناع الألعاب',
    'Matchs joués': 'المباريات الملعوبة',
    'Histoire du club': 'تاريخ النادي',
    'Palmarès, records de tous les temps et fins de carrière.': 'خزانة الألقاب، الأرقام القياسية التاريخية، ونهايات المسيرة.',

    // ── تبويب المدير / الإعدادات ──────────────────────────────────────────
    'Tactique': 'التكتيك',
    'Gestion': 'الإدارة',
    'Charisme': 'الكاريزما',
    'Saison': 'الموسم',
    'Depuis la saison': 'منذ الموسم',
    'Aucun titre': 'لا ألقاب',
    'Aucun club dans le CV pour le moment.': 'لا يوجد نادٍ في السيرة الذاتية بعد.',
    'Attributs': 'الصفات',
    'Ces notes progressent lentement avec vos résultats, la tenue du vestiaire et vos recrutements — elles ne se réinitialisent jamais.': 'هذه التقييمات تتطور ببطء مع نتائجك، وانضباط غرفة الملابس، وتعاقداتك — ولا تُعاد أبدًا إلى الصفر.',
    'Paliers de carrière': 'مستويات المسيرة',
    'points': 'نقاط',
    'victoires, titres et podiums': 'انتصارات، ألقاب ومراكز متقدمة',
    'Connecté': 'متصل',
    'Votre score :': 'نتيجتك:',
    'Voir': 'عرض',
    'Se connecter à Google Play Games': 'تسجيل الدخول إلى Google Play Games',
    'Points de carrière': 'نقاط المسيرة',

    // ── تبويب التدريب ─────────────────────────────────────────────────────
    'Allégée': 'خفيف',
    'Préserve les jambes': 'يحافظ على لياقة اللاعبين',
    'Normale': 'عادي',
    'Le bon compromis': 'التوازن الأمثل',
    'Intense': 'مكثف',
    'Progresse vite, fatigue et blesse': 'تقدم سريع، لكنه يُتعب ويُصيب',
    'Bloqué': 'متوقف',
    'Lent': 'بطيء',
    'Modéré': 'معتدل',
    'Bon': 'جيد',
    'Rapide': 'سريع',
    'blessé': 'مصاب',
    'Plafond atteint': 'تم بلوغ الحد الأقصى',
    '+1 dans': '+1 خلال',
    'Entraînement': 'التدريب',
    "Rendement selon l'âge": 'الأداء حسب العمر',

    // ── تبويب المدربين ────────────────────────────────────────────────────
    'Vous': 'أنت',
    'Votre équipe': 'فريقك',
    'Entraîneurs': 'المدربون',
    'Offensif': 'هجومي',
    'Défensif': 'دفاعي',
    'Équilibré': 'متوازن',
    'Jeu total': 'كرة القدم الشاملة',

    // ── تكملة: تعليقات/إشعارات ناقصة ──────────────────────────────────────
    'Journée sans match, on avance.': 'لا مباراة اليوم، نواصل التقدم.',
    'Journée simulée automatiquement.': 'تمت محاكاة الجولة تلقائيًا.',
    'La saison est terminée !': 'انتهى الموسم!',
    'Sans recruteur : estimation approximative': 'دون كشّاف: تقدير تقريبي',

    // ── نوافذ ثانوية (الكرات الثابتة، ملف الفريق) ─────────────────────────
    'Prêt': 'إعارة',
    'Conseillé': 'موصى به',
    'forme': 'اللياقة',
    'Aptitude': 'الكفاءة',
    'Choix automatique': 'اختيار تلقائي',
    "Aujourd'hui :": 'اليوم:',
    'Aucun joueur disponible': 'لا يوجد لاعب متاح',
    'Le sang-froid sur onze mètres': 'برود الأعصاب من مسافة 11 مترًا',
    'La frappe par-dessus le mur': 'التسديدة فوق الحائط',
    'Le pied qui trouve la tête': 'القدم التي تجد الرأس',
    'Le patron dans le vestiaire': 'زعيم غرفة الملابس',
    'Celui par qui le jeu doit passer': 'من يجب أن تمر اللعبة عبره',

    // ── ملف اللاعب التفصيلي ───────────────────────────────────────────────
    'Réserve': 'الاحتياط',
    'Matchs': 'المباريات',
    'Né le': 'تاريخ الميلاد',
    'Pot.': 'الإمكانات',
    'Buts': 'الأهداف',
    'Passes': 'التمريرات الحاسمة',
    'Statistiques': 'الإحصائيات',
    'Total carrière': 'إجمالي المسيرة',
    'saison': 'موسم',
    'Historique saison par saison': 'السجل موسمًا بموسم',

    // ── تكملة أخيرة: إشعارات مؤكد نقصها ───────────────────────────────────
    'Achat non abouti.': 'لم تكتمل عملية الشراء.',
    'Attention : aucun gardien dans votre onze de départ !': 'تنبيه: لا يوجد حارس مرمى في تشكيلتك الأساسية!',
    'Aucun joueur à révéler sur le marché.': 'لا يوجد لاعب لكشفه في السوق.',
    'Budget insuffisant !': 'الميزانية غير كافية!',
    'Ce joueur est déjà en prêt.': 'هذا اللاعب معار بالفعل.',
    'Ce joueur est emprunté : vous ne pouvez pas le vendre.': 'هذا اللاعب مُعار: لا يمكنك بيعه.',
    'Connectez-vous pour comparer votre carrière à celle des autres managers.': 'سجّل الدخول لمقارنة مسيرتك بمديرين آخرين.',
    'Déjà en parfait état.': 'في حالة ممتازة بالفعل.',
    'Fonds insuffisants pour ce transfert.': 'أموال غير كافية لهذا الانتقال.',
    'Fonds insuffisants pour envoyer un recruteur.': 'أموال غير كافية لإرسال كشّاف.',
    'Les trophées seront décernés à la fin de la saison.': 'ستُمنح الجوائز في نهاية الموسم.',
    'Membre du staff licencié.': 'تم إقالة عضو من الطاقم.',
    'Niveau maximum atteint !': 'تم بلوغ المستوى الأقصى!',
    'Niveau maximum déjà atteint.': 'تم بلوغ المستوى الأقصى بالفعل.',
    'Offre déclinée.': 'تم رفض العرض.',
    'Tenue changée.': 'تم تغيير الزي.',
    'Trois nouveaux objectifs tirés.': 'تم سحب ثلاثة أهداف جديدة.',
    'Vérification des achats en cours...': 'جارٍ التحقق من المشتريات...',

    // ── مفاتيح ناقصة تم اكتشافها بالتدقيق ─────────────────────────────────
    'Bon offert': 'جلسة مجانية',
    'Comprendre la boutique': 'فهم المتجر',
    'Conférence de presse': 'مؤتمر صحفي',
    'Forme': 'اللياقة',
    'Kiné': 'علاج',
    'Lui parler': 'التحدث إليه',
    'Moral': 'المعنويات',
    'Pas de kiné au club': 'لا يوجد معالج في النادي',
    'Presse': 'الصحافة',
    'Prêté par': 'معار من',
    'Renouveler': 'تجديد',
    'Repos': 'راحة',
    'Séance faite': 'تمت الجلسة',
    'Tireur de corner': 'منفذ الركنيات',
    'Tireur de coup franc': 'منفذ الركلات الحرة',
    'Tireur de penalty': 'منفذ ركلات الجزاء',
    'Vendre': 'بيع',
    'séance(s)': 'جلسة/جلسات',

    // ── الواجهة الثابتة (index.html) ─────────────────────────────────────
    "1. Votre nom d'entraîneur": '1. اسم المدرب',
    '2. Votre allure': '2. مظهرك',
    '3. Choisissez une Ligue': '3. اختر دوريًا',
    '4. Choisissez votre Club': '4. اختر ناديك',
    'Actualités': 'الأخبار',
    'Alchimie du groupe': 'انسجام الفريق',
    'B/M': 'هدف/مباراة',
    'Banc': 'دكة البدلاء',
    'Boîte de réception': 'صندوق الوارد',
    'Budget': 'الميزانية',
    'Calcul de tous les matchs du continent africain': 'جارٍ حساب كل مباريات القارة الأفريقية',
    'Choisissez le club africain que vous allez diriger vers les sommets.': 'اختر النادي الأفريقي الذي ستقوده إلى القمة.',
    'Classement': 'الترتيب',
    'Composition': 'التشكيلة',
    'Confiance du conseil': 'ثقة الإدارة',
    'Consignes': 'التعليمات',
    'Contre-Attaque': 'الهجوم المرتد',
    'Diff. niveau': 'فارق المستوى',
    'Discours de motivation': 'خطاب تحفيزي',
    'Défense Absolue': 'دفاع مطلق',
    'Forme dom.': 'اللياقة (الديار)',
    'Forme ext.': 'اللياقة (خارج الديار)',
    'Forme récente': 'الأداء الأخير',
    'Glissez un joueur sur un autre, ou touchez-en deux': 'اسحب لاعبًا فوق آخر، أو انقر على اثنين',
    'Humeur du vestiaire': 'أجواء غرفة الملابس',
    'Jeu Direct': 'اللعب المباشر',
    'Lancer le match 2D': 'ابدأ المباراة ثنائية الأبعاد',
    'Les news apparaissent ici…': 'ستظهر الأخبار هنا…',
    'Manière de jouer': 'أسلوب اللعب',
    'Mercato & Détection': 'الانتقالات والكشافة',
    'Notes': 'التقييمات',
    'Nouveau Contrat': 'عقد جديد',
    'Objectifs saison': 'أهداف الموسم',
    'Passer': 'تخطٍّ',
    'Points': 'النقاط',
    'Position': 'المركز',
    'Prochain match': 'المباراة القادمة',
    'Recruteur (500 K€)': 'كشّاف (500 ألف يورو)',
    'Remplacements': 'التبديلات',
    'Renforcez votre effectif. Fonds disponibles :': 'عزّز تشكيلتك. الأموال المتاحة:',
    'Réservistes': 'الاحتياطيون',
    'Rôles': 'الأدوار',
    'Signer le contrat': 'توقيع العقد',
    'Simulation en cours...': 'جارٍ المحاكاة...',
    'Stats': 'الإحصائيات',
    'Style': 'الأسلوب',
    'TEMPS FORT': 'لقطة بارزة',
    'Tenue': 'الزي',
    'Tireurs &amp; capitaine': 'المنفذون والقائد',
    'Ultra Offensive': 'هجومي جدًا',
    'VS': 'ضد',
    'Visage': 'الوجه',
    'Voir les résultats de la journée': 'عرض نتائج الجولة',
    'XI de départ': 'التشكيلة الأساسية',
    '⚠️ Effacer ma partie et recommencer': '⚠️ حذف لعبتي والبدء من جديد',
    'Échanger avec…': 'بدّل مع…',
    'joueur': 'لاعب',
    'joueurs': 'لاعبين',

    'Zone de danger': 'منطقة الخطر',
    'Efface définitivement votre carrière : effectif, palmarès, budget et progression. Cette action est irréversible.': 'يمسح مسيرتك نهائيًا: التشكيلة، الألقاب، الميزانية والتقدم. لا يمكن التراجع عن هذا الإجراء.',
    'Effacer ma partie et recommencer': 'حذف لعبتي والبدء من جديد',

    // ── أجزاء الواجهة (التدقيق النهائي) ───────────────────────────────────
    'Annuler (Reprendre)': 'إلغاء (استئناف)',
    'Aucun buteur': 'لا يوجد هداف',
    'Aucun club ne correspond.': 'لا يوجد نادٍ مطابق.',
    "Aucun de vos joueurs n'a été distingué cette saison. Les primes vont à leurs clubs.": 'لم يفز أي من لاعبيك بجائزة هذا الموسم. المكافآت تذهب إلى أنديتهم.',
    'Aucun joueur ne correspond.': 'لا يوجد لاعب مطابق.',
    'Aucune actualité': 'لا توجد أخبار',
    'Badges de profil': 'شارات الملف الشخصي',
    'Bilan de carrière': 'حصيلة المسيرة',
    'Carrière (CV)': 'المسيرة (السيرة الذاتية)',
    'Ce que conseille votre staff': 'ما ينصح به طاقمك',
    'Clubs + Joueurs': 'الأندية + اللاعبون',
    'Comment ils jouent': 'كيف يلعبون',
    "Confort uniquement — rien ici n'améliore vos joueurs.": 'للراحة فقط — لا شيء هنا يحسّن لاعبيك.',
    "Consulter les stats d'abord": 'الاطلاع على الإحصائيات أولاً',
    "Coup d'envoi": 'ركلة البداية',
    'Célébrations de but': 'احتفالات الأهداف',
    'Design actif :': 'التصميم النشط:',
    "Direction l'effectif": 'إلى التشكيلة',
    'Début de saison': 'بداية الموسم',
    'Démarrer la saison suivante': 'بدء الموسم التالي',
    'Effet des philosophies': 'تأثير الفلسفات',
    'Entretien': 'الصيانة',
    'Entretien individuel': 'حديث فردي',
    'Garde-robe du manager': 'خزانة ملابس المدير',
    'Gemmes': 'الجواهر',
    'Grande Finale': 'النهائي الكبير',
    'Installations': 'المنشآت',
    "Jusqu'à minuit": 'حتى منتصف الليل',
    'Le palmarès individuel se remplira à la fin de votre première saison.': 'ستظهر الجوائز الفردية في نهاية موسمك الأول.',
    'Les hommes à surveiller': 'اللاعبون الواجب مراقبتهم',
    'Maillots du club': 'أقمصة النادي',
    'Meilleurs Buteurs': 'أفضل الهدافين',
    'Meilleurs Passeurs': 'أفضل صناع الأهداف',
    'Mi-temps': 'بين الشوطين',
    'Note': 'التقييم',
    'Notes du match': 'تقييمات المباراة',
    'Nouveaux joueurs confirmés': 'لاعبون مؤكدون جدد',
    'Offre limitée': 'عرض محدود',
    'Palier atteint': 'تم بلوغ المستوى',
    'Pas encore de buteur en Ligue Elite Africaine.': 'لا يوجد هداف بعد في الدوري الأفريقي النخبوي.',
    'Pas encore de passeur en Ligue Elite Africaine.': 'لا توجد تمريرة حاسمة بعد في الدوري الأفريقي النخبوي.',
    'Porté': 'مرتدى',
    'Poste': 'المركز',
    "Purement financier — aucune installation n'apporte le moindre avantage sportif.": 'مالي بحت — لا توفر أي منشأة أي أفضلية رياضية.',
    "Purement visuel — aucun stade n'apporte le moindre avantage sportif.": 'بصري بحت — لا يوفر أي ملعب أي أفضلية رياضية.',
    'Repartent en fin de saison': 'يعودون في نهاية الموسم',
    'Retour automatique en fin de saison': 'عودة تلقائية في نهاية الموسم',
    'Récupérer les 80 crédits du jour': 'استلام 80 رصيدًا اليوم',
    'Stades': 'الملاعب',
    'Tapez un nom, ou choisissez un poste / OVR / âge pour lister des joueurs.': 'اكتب اسمًا، أو اختر مركزًا / تقييمًا / عمرًا لعرض اللاعبين.',
    'Trajectoire': 'المسار',
    'Utiliser': 'استخدام',
    'Vidéos bonus': 'فيديوهات إضافية',
    "Voir l'effectif": 'عرض التشكيلة',
    'Votre club': 'ناديك',
    'Votre club termine à la': 'ناديك ينهي الموسم في',
    'note moyenne': 'متوسط التقييم',
    'possession': 'الاستحواذ',
    'tirs': 'تسديدات',

    'Active': 'مفعّل',
    'Campus': 'الحرم',
    'Clubs': 'الأندية',
    'Défense →': 'الدفاع ←',
    'Effectif': 'التشكيلة',
    'Entre': 'يدخل',
    'Force': 'القوة',
    'Ils ont raccroché': 'اعتزلوا',
    'Notes indisponibles pour ce match.': 'التقييمات غير متاحة لهذه المباراة.',
    'Notes provisoires : le poids du résultat monte à mesure que le match avance.': 'تقييمات مؤقتة: يزداد وزن النتيجة كلما تقدمت المباراة.',
    'Offre Flash': 'عرض خاطف',
    'Sort': 'يخرج',
    'Tous': 'الكل',
    "d'énergie": 'من الطاقة',
    'e place': 'المركز',
    'en bas': 'في الأسفل',
    'obtenu.': 'المُحقق.',
    'temps de jeu réel': 'وقت اللعب الفعلي',
    '· moyenne': '· المتوسط',
    '← Attaque': '→ الهجوم',
    '↩ Rappeler': '↩ استدعاء',
};
