// ═══════════════════════════════════════════════════════════════════════════
// TRANSLATION — ENGLISH
// Grouped under window.I18N_EN, loaded BEFORE app.js (see index.html), which
// then assembles the three language files into the I18N registry.
// Any key missing here falls back to French (see lang-fr.js / t() in app.js).
// ═══════════════════════════════════════════════════════════════════════════
window.I18N_EN = {
    'app.subtitle': 'Manager',
    'nav.dashboard': 'Dashboard',
    'nav.squad': 'Squad',
    'nav.tactics': 'Tactics',
    'nav.market': 'Transfers',
    'nav.staff': 'Staff',
    'nav.standings': 'Standings',
    'nav.awards': 'Awards',
    'nav.shop': 'Shop',
    'nav.campus': 'Campus',
    'nav.home_mobile': 'Home',
    'nav.more': 'More',
    'nav.profile': 'Profile',
    'nav.reset': 'Reset',
    'screen.tactics': 'Tactics Office',
    'screen.standings': 'Standings',
    'screen.squad': 'Pro Squad',
    'screen.squad_sub': 'Your players currently under contract.',

    // ── PASSE 1 : DONNÉES DE JEU ─────────────────────────────────────────
    // Staff
    'Entraîneur Adjoint': 'Assistant Coach',
    'Bonus Tactique': 'Tactical Bonus',
    'Kiné Chef': 'Head Physio',
    'Récupération': 'Recovery',
    'Recruteur Chef': 'Head Scout',
    'Précision scouting': 'Scouting Accuracy',
    'Médecin du Sport': 'Sports Doctor',
    'Risque blessure': 'Injury Risk',
    'Manager des Jeunes': 'Youth Manager',
    'Progression académie': 'Academy Progress',

    // Tenues du manager
    'Costume Marine, cravate': 'Navy Suit, Tie',
    'Costume Noir, cravate': 'Black Suit, Tie',
    'Gris moderne, col ouvert': 'Modern Grey, Open Collar',
    'Bordeaux élégant, cravate': 'Elegant Maroon, Tie',
    'Vert olive, décontracté': 'Olive Green, Casual',
    'Ivoire, cravate dorée': 'Ivory, Gold Tie',
    'Sable, col mao': 'Sand, Mandarin Collar',
    'Bleu nuit, pochette rouge': 'Midnight Blue, Red Pocket Square',
    'Anthracite, boutons dorés': 'Charcoal, Gold Buttons',
    'Prestige, revers ivoire': 'Prestige, Ivory Lapel',

    // Boutique de crédits (confort/cosmétique)
    'Relancer les objectifs': 'Reroll Objectives',
    "Tire trois nouveaux objectifs hebdomadaires.": "Draws three new weekly objectives.",
    'Révéler un joueur': 'Reveal a Player',
    "Dévoile les statistiques d'un joueur non supervisé du marché.": "Reveals the stats of an unscouted market player.",
    'Tenue Ivoire': 'Ivory Suit',
    "Costume ivoire, cravate dorée.": "Ivory suit, gold tie.",
    'Tenue Sable': 'Sand Suit',
    "Costume sable, col mao.": "Sand suit, mandarin collar.",
    'Tenue Bleu nuit': 'Midnight Blue Suit',
    "Bleu nuit, pochette rouge.": "Midnight blue, red pocket square.",
    'Tenue Or': 'Gold Suit',
    "Costume anthracite, boutons dorés.": "Charcoal suit, gold buttons.",
    'Portée': 'Worn',
    'Porter': 'Wear',

    // Objectifs hebdomadaires
    'Gagner 2 matchs': 'Win 2 matches',
    'Marquer 5 buts': 'Score 5 goals',
    'Garder 1 cage inviolée': 'Keep 1 clean sheet',
    'Gagner 3 points de stat': 'Gain 3 stat points',
    'Rester 3 matchs invaincu': 'Go unbeaten in 3 matches',
    'Un joueur noté 8.0 ou plus': 'A player rated 8.0 or higher',
    'Objectif rempli': 'Objective completed',
    'crédits': 'credits',

    // Maillots du club
    'Historique': 'Classic',
    'Rayé': 'Striped',
    'Cerclé': 'Hooped',
    'Écharpe': 'Sash',
    'Or & Nuit': 'Gold & Night',
    'Flamme': 'Flame',

    // Stades
    'Terre Battue': 'Dusty Pitch',
    "Le terrain d'origine du club — poussiéreux mais chaleureux.": "The club's original ground — dusty but full of heart.",
    'Tribune Populaire': 'Popular Stand',
    "Des tribunes qui se remplissent, une ambiance qui monte.": "Stands filling up, atmosphere rising.",
    'Arène Moderne': 'Modern Arena',
    "Béton et acier — un stade aux normes continentales.": "Concrete and steel — a stadium built to continental standards.",
    'Nocturne': 'Night Match',
    "Sous les projecteurs — l'ambiance électrique des matchs en soirée.": "Under the floodlights — the electric feel of evening matches.",
    'Nocturne Doré': 'Golden Night',
    "La même nuit électrique, habillée d'or — exclusif.": "The same electric night, dressed in gold — exclusive.",
    'Arène Continentale': 'Continental Arena',
    "Le décor des grands soirs de CAF — bleu et lumière.": "The backdrop of big CAF nights — blue and light.",
    'Jour de Finale': 'Final Day',
    "Feux d'artifice et confettis — le stade d'un soir de sacre.": "Fireworks and confetti — the stadium on a night of glory.",

    // Célébrations de but
    'Classique': 'Classic',
    'Sprint au coin': 'Corner Sprint',
    'Glissade': 'Knee Slide',
    'Virage en fusion': 'Stand on Fire',
    "Feu d'artifice": 'Fireworks',
    'Statut de légende': 'Legend Status',
    'Nuit continentale': 'Continental Night',
    'Roue de la Fortune': 'Wheel of Fortune',
    'Tour gratuit du jour': "Today's Free Spin",

    // Badges de profil
    'Aucun': 'None',
    'Sur le banc': 'On the Bench',
    'Tacticien': 'Tactician',
    'Bâtisseur': 'Builder',
    'Gagneur': 'Winner',
    'Légende': 'Legend',
    'Icône continentale': 'Continental Icon',

    // Campus
    'Tribunes agrandies': 'Expanded Stands',
    "Plus de places disponibles à domicile — hausse directe du plafond de billetterie.": "More seats at home — a direct boost to your ticketing cap.",
    'Boutique du Club': 'Club Store',
    "Maillots et produits dérivés — un revenu fixe supplémentaire à chaque match.": "Shirts and merchandise — extra fixed income every match.",
    'Espace VIP': 'VIP Lounge',
    "Loges premium pour sponsors et invités — revenu de prestige à chaque match.": "Premium boxes for sponsors and guests — prestige income every match.",
    'Chaudron & Ambiance': 'Cauldron & Atmosphere',
    "Un stade qui vibre attire plus de monde — billetterie additionnelle à domicile.": "A buzzing stadium draws bigger crowds — extra home ticketing.",
    'Écran Géant': 'Giant Screen',
    "Purement visuel — l'ambiance du jour de match, sans effet sur les recettes.": "Purely visual — matchday atmosphere, no effect on revenue.",

    // Trophées de fin de saison
    "Ballon d'Or Africain": "African Ballon d'Or",
    "Le meilleur joueur du continent, tous postes confondus.": "The continent's best player, across all positions.",
    "Soulier d'Or Africain": "African Golden Boot",
    "Le plus grand buteur des 10 championnats.": "The top scorer across all 10 leagues.",
    "Meilleur Passeur Africain": "African Playmaker of the Year",
    "Le maître à jouer de la saison.": "The season's midfield maestro.",
    "Gant d'Or Africain": "African Golden Glove",
    "Le gardien le plus infranchissable.": "The most impenetrable goalkeeper.",
    "Meilleur Espoir Africain": "African Young Player of the Year",
    "Le meilleur joueur de 21 ans ou moins.": "The best player aged 21 or under.",
    "Meilleur buteur du championnat": "League Top Scorer",
    "Le canonnier de votre championnat.": "The sharpshooter of your league.",
    'Non attribué cette saison': 'Not awarded this season',
    'm. joués': 'apps',
    'passes déc.': 'assists',
    'buts': 'goals',
    'passes': 'assists',
    'Prime sponsors': 'Sponsor bonus',
    'Prime versée à': 'Bonus paid to',

    // ── PASSE 2 : BOUTIQUE + CAMPUS ──────────────────────────────────────
    'Poignée de crédits': 'Handful of Credits',
    'Sac de crédits': 'Bag of Credits',
    'Coffre de crédits': 'Chest of Credits',
    'Édition Manager': 'Manager Edition',
    "Retire les publicités imposées, offre 1000 crédits, la tenue Or exclusive et un second emplacement de carrière.": "Removes forced ads, grants 1000 credits, the exclusive Gold suit and a second career slot.",
    "Débloque la piste Prestige du pass en cours : cosmétiques exclusifs et crédits à chaque palier.": "Unlocks the Prestige track of the current pass: exclusive cosmetics and credits at every tier.",
    'Offre de bienvenue': 'Welcome Offer',
    "1200 crédits, 150 gemmes, la tenue Ivoire et un Pack Découverte (1 joueur confirmé) offerts. Réservée à votre première saison.": "1200 credits, 150 gems, the Ivory suit and a free Discovery Pack (1 confirmed player). First-season only.",
    'Abonnement VIP': 'VIP Subscription',
    "80 crédits chaque jour, 60 gemmes à chaque renouvellement, publicités imposées retirées, badge VIP. Reconduction automatique chaque mois à 2,49 € jusqu'à résiliation — résiliable à tout moment depuis le Play Store.": "80 credits every day, 60 gems on every renewal, forced ads removed, VIP badge. Auto-renews monthly at €2.49 until cancelled — cancel anytime from the Play Store.",
    'Sachet de gemmes': 'Small Gem Pouch',
    'Bourse de gemmes': 'Gem Purse',
    'Coffre de gemmes': 'Gem Chest',
    'Pack Découverte': 'Discovery Pack',
    "1 joueur confirmé (80-85), immédiatement dans l'effectif.": "1 confirmed player (80-85), added to your squad instantly.",
    'Pack Talents': 'Talent Pack',
    "3 joueurs confirmés (80-88) en un seul tirage.": "3 confirmed players (80-88) in one draw.",
    'Pack Génération': 'Generation Pack',
    "6 joueurs confirmés (83-92) — un effectif de stars d'un coup.": "6 confirmed players (83-92) — a squad of stars in one go.",
    '80 crédits': '80 credits',
    '220 crédits': '220 credits',
    '20 gemmes': '20 gems',
    '50 gemmes': '50 gems',
    'Révélation gratuite': 'Free Reveal',
    'Pack Découverte offert': 'Free Discovery Pack',
    'Jackpot — 180 gemmes': 'Jackpot — 180 gems',
    'Populaire': 'Popular',
    'Meilleure valeur': 'Best Value',
    'Une fois': 'One-time',
    'Restaurer': 'Restore',
    'Actif': 'Active',
    'Tourner': 'Spin',
    'gemmes': 'gems',

    // ── PASSE 3 : ÉCRANS DE JEU (débuts) ─────────────────────────────────
    'Exige un transfert': 'Demands a transfer',
    'Transfert': 'Transfer',
    'Réclame du temps de jeu': 'Wants more playing time',
    'Frustré': 'Frustrated',
    'Refuser': 'Decline',
    'Récupérer': 'Claim',
    'Prêter': 'Loan',
    'Fermer': 'Close',
    'Accepter': 'Accept',
    'Valider': 'Confirm',
    'Tout auto': 'Auto-fill',
    'Reprendre le match': 'Resume Match',
    'Rencontrer': 'Meet',
    'Mon club': 'My Club',
    'Licencier': 'Dismiss',
    'Ignorer': 'Dismiss',
    'Décliner': 'Decline',
    'Compositions': 'Line-ups',
    'Annuler': 'Cancel',
    'Afrique': 'Africa',

    // ── PASSE 3 (suite) : Mercato, Académie, Staff ───────────────────────
    'Tous postes': 'All positions',
    'Tous prix': 'All prices',
    'Tout niveau': 'All ratings',
    'Rafraîchir les agents libres': 'Refresh free agents',
    'Infrastructures': 'Facilities',
    'Niv. Max Atteint': 'Max Level Reached',
    'Améliorer': 'Upgrade',
    'Débutant': 'Rookie',
    'Confirmé': 'Seasoned',
    'Expérimenté': 'Experienced',
    'Réputé': 'Renowned',
    'Élite': 'Elite',
    'ans': 'y/o',

    // ── PASSE 4 : NOTIFICATIONS, BOÎTE DE RÉCEPTION, INTERVIEWS ──────────
    'Aucun message': 'No messages',
    'Offre reçue': 'Offer received',
    'Recrutement': 'Signing',
    'Demande de prêt': 'Loan request',
    'Proposition': 'Offer',
    'Alerte': 'Alert',
    'Contrat': 'Contract',
    'Vestiaire': 'Dressing Room',
    'Palier': 'Tier',
    'Distinction': 'Award',
    'Objectif': 'Objective',
    'Quotidien': 'Daily',
    'Info': 'News',
    'Bonus': 'Bonus',
    'Une réaction ?': 'Any reaction?',
    'Le défendre publiquement': 'Defend him publicly',
    'Prendre ses distances': 'Distance yourself',
    'Ne pas réagir': "Don't react",
    'Le féliciter publiquement': 'Praise him publicly',
    'Recentrer sur le collectif': 'Refocus on the team',
    'Rester factuel': 'Stay factual',

    // ── PASSE 4 (suite) : COMMENTAIRES DE MATCH EN DIRECT ────────────────
    "L'arbitre siffle le coup d'envoi. C'est parti !": "The referee blows the whistle. Kick-off!",
    "Mi-temps. Les équipes rentrent aux vestiaires.": "Half-time. The teams head to the dressing rooms.",
    "Fin de la première période de prolongation.": "End of the first period of extra time.",
    "Fin du temps réglementaire.": "End of regulation time.",
    "Coup de sifflet final !": "Full time!",
    "PENALTY sifflé pour": "PENALTY awarded to",
    "place le ballon sur le point.": "places the ball on the spot.",
    "Corner pour": "Corner for",
    "Coup franc dangereux pour": "Dangerous free kick for",
    "se charge du ballon.": "steps up to take it.",
    "EXPULSION !": "SENT OFF!",
    "voit son 2e carton jaune !": "picks up a second yellow card!",
    "Faute tactique. Carton jaune pour": "Tactical foul. Yellow card for",
    "CARTON ROUGE DIRECT !": "STRAIGHT RED CARD!",
    "Faute grossière de": "A reckless foul from",
    "BLESSURE !": "INJURY!",
    "est touché": "is down injured",
    "Son énergie s'effondre, remplacez-le vite !": "His energy is collapsing, sub him off quickly!",
    "Changement :": "Substitution:",
    "remplace": "replaces",
    "sorti sur blessure.": "who went off injured.",
    "Coup dur pour l'adversaire :": "Tough break for the opposition:",
    "sort sur civière et l'équipe n'a plus de remplaçant !": "is stretchered off and the team has no substitutes left!",
    "Action fulgurante de": "A lightning move from",
    "La défense de": "The defense of",
    "repousse le danger.": "clears the danger.",

    // ── PASSE 6 : commentaires de match (suite) ───────────────────────────
    "Toujours rien pour départager les deux clubs — on joue la prolongation (2 × 15 min).": "Still nothing to separate the two sides — on to extra time (2 × 15 min).",
    "Prolongation ! Un 6e remplacement vous est accordé.": "Extra time! You're granted a 6th substitution.",
    "minute(s) de temps additionnel.": "minute(s) of added time.",
    "Séance de tirs au but :": "Penalty shootout:",
    "se qualifie !": "goes through!",
    "Changement tactique pour l'adversaire.": "Tactical change for the opposition.",

    // ── PASSE 7 : commentaires de but ────────────────────────────────────
    'BUT !': 'GOAL!',
    'sert': 'sets up',
    'qui conclut en beauté !': 'who finishes in style!',
    'Quelle passe de': 'What a pass from',
    'ne pouvait pas rater !': 'couldn\'t miss that!',
    'Superbe centre de': 'A superb cross from',
    'pour': 'for',
    'BUT SUR PENALTY !': 'GOAL FROM THE SPOT!',
    'transforme avec sang-froid !': 'converts ice-cold!',
    'COUP FRANC DIRECT !': 'DIRECT FREE KICK!',
    'enroule par-dessus le mur !': 'curls it over the wall!',
    'BUT EXCEPTIONNEL !': 'STUNNING GOAL!',
    'Frappe de': 'A strike from',
    'à': 'from',
    'mètres': 'meters out',
    'place parfaitement son tir': 'places his shot perfectly',
    'à bout portant': 'from point-blank range',
    'INCROYABLE RATÉ !': 'UNBELIEVABLE MISS!',
    'était seul face au but !': 'was clean through on goal!',
    'ARRÊT MIRACULEUX !': 'MIRACLE SAVE!',
    'Le gardien sauve son équipe face à': 'The keeper bails his team out against',
    'Frappe lointaine de': 'A long-range effort from',
    'qui passe loin du cadre.': 'flies well wide.',
    'Tir dans un angle fermé de': 'A tight-angle shot from',
    'capté tranquillement par le gardien.': 'comfortably held by the keeper.',
    'Bel arrêt du gardien sur cette frappe de': 'A fine save by the keeper from',
    'dévisse légèrement son tir.': 'scuffs his shot slightly.',
    'La défense se jette et contre la frappe de': 'The defense throws itself in and blocks the shot from',

    // ── PASSE 8 : écran CAF ──────────────────────────────────────────────
    "Votre club n'est pas qualifié cette saison — terminez": "Your club isn't qualified this season — finish",
    'Top 2': 'Top 2',
    'de votre championnat pour participer.': 'of your league to take part.',
    'Votre club est éliminé': 'Your club has been eliminated',
    'Sorti en': 'Eliminated in the',
    'Phase de groupes': 'Group Stage',
    'Demi-finale': 'Semi-final',
    'vous pouvez suivre la suite de la compétition en spectateur.': 'you can follow the rest of the competition as a spectator.',
    "Champion d'Afrique": 'Champion of Africa',
    'GROUPE': 'GROUP',
    'Votre groupe': 'Your Group',
    'Club': 'Club',
    'V': 'W',
    'N': 'D',
    'D': 'L',
    'Pts': 'Pts',
    'Quarts de finale': 'Quarter-finals',
    'Aller': 'Leg 1',
    'Retour': 'Leg 2',
    'Finale': 'Final',

    // ── PASSE 9 : Classements + causeries de mi-temps ────────────────────
    'j': 'gp',
    'Rester calme': 'Stay Calm',
    "On ne change rien, on continue.": "No changes, we carry on.",
    'Encourager': 'Encourage',
    "Vous leur dites votre confiance.": "You tell them you believe in them.",
    'Secouer': 'Shake Them Up',
    "Le ton monte dans le vestiaire.": "Voices are raised in the dressing room.",
    'Exiger le bloc': 'Demand Discipline',
    "Consignes serrées, on verrouille.": "Tight instructions, lock it down.",
    "Vous menez à la pause. Le vestiaire est chaud.": "You're leading at the break. The dressing room is buzzing.",
    "Vous êtes menés. Onze paires d'yeux vous regardent.": "You're trailing. Eleven pairs of eyes are on you.",
    "Tout reste à faire. Le match se joue maintenant.": "Everything's still to play for. The match is decided now.",

    // ── PASSE 9 (suite) : consignes tactiques ────────────────────────────
    "Couloir d'attaque": 'Attacking Channel',
    'Par où le jeu sort': 'Where play builds from',
    'Mixte': 'Mixed',
    'Axe': 'Through the Middle',
    'Deux ailes': 'Both Flanks',
    'Droite': 'Right',
    'Gauche': 'Left',
    'Pressing': 'Pressing',
    'Où on va chercher le ballon': 'Where you win the ball back',
    'Sa surface': 'Their Box',
    'Sa moitié': 'Their Half',
    'Tout terrain': 'Full Pitch',
    'Ligne défensive': 'Defensive Line',
    'La hauteur du bloc': 'How high the block sits',
    'Basse': 'Low',
    'Normale': 'Normal',
    'Haute': 'High',
    'Mentalité': 'Mentality',
    'Défensive': 'Defensive',
    'Équilibrée': 'Balanced',
    'Offensive': 'Offensive',
    'Style de jeu': 'Playing Style',
    'Possession': 'Possession',
    'Direct': 'Direct',
    'Contre': 'Counter',
    'Consignes en direct': 'Live Instructions',
    "Chaque changement s'applique immédiatement, sans arrêter le jeu.": "Every change applies instantly, without stopping play.",
    'Fermer': 'Close',
    'Formation': 'Formation',

    // ── Écran Paramètres ──────────────────────────────────────────────────
    'nav.settings': 'Settings',
    'Langue': 'Language',
    'Apparence': 'Appearance',
    'Sombre': 'Dark',
    'Clair': 'Light',
    'Le mode clair est encore en cours de finition sur certains écrans.': 'Light mode is still being polished on some screens.',
    'Ambiance sonore': 'Sound',
    'Revoir le tutoriel': 'Replay the Tutorial',
    'Revoir le tutoriel de la boutique': 'Replay the Shop Tutorial',

    // ── Négociations de transfert et contrats ────────────────────────────
    'Renouvellement de contrat': 'Contract Renewal',
    'OVR': 'OVR',
    'Salaire actuel :': 'Current wage:',
    'mois': 'month',
    'Nouveau salaire demandé :': 'Requested new wage:',
    'Durée :': 'Length:',
    'saisons': 'seasons',
    'Contrat de': 'Contract for',
    'renouvelé (2 saisons) !': 'renewed (2 seasons)!',
    'Prolonger': 'Extend',
    "Effectif complet (30 joueurs maximum).": "Squad full (30 players maximum).",
    'ne peut pas vendre': "can't sell",
    "il n'est chez eux qu'en prêt, il ne leur appartient pas.": "he's only on loan there, they don't own him.",
    'refuse de négocier.': 'refuses to negotiate.',
    'Leur effectif est déjà trop court': 'Their squad is already too thin',
    'joueurs': 'players',
    'pour se séparer de qui que ce soit.': 'to let anyone go.',
    'refuse net.': 'flatly refuses.',
    "est un pilier du club : il n'est pas à vendre, quel que soit le montant.": "is a key player: not for sale at any price.",
    'réclame': 'is asking',
    'pour': 'for',
    'Vos fonds :': 'Your funds:',
    'Il vous manque': "You're short by",
    'accepte de négocier': 'agrees to negotiate',
    'ans': 'y/o',
    'POT': 'POT',
    'Indemnité de transfert :': 'Transfer fee:',
    'Salaire réclamé :': 'Requested wage:',
    'Le club a besoin de liquidités : le prix est en dessous de sa valeur.': 'The club needs cash: the price is below market value.',
    "C'est un titulaire chez eux, d'où la majoration.": "He's a starter there, hence the markup.",
    'Fonds insuffisants.': 'Insufficient funds.',
    "Ce joueur n'est plus disponible.": 'This player is no longer available.',
    'rejoint': 'joins',
    'Signer': 'Sign',

    // ── Commentaires additionnels + demande de prêt ──────────────────────
    'CHANGEMENT TACTIQUE :': 'TACTICAL CHANGE:',
    'entre à la place de': 'comes on for',
    'Le groupe répond présent.': 'The squad responds well.',
    'Le message passe mal, les têtes se baissent.': "The message doesn't land, heads drop.",
    'Le groupe écoute sans broncher.': 'The squad listens without flinching.',
    'Causerie': 'Team Talk',
    'Consigne du banc': 'Touchline Instruction',
    'Maximum 4 joueurs empruntés simultanément.': 'Maximum 4 players on loan at once.',
    'est déjà en prêt à': 'is already on loan at',
    'il ne peut pas être re-prêté.': "he can't be loaned out again.",
    'refuse :': 'refuses:',
    'leur effectif': 'their squad',
    "est trop court pour se priver de quelqu'un.": "is too thin to let anyone go.",
    'refuse.': 'refuses.',
    'est titulaire chez eux': 'is a starter there',
    'e de la hiérarchie': 'th in the pecking order',
    "On ne prête pas un homme dont on a besoin le week-end.": "You don't loan out a player you need at the weekend.",
    'décline poliment.': 'politely declines.',
    'À OVR': 'At OVR',
    'vise plus haut que': 'is aiming higher than',
    'force': 'strength',
    "Renforcez d'abord la stature du club.": "Build up the club's stature first.",
    'Indemnité de prêt réclamée :': 'Loan fee requested:',
    'Vos fonds ne suffisent pas.': "Your funds aren't enough.",
    'accepte de vous prêter': 'agrees to loan you',
    'pour une saison.': 'for a season.',
    'Indemnité de prêt :': 'Loan fee:',
    'Salaire à votre charge :': 'Wage you cover:',
    'Il repartira automatiquement chez lui en fin de saison. Vous ne pourrez ni le vendre, ni le re-prêter.': "He'll automatically return home at season's end. You can't sell him or loan him out again.",

    // ── Conférences de presse (réponses courtes + citations) ────────────
    'Un pas à la fois': 'One step at a time',
    'On vise le trophée': "We're aiming for the trophy",
    'Féliciter les joueurs': 'Praise the players',
    'Relativiser': 'Keep perspective',
    'Reconnaître la déception': 'Admit the disappointment',
    "Blâmer l'arbitrage": 'Blame the officiating',
    'Regarder devant': 'Look ahead',
    'Revendiquer le travail': 'Claim credit for the work',
    'Rester humble': 'Stay humble',
    'Rassurer le groupe': 'Reassure the group',
    'Se remettre en cause': 'Question myself',
    'Hausser le ton': 'Raise the tone',
    'Ne rien changer': 'Change nothing',
    'Se projeter sur le titre': 'Look ahead to the title',
    'Prévenir un relâchement': 'Warn against complacency',
    'Journée après journée': 'Matchday by matchday',
    'Assumer le costume': 'Own the role',
    'Rejeter la pression': 'Dismiss the pressure',
    'Dédramatiser': 'Play it down',
    "Sonner l'alarme": 'Sound the alarm',
    'Rassurer la direction': 'Reassure the board',
    'Demander du temps': 'Ask for time',
    'Défier les critiques': 'Defy the critics',
    'Ne pas commenter': 'No comment',
    'Protéger le groupe': 'Protect the group',
    'Assumer seul': 'Take sole responsibility',
    'Pointer les manques': 'Point out the shortcomings',
    'Rester prudent': 'Stay cautious',
    "Assumer l'ambition": 'Own the ambition',
    'Créditer le groupe': 'Credit the group',
    "Les points d'abord": 'Points come first',
    'Reconnaître les limites': 'Acknowledge the limits',
    'Saluer le mental': 'Salute the mentality',
    'Féliciter la défense': 'Praise the defense',
    "Réclamer plus d'ambition": 'Demand more ambition',
    'Un point pris': 'A point gained',
    'Un point de trop perdu': 'A point too many dropped',
    'Rester neutre': 'Stay neutral',
    'Rester vague': 'Stay vague',
    'Annoncer une ambition': 'Announce an ambition',
    'Prôner la prudence': 'Advocate caution',
    "S'en réjouir ouvertement": 'Openly celebrate it',
    'Match après match': 'Match by match',
    'Viser plus haut': 'Aim higher',
    'Rester lucide': 'Stay level-headed',
    'On savoure ce soir, on repense au continent demain.': 'We enjoy tonight, we think continent tomorrow.',
    'On ne participe pas pour faire de la figuration. On y va pour le gagner.': "We're not here to make up the numbers. We're here to win it.",
    'Ce sont eux qui ont fait le travail sur le terrain, pas moi.': 'They did the work on the pitch, not me.',
    'Le championnat reste notre priorité. On tourne la page vite.': 'The league remains our priority. We turn the page quickly.',
    "C'est une désillusion. On visait plus loin, il faut le dire.": "It's a disappointment. We aimed further, let's be honest.",
    "Certaines décisions ont pesé lourd ce soir. Je ne suis pas le seul à l'avoir vu.": "Some decisions weighed heavily tonight. I'm not the only one who noticed.",
    'Les chiffres, on les comptera à la fin. Pas avant.': "We'll count the numbers at the end. Not before.",
    'Ce club a changé de visage depuis mon arrivée. Je le dis sans fausse modestie.': 'This club has changed face since I arrived. I say it without false modesty.',
    "Je ne suis qu'un maillon. Le club était là avant moi, il sera là après.": "I'm just one link. The club was here before me, it'll be here after.",
    "On va s'en sortir ensemble. Douter maintenant serait la pire erreur.": "We'll get through this together. Doubting now would be the worst mistake.",
    "Le premier responsable d'une série comme celle-là, c'est le coach. Je regarde ce que je peux changer.": "The person most responsible for a run like this is the coach. I'm looking at what I can change.",
    "Il y a un manque d'exigence individuelle. Ça doit changer, et vite.": "There's a lack of individual demands. That has to change, and fast.",
    "On garde les pieds sur terre et la même méthode. C'est elle qui paie.": "We keep our feet on the ground and the same method. It's what's paying off.",
    "À ce rythme, il n'y a aucune raison de se cacher sur nos ambitions.": "At this rate, there's no reason to hide our ambitions.",
    "Le vrai danger maintenant, c'est de croire qu'on a déjà gagné quelque chose.": "The real danger now is thinking we've already won something.",
    'On ne regarde pas le classement, seulement le prochain adversaire.': "We're not looking at the table, only the next opponent.",
    'On veut ce titre. Autant le dire clairement plutôt que de jouer la fausse humilité.': 'We want this title. Better to say it clearly than play false humility.',
    "La pression, c'est pour ceux qui n'ont rien à perdre. Nous, on joue libérés.": 'Pressure is for those with nothing to lose. We play free.',
    "On a les moyens de s'en sortir. Il faut juste rester soudés.": 'We have what it takes to get through this. We just need to stay united.',
    "La situation est grave. Ceux qui ne le comprennent pas n'ont rien à faire ici.": "The situation is serious. Those who don't understand that have no place here.",
    'Je prends mes responsabilités devant le club. On va se maintenir.': 'I take responsibility before the club. We will stay up.',
    'Un projet se juge sur une saison, pas sur trois journées.': 'A project is judged over a season, not three matchdays.',
    'Je fais mon travail. Ceux qui doutent jugeront au classement.': 'I do my job. Those who doubt will judge by the table.',
    'Je ne parle que de football.': 'I only talk about football.',
    "Personne ne lâche. Ces joueurs se battent, je réponds d'eux.": 'Nobody gives up. These players fight, I vouch for them.',
    "L'équipe a fait le travail. Le choix tactique était le mien, l'erreur aussi.": 'The team did the work. The tactical choice was mine, and so was the mistake.',
    "Certains n'ont pas le niveau exigé ici. Ils le savent.": "Some don't have the level required here. They know it.",
    'Un match ne fait pas une saison. On regarde le suivant.': "One match doesn't make a season. We look at the next one.",
    "On joue pour gagner, et de la meilleure des manières. Pourquoi s'en cacher ?": 'We play to win, and in the best possible way. Why hide it?',
    'Ce sont eux sur le terrain. Tout leur revient.': "It's them out on the pitch. It's all down to them.",
    'Trois points restent trois points, quelle que soit la manière.': 'Three points are three points, no matter how you get them.',
    "On sait qu'il y a du travail. Cette victoire ne doit pas masquer ça.": "We know there's work to do. This win shouldn't hide that.",
    "Ce groupe ne lâche jamais. C'est ce qui a fait la différence.": "This group never gives up. That's what made the difference.",
    "C'est un travail collectif, du gardien jusqu'aux attaquants qui défendent en premier.": "It's a collective effort, from the keeper to the forwards defending first.",
    "Bien défendre, c'est un point de départ. Il faut aussi être dangereux devant.": 'Defending well is a starting point. We also need to be dangerous up front.',
    'On a fait le nécessaire. Rien de plus à ajouter.': 'We did what was needed. Nothing more to add.',
    'Face à cet adversaire, ce point est plutôt bon à prendre.': 'Against this opponent, this point is a good one to take.',
    "On avait les moyens de gagner ce soir. C'est deux points de perdus, pas un de pris.": "We had what it took to win tonight. That's two points dropped, not one gained.",
    'Un résultat logique au vu de la physionomie du match.': 'A logical result given how the match unfolded.',
    "On construit match après match, sans se fixer de chiffre à l'avance.": 'We build match by match, without setting a number in advance.',
    'Ce club a les moyens de viser le haut du tableau cette saison. Je le dis dès maintenant.': "This club has what it takes to aim for the top of the table this season. I'm saying it now.",
    "Il faut d'abord poser des bases solides. Les ambitions viendront ensuite.": 'We need to lay solid foundations first. The ambitions will come after.',
    'La saison est encore longue. On ne regarde pas trop loin.': "The season is still long. We're not looking too far ahead.",
    "Ce classement, on l'a mérité. Pas de raison de bouder son plaisir.": 'We earned this table position. No reason to hold back our joy.',
    'Cette place doit nous donner faim, pas nous satisfaire.': 'This position should make us hungry, not satisfied.',
    'On avance sans regarder trop loin.': 'We move forward without looking too far ahead.',
    'Ce groupe peut aller chercher davantage.': 'This group can achieve more.',
    "Nos moyens sont ce qu'ils sont. On fait avec.": 'Our resources are what they are. We work with them.',

    // ── Questions de conférence de presse ─────────────────────────────────
    'Qualification continentale face à': 'Continental qualification against',
    "L'Afrique, ce n'est plus un rêve ?": 'Is Africa no longer just a dream?',
    'Élimination continentale contre': 'Continental elimination against',
    'Un échec pour le projet ?': 'A failure for the project?',
    'Un cap symbolique de matchs à la tête du club. Un bilan ?': 'A symbolic number of matches in charge. Any assessment?',
    "Troisième défaite d'affilée. La spirale négative vous inquiète-t-elle ?": 'Third straight defeat. Does the negative spiral worry you?',
    "Cinquième match sans défaite. Cette équipe a-t-elle changé de dimension ?": 'Fifth match unbeaten. Has this team stepped up a level?',
    'À quelques journées de la fin, vous jouez le titre. La pression monte-t-elle ?': "With a few matchdays left, you're in the title race. Is the pressure building?",
    'Le club est empêtré dans la lutte pour le maintien. Le discours a-t-il changé dans le vestiaire ?': "The club is stuck in a relegation battle. Has the message changed in the dressing room?",
    'Votre poste est ouvertement discuté. Un message à la direction ?': 'Your job is openly being questioned. Any message for the board?',
    'Nouveau revers face à': 'Another setback against',
    'Le vestiaire vous échappe-t-il ?': 'Is the dressing room slipping away from you?',
    'Une démonstration face à': 'A statement performance against',
    'Le plus beau match de la saison ?': 'The best match of the season?',
    'Victoire courte mais précieuse contre': 'A narrow but precious win against',
    'La manière compte-t-elle vraiment ?': 'Does the manner of victory really matter?',
    'Une cage inviolée de plus face à': 'Another clean sheet against',
    'Le socle défensif du club ?': "The club's defensive foundation?",
    'Match nul concédé face à': 'A draw conceded against',
    'Un point perdu ou un point pris ?': 'A point dropped or a point gained?',
    'Encore tôt dans la saison. Quels objectifs vous fixez-vous pour cet exercice ?': 'Still early in the season. What targets are you setting for this campaign?',
    'Le club pointe à la': 'The club sits in',
    'ᵉ place. Une saison qui prend une belle tournure ?': ' place. Is the season taking a good turn?',
    'Comment abordez-vous la suite du championnat,': 'How are you approaching the rest of the season, currently',
    'ᵉ au classement ?': ' in the table?',

    // ── Rapport d'avant-match (style adverse) ────────────────────────────
    'Garde le ballon et construit patiemment.': 'Keeps the ball and builds patiently.',
    "Joue vers l'avant dès que possible, beaucoup de ballons longs.": 'Plays forward as soon as possible, lots of long balls.',
    'Laisse le ballon et frappe en transition.': 'Cedes the ball and strikes on the counter.',
    'Bloc bas, presse seulement dans sa surface.': 'Low block, only presses in its own box.',
    'Bloc médian.': 'Mid block.',
    'Presse haut, sur tout le terrain.': 'Presses high, across the whole pitch.',
    "Défense basse — l'espace est devant, pas derrière.": 'Deep defense — the space is in front, not behind.',
    'Ligne médiane.': 'Mid line.',
    'Ligne haute — un ballon dans le dos peut tout casser.': 'High line — a ball in behind can break everything open.',
    'Attaque de partout.': 'Attacks from everywhere.',
    "Cherche l'axe.": 'Looks to go through the middle.',
    'Étire le jeu sur les deux ailes.': 'Stretches play on both wings.',
    'Insiste sur son côté droit.': 'Favors its right side.',
    'Insiste sur son côté gauche.': 'Favors its left side.',
    "Ils attendent la transition : ne laissez pas votre ligne trop haute.": "They wait to break: don't push your line too high.",
    "Ils veulent le ballon : allez le leur prendre haut.": 'They want the ball: go and press them high.',
    "Ils jouent long : reculez la ligne et gagnez les seconds ballons.": 'They play long: drop your line and win the second balls.',

    // ── Paliers de carrière + objectifs du tableau de bord ───────────────
    'Premiers pas': 'First Steps',
    'Le conseil vous fait confiance': 'The board trusts you',
    'Reconnaissance': 'Recognition',
    'La presse commence à vous citer': 'The press starts quoting you',
    'Coach confirmé': 'Established Coach',
    'Un sponsor rejoint le projet': 'A sponsor joins the project',
    'Bâtisseur': 'Builder',
    "Vos infrastructures montent d'un cran": 'Your facilities move up a level',
    'Monument': 'Monument',
    'Une légende africaine rejoint votre projet': 'An African legend joins your project',
    'Classements': 'Leaderboards',
    'Obtenu': 'Achieved',
    'Remporter le titre': 'Win the Title',
    'Top 3 en championnat': 'Top 3 in the League',
    'Maintien (Top 10)': 'Stay Up (Top 10)'
};
